let ar = {
  "Categories": "التصنيفات",
  "Language": "لغة",
  "Show Time Zone": "إظهار المنطقة الزمنية",
  "Custom Local Settings": "الإعدادات المحلية المخصصة",
  "Add and showcase events on your site using a beautiful calendar.": "قم بإضافة وعرض الأحداث على موقعك باستخدام تقويم جميل . ",
  "Week Days": "أيام الأسبوع",
  "Manage Events": "إدارة الأحداث",
  "General": "جنرال لواء",
  "Layout Picker": "منتقي التخطيط",
  "Month": "شهر",
  "Monthly": "شهريا",
  "Week": "أسبوع",
  "Weekly": "أسبوعي",
  "Day": "يوم",
  "Daily": "اليومي",
  "Agenda": "جدول أعمال",
  "Navigation Buttons": "أزرار التنقل",
  "Week numbers": "أرقام الأسبوع",
  "Include Weekends": "تضمين عطلات نهاية الأسبوع",
  "All-day": "طوال اليوم",
  "All Day": "طوال اليوم",
  "Label": "ضع الكلمة المناسبة",
  "Fit to Height": "يصلح للارتفاع",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "لتعيين نسب التطبيق تعطيل هذا الخيار يدويًا وتغيير حجم التقويم في محرر. ",
  "Default Layout": "التخطيط الافتراضي",
  "Monthly view": "العرض الشهري",
  "Weekly and Daily view": "العرض الأسبوعي واليومي",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "يمكنك منح الزائرين تجربة أكثر اتساقًا من خلال إظهار نفس العدد من الأسابيع ( 6) في المرة الواحدة.",
  "Fixed Weekly Layout": "تخطيط أسبوعي ثابت",
  "back": " العودة ",
  "Row": "صف",
  "Hours in Weekly View": "الساعات في العرض الأسبوعي",
  "Hours in Daily View": "الساعات في العرض اليومي",
  "Start": "بداية",
  "End": "النهاية",
  "At This Hour": "في هذه الساعة",
  "Add to": "اضف إليه",
  "Button": "زر",
  "Buttons": "وصفت",
  "Sunday": "الأحد",
  "Monday": "الإثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": " الخميس ",
  "Friday": "يوم الجمعة",
  "Saturday": "يوم السبت",
  "Default Date": "التاريخ الافتراضي",
  "year": " السنة ",
  "month": " الشهر ",
  "days": " الأيام ",
  "ago": " قبل ",
  "ahead": " أمام ",
  "Yesterday": "في الامس",
  "Today": "اليوم",
  "Tomorrow": "غدا",
  "Custom": "العادة",
  "Set Daily Rows Limit": "تعيين حد الصفوف اليومية",
  "Set Proportions": "تعيين النسب",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "السماح للزائر بإضافة حدث إلى Calnedars المحلي , Google و Yahoo و Outlook و ICalendar . ",
  "Container": "حاوية",
  "Background": "خلفية",
  "Container Background": "خلفية الحاوية",
  "Container Borders": "حدود الحاوية",
  "Calendar": "التقويم",
  "Event Info Tooltip": "تلميح معلومات الحدث",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "عندما يحوم الناس فوق حدث ما ، سيرون كل المعلومات المتعلقة به في تلميح الأدوات. ",
  "Event Info Window": "نافذة معلومات الحدث",
  "This is the full information window that opens when someone clicks on the event.": "هذه هي نافذة المعلومات الكاملة التي تفتح عندما ينقر شخص ما على الحدث. ",
  "Use Gradient": "استخدم التدرج اللوني",
  "Vertical": "عمودي",
  "Horizontal": "أفقي",
  "First": "أول",
  "Second": "ثانيا",
  "diagonal": " قطري ",
  "Radial": "شعاعي",
  "Select option": "حدد خيار",
  "Solid": "صلب",
  "Dotted": "منقط",
  "Dashed": "متقطع",
  "Double": "مزدوج",
  "Border Radius": "نصف قطر الحدود",
  "Padding": "حشوة",
  "Date Header": "عنوان التاريخ",
  "Event Default Color": "اللون الافتراضي للحدث",
  "Days of Week": "ايام الاسبوع",
  "Days of Week Background": "أيام الأسبو�� الخلفية",
  "Date": "تاريخ",
  "Event Title": "عنوان الحدث",
  "Highlight today": "تسليط الضوء اليوم",
  "Highlight Color": "تسليط الضوء على اللون",
  "Hide": "إخفاء",
  "Calendar Border Color": "لون حدود التقويم",
  "Calendar Border Width": "عرض حدود التقويم",
  "Calendar Border Style": "نمط حدود التقويم",
  "Font Color": "لون الخط",
  "Event Background": "خلفية الحدث",
  "Card Date Color": "لون تاريخ البطاقة",
  "Title Font": "الخط عنوان",
  "Date Font": "خط التاريخ",
  "Description Font": "خط الوصف",
  "Button Background": "زر الخلفية",
  "Button Text": "زر كتابة",
  "Border Color": "لون الحدود",
  "Border Width": "عرض الحدود",
  "Border Type": "نوع الحدود",
  "Title": "عنوان",
  "Description": "وصف",
  "Background Color": "لون الخلفية",
  "Divider": "مقسم",
  "Event Details Font": "خط تفاصيل الحدث",
  "Website Link Color": "لون رابط الموقع",
  "Developer Info": "معلومات المطور",
  "User Guide": "دليل المستخدم",
  "Support e-mail": "دعم البريد الإلكتروني",
  "Our Website": "موقعنا على الانترنت",
  "App Review": "مراجعة التطبيقات",
  "Enjoying App? Leave us a review in the App Market.": "استمتع بالتطبيق؟ اترك لنا مراجعة في سوق التطبيقات. ",
  "Review Us": "راجعنا",
  "Connect With Us": "اتصل بنا",
  "What's your email?": "ما هو بريدك الإلكتروني؟ ",
  "Invalid email address!": "عنوان بريد إلكتروني غير صالح! ",
  "Comments": "تعليقات",
  "We'd love to hear from you. Send us a message.": "نود أن نسمع منك. أرسل لنا رسالة. ",
  "Message must be at least 5 characters long": "يجب ألا يقل طول الرسالة عن 5 أحرف",
  "Send": "إرسال",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "إذا كنت تريد السماح للمستخدم بالتبديل بين طرق عرض التقويم ، فقم بتمكين هذا الخيار واختر طرق العرض التي تريد عرضها. ",
  "Main": "الأساسية",
  "Localize": "تمركز",
  "Settings": "الإعدادات",
  "Layouts": "تخطيطات",
  "Advanced": "المتقدمة",
  "Design": "التصميم",
  "Support": "الدعم",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "تعتمد جميع الإعدادات المحلية (تلقائيًا) على لغتك. إذا كانت لغتك في القائمة ، فليست هناك حاجة لتخصيص هذا القسم.",
  "Date Format": "صيغة التاريخ",
  "Time Format": "تنسيق الوقت",
  "Text Direction": "اتجاه النص",
  "Left to Right": "من اليسار إلى اليمين",
  "Right to Left": "من اليمين الى اليسار",
  "Week Starts On": "يبدأ الأسبوع",
  "Agenda Style": "نمط جدول الأعمال",
  "Classic": "كلاسيك",
  "Modern": "عصري",
  "Agenda Header": "جدول الأعمال",
  "Upcoming Events": "الأحداث القادمة",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "قم بالترقية الآن واحصل على المزيد من الميزات واستمتع بتطبيقك بالكامل!",
  "Upgrade Now": "تحديث الآن",
  "Hosting events that last all day? This lets you show them on your calendar.": "استضافة الأحداث التي تستمر طوال اليوم؟ يتيح لك ذلك إظهارها في التقويم الخاص بك.",
  "24 hours": "24 ساعة",
  "Sat": "يوم السبت",
  "Sun": "الأحد",
  "Mon": "الإثنين",
  "Default": "الافتراضي",
  "Select custom design style for your calendar.": "حدد نمط تصميم مخصص للتقويم الخاص بك.",
  "Style": "قلم المدقة",
  "Styles and Colors": "الأنماط والألوان",
  "Calendar Name": "اسم التقويم",
  "Write your Calendar name here": "اكتب اسم التقو��م الخاص بك هنا",
  "Enable Search": "تمكين البحث",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "هذا غير مرئي للمستخدمين. قم بتعيين أسماء للتمييز بين التقاويم الخاصة بك عند استخدام وظيفة Boom Calendar Sync.",
  "+ Add Event": "+ إضافة حدث",
  "Manage and Sync": "إدارة ومزامنة",
  "Show event details as...": "...إظهار تفاصيل الحدث كـ",
  "Tooltip": "تلميح",
  "Popup": "معلومات مربع",
  "None": "لا شيء",
  "Show Category": "إظهار الفئة",
  "Header Align": "محاذاة الرأس",
  "Show Time": "إظهار وقت الحدث",
  "Hours in Weekly/Daily View": "ساعات في عرض أسبوعي / يومي",
  "Agenda Event Limit": "حد حدث جدول الأعمال",
  "Share Events": "مشاركة الأحداث",
  "Shadow": "ظل",
  "Inner Padding": "الحشو الداخلي",
  "Text": "نص",
  "Active Button Border": "حد زر نشط",
  "Light Mode": "وضع الضوء",
  "Event Text Color": "لون نص الحدث",
  "Dates": "تواريخ",
  "Skeleton": "هيكل عظمي",
  "Skeleton Color": "لون الهيكل العظمي",
  "Width": "عرض",
  "Skeleton Style": "نمط الهيكل العظمي",
  "Color": "اللون",
  "Section Titles": "عناوين الأقسام",
  "Section Content": "محتوى القسم",
  "Header": "الرأس",
  "Map": "خريطة",
  "Standard": "اساسي",
  "Retro": "ريترو",
  "Silver": "فضة",
  "Night": "ليل",
  "Dark": "داكن",
  "Aubergine": "باذنجان",
  "Map Header": "رأس الخريطة",
  "Show Title in mobile": "إظهار العنوان في الجوال",
  "Card": "بطاقة",
  "Card View": "عرض البطاقة",
  "Card background color": "لون خلفية البطاقة",
  "Title font": "الخط عنوان",
  "Desciption font": "خط الوصف",
  "Section font": "قسم الخط",
  "Section divider color": "لون مقسم القس",
  "General Info": "معلومات عامة",
  "Venue": "مكان",
  "Organizer": "منظم",
  "Search": "بحث",
  "calendar": "التقويم",
  "Share this event": "شارك هذا الحدث",
  "Copy event URL": "انسخ عنوان الحدث",
  "Copied!": "علم!",
  "Add & Share": "إضافة ومشاركة",
  "Calendar view": "عرض التقويم",
  "Add Event": "أضف حدث",
  "Uncategorised": "\tغير مصن",
  "More": "أكثر",
  "Less": "أقل",
  "Register": "تسجيل",
  "Guests": "ضيوف",
  "unlimited": "غير محدود",
  "Show more": "أظهر المزيد",
  "Add event": "أضف حدثًا",
  "All Day Event": "حدث طوال اليوم",
  "Location": "موقعك",
  "Choose a category": "اختر فئة",
  "Venue name": "اسم المكان",
  "Venue phone": "هاتف المكان",
  "Venue email": "البريد الإلكتروني للمكان",
  "Venue website": "الموقع الإلكتروني للمكان",
  "Organizer name": "اسم المنظم",
  "Organizer phone": "هاتف المنظم",
  "Organizer email": "البريد الإلكتروني للمنظم",
  "Organizer website": "موقع المنظم",
  "Personal info": "معلومات شخصية",
  "First name": "الاسم الاول",
  "Last name": "الكنية",
  "Email Address": "عنوان البريد الالكترونى",
  "Additional Notes": "ملاحظات إضافية",
  "Back": "عودة",
  "Save": "حفظ",
  "Next": "التالى",
  "Your event has been submitted": "تم تقديم الحدث الخاص بك",
  "Event submittion has been failed": "فشل تقديم الحدث",
  "e.g. Birthday Party": "\tعلى سبيل المثال حفلة عيد ميلاد",
  "First Name": "الاسم الاول",
  "Last Name": "الكنية",
  "Phone Number": "رقم الهاتف",
  "Address": "عنوان",
  "Your comments": "تعليقاتك",
  "How many guests?": "كم عدد الضيوف؟",
  "Anything else we need to know?": "أي شيء آخر نحن بحاجة إلى معرفته؟",
  "Guests:": "ضيوف:",
  "Submit": "إرسال",
  "Go to Calendar": "اذهب إلى التقويم",
  "Registration completed successfully!": "تم التسجيل بنجاح!",
  "Please check your registered email address": "يرجى التحقق م�� عنوان بريدك الإلكتروني المسجل",
  "Add to Calendar": "إضافة إلى التقويم",
  "Share this Event": "شارك هذا الحدث",
  "Sorry something went wrong": "عذرا، هناك خطأ ما",
  "Back to registration": "العودة إلى التسجيل",
  "Date & Location": "التاريخ والمكان",
  "Date & Time": "التاريخ والوقت",
  "home": "الصفحة الرئيسية",
  "Header align": "محاذاة الرأس",
  "Footer": "تذييل",
  "Categories Filter": "الفئات تصفية",
  "Show only upcoming": "عرض القادم فقط",
  "Card(s) in a row": "بطاقة (بطاقات) متتالية",
  "Space between cards": "مسافة بين البطاقات",
  "Shown events limit": "تظهر الأحداث الحد",
  "Style 1": "نمط 1.",
  "Style 2": "النمط 2",
  "Style 3": "النمط 3",
  "Style 4": "النمط 4",
  "Buttons & Links": "أزرار وروابط",
  "Button corner radius": "نصف قطر ركن الزر",
  "Buttons font": "خط الأزرار",
  "Buttons background": "أزرار الخلفية",
  "Get notified by Email": "احصل على إشعار عبر البريد الإلكتروني",
  "Review events": "مراجعة الأحداث",
  "Click on date": "انقر فوق التاريخ",
  "Add Event button": "زر \"إضافة حدث\"",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "تتيح لك مزامنة التقويم دمج أحداثك وجلساتك مع تقويم Boom الخاص بك.",
  "connect": "الاتصال",
  "Synchronized Calendars": "التقاويم المتزامنة",
  "Import events": "أحداث الاستيراد",
  "Disconnect": "قطع الاتصال",
  "Choose calendar": "اختر التقويم",
  "Monitor your Wix events through the sync feature": "راقب أحداث WIX الخاصة بك من خلال ميزة المزامنة",
  "Connect all your Boom calendars available on your website": "قم بتوصيل جميع تقاويم Boom المتوفرة على موقع الويب الخاص بك",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "يمكنك جدولة اجتماعات Zoom والانضمام إليها وإدارتها مباشرةً من خلال تقويم Boom الخاص بنا.",
  "Monitor your Event Brite events through the Event Brite sync feature": "راقب أحداث Event Brite من خلال ميزة مزامنة Event Brite",
  "Email": "بريد الالكتروني",
  "Add-ons": "أضف نحن",
  "Receive notification emails as soon as users add events to your calendar.": "تلقي رسائل البريد الإلكتروني الإخطار بمجرد إضافة المستخدمين إلى التقويم الخاص بك.",
  "Enable + button on the calendar header": "تمكين + زر في رأس التقويم",
  "Accept or decline events added by customers before making them public.": "قبول أو رفض الأحداث المضافة من قبل العملاء قبل جعلهم الجمهور.",
  "Switch Add Event": "تبديل إضافة حدث",
  "Enable your browser cookies to connect to your account.": "قم بتمكين ملفات تعريف الارتباط الخاصة بك للاتصال بحسابك.",
  "Learn more": "يتعلم أكثر",
  "Print Button": "زر طباعة",
  "Permit your users to print your Boom Event Calendar in any date range.": "السماح للمستخدمين بطباعة تقويم حدث طفرة الخاص بك في أي نطاق تاريخ.",
  "Show Title on mobile": "عرض العنوان على الهاتف المحمول",
  "Show Skeleton on mobile": "أظهر هيكل عظمي على الهاتف المحمول",
  "Start 7-day Business trial": "بدء محاكمة الأعمال لمدة 7 أيام",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "استمتع بجميع الميزات غير المحدودة، مثل بيع التذاكر والتسجيل ووظائف حدث الزوار.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "يرجى ملاحظة: في نهاية الفترة التجريبية، سيتم إرجاعك إلى خطة الاشتراك الحالية.",
  "Not Now": "ليس الآن",
  "Start free trial": "بدء التجربة المجانية",
  "Congrats!": "مبروك!",
  "Your 7-day Business trial has been successfully activated.": "تم تنشيط تجربة تجارية تجارية لمدة 7 أيام بنجاح.",
  "Done": "فعله",
  "Title font color": "عنوان الخط اللون",
  "Desciption font color": "وصف الخط اللون",
  "Section font color": "قسم الخط اللون",
  "Card Header": "رأس البطاقة",
  "Category": "فئة",
  "Display at the": "عرض في",
  "top": "أعلى",
  "bottom": "قاع",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "عرض مرشح الفئة في الأعلى أو في الجزء السفلي من التقويم.تنطبق الإعدادات على جدول الأعمال وآراء الأوراق فقط",
  "Processing your events": "معالجةالأحداث",
  "Search for events": "البحث عن الأحداث",
  "There are no events added": "لا توجد أحداث مضافة",
  "Location: To be determined": "الموقع: أن تكون مصممة",
  "No events for selected date": "لا توجد أحداث للتاريخ المحدد",
  "Uncategorized": "غير مصنف",
  "Edit event": "تحرير الحدث",
  "Edit original event": "تحرير الحدث الأصلي",
  "Copy event": "نسخ الحدث",
  "Copy as new event": "نسخ كحدث جديد",
  "Delete event": "حذف الحدث",
  "Stop repeating on this date": "توقف عن التكرار في هذا التاريخ",
  "Exclude this date": "استبعاد هذا التاريخ",
  "Location is going to be announced": "سيتم الإعلان عن الموقع",
  "Fill your personal information": "املأ معلوماتك الشخصية",
  "Check Box": "خانة الاختيار",
  "Single Choice": "اختيار واحد",
  "Option": "خيار",
  "Share Event": "شارك الحدث",
  "Oops! Something went wrong": "أُووبس!هناك خطأ ما",
  "We are sorry this event has already taken place": "نحن آسفون أن هذا الحدث قد حدث بالفعل",
  "Back to calendar": "العودة إلى التقويم",
  "This field is required": "هذه الخانة مطلوبه",
  "Phone": "هاتف",
  "Number field": "حقل الرقم",
  "Option": "خيار",
  "Check Box": "خانة الاختيار",
  "Single Choice": "اختيار واحد",
 "Please provide a valid email" : "يرجى تقديم عنوان بريد إلكتروني صالح",
 "Select at least one option" : "حدد خيارًا واحدًا على الأقل",
 "Choose tickets to see total value" : "اختر التذاكر لرؤية القيمة الإجمالية",
 "tickets" : "التذاكر",
 "Choose Tickets" : "اختر التذاكر",
 "Choose payment method" : "اختر وسيلة الدفع",
 "Pay" : "يدفع",
 "Total" : "المجموع",
 "Free" : "حر",
 "Buy tickets" : "اشتري تذاكر",
 "Sold Out" : "نفذ",
 "Tickets are available" : "التذاكر متوفرة",
 "Sales End" : "نهاية المبيعات",
 "Buy tickets" : "اشتري تذاكر",
 "Availible from" : "متاح من",
 "You will soon receive a confirmation message of successful registration to your email address. You can also check your order details below." : "ستتلقى قريبًا رسالة تأكيد للتسجيل الناجح إلى عنوان بريدك الإلكتروني.يمكنك أيضًا التحقق من تفاصيل طلبك أدناه.",
 "Go to Orders" : "اذهب إلى الطلبات",
 "Go to Details" : "انتقل إلى التفاصيل",
 "Group ticket" : "تذكرة المجموعة",
 "Name" : "اسم",
 "Price" : "سعر",
 "Order by" : "ترتيب حسب",
 "Order ID" : "رقم التعريف الخاص بالطلب"
}
export default ar