let bg = {
  "Categories": "Категории",
  "Share this event": "Споделете това събитие",
  "Language": "Език",
  "Show Time Zone": "Показване на часовата зона",
  "Custom Local Settings": "Персонализирани локални настройки",
  "Add and showcase events on your site using a beautiful calendar.": "Добавете и покажете събития на вашия сайт с помощта на красив календар .",
  "Week Days": "Седмични дни",
  "Manage Events": "Управление на събития",
  "General": "Общ",
  "Layout Picker": "Избор на оформление",
  "Month": "Месец",
  "Monthly": "Месечно",
  "Week": "Седмица",
  "Weekly": "Cедмично",
  "Day": "Ден",
  "Daily": "Дейли",
  "Agenda": "Дневен ред",
  "Navigation Buttons": "Бутони за навигация",
  "Week numbers": "Седмични номера",
  "Include Weekends": "Включване на уикендите",
  "All-day": "Цял ден",
  "All Day": "Цял ден",
  "Label": "Етикет",
  "Fit to Height": "Подходящ на височина",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "За да зададете пропорциите на приложението, деактивирайте тази опция и промените размера на календара в редактора.",
  "Default Layout": "Оформление по подразбиране",
  "Monthly view": "Месечен изглед",
  "Weekly and Daily view": "Седмичен и дневен изглед",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Можете да дадете на посетителите по- последователно изживяване, като показвате един и същ брой седмици( 6) наведнъж.",
  "Fixed Weekly Layout": "Фиксирана седмична оформление",
  "back": " назад ",
  "Row": "Ред",
  "Hours in Weekly View": "Часове в седмичен изглед",
  "Hours in Daily View": "Часове в ежедневен изглед",
  "Start": "Започнете",
  "End": "Край",
  "At This Hour": "В този час",
  "Add to": "Добави към",
  "Button": "Бутон",
  "Buttons": "Бутони",
  "Sunday": "В неделя",
  "Monday": "Понеделник",
  "Tuesday": "Вторник",
  "Wednesday": "Сряда",
  "Thursday": " Четвъртък ",
  "Friday": "Петък",
  "Saturday": "Събота",
  "Default Date": "Дата по подразбиране",
  "year": " година ",
  "month": " месец ",
  "days": " дни ",
  "ago": " преди ",
  "ahead": " напред ",
  "Yesterday": "Вчера",
  "Today": "Днес",
  "Tomorrow": "Утре",
  "Custom": "Персонализиран",
  "Set Daily Rows Limit": "Задайте лимит на дневните редове",
  "Set Proportions": "Задаване на пропорции",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Разрешете на посетителя да добави събитие към местните Calnedars, Google, Yahoo, Outlook, ICalendar .",
  "Container": "Контейнер",
  "Background": "Заден план",
  "Container Background": "Фон на контейнера",
  "Container Borders": "Граници на контейнери",
  "Calendar": "Календар",
  "Event Info Tooltip": "Подсказка за информация за събитието",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Когато хората задръжте курсора на дадено събитие, те ще видят цялата информация за него в подсказка.",
  "Event Info Window": "Прозорец за информация за събитието",
  "This is the full information window that opens when someone clicks on the event.": "Това е пълният информационен прозорец, който се отваря, когато някой кликне върху събитието.",
  "Use Gradient": "Използвайте градиент",
  "Vertical": "Вертикална",
  "Horizontal": "Хоризонтално",
  "First": "На първо място",
  "Second": "Втора",
  "diagonal": " диагонал ",
  "Radial": "Радиално",
  "Select option": "Изберете опция",
  "Solid": "Solid",
  "Dotted": "Пунктирана",
  "Dashed": "Дяволски",
  "Double": "Double",
  "Border Radius": "Граничен радиус",
  "Padding": "Празно",
  "Date Header": "Заглавие на дата",
  "Event Default Color": "Цвят по подразбиране на събитието",
  "Days of Week": "Дни от седмицата",
  "Days of Week Background": "Дни на седмицата",
  "Date": "Дата",
  "Event Title": "Заглавие на събитието",
  "Highlight today": "Отбележете днес",
  "Highlight Color": "Цвят на подчертаване",
  "Hide": "Крия",
  "Calendar Border Color": "Цвят на границата на календара",
  "Calendar Border Width": "Ширина на границата на календара",
  "Calendar Border Style": "Календар на границата на календара",
  "Font Color": "Цвят на шрифта",
  "Event Background": "Фон на събитието",
  "Card Date Color": "Цвят на датата на картата",
  "Title Font": "Шрифт на заглавието",
  "Date Font": "Шрифт за дата",
  "Description Font": "Шрифт с описание",
  "Button Background": "Фон на бутона",
  "Button Text": "Текст на бутона",
  "Border Color": "Цвят на границата",
  "Border Width": "Ширина на границата",
  "Border Type": "Тип граница",
  "Title": "Заглавие",
  "Description": "Описание",
  "Background Color": "Цвят на фона",
  "Divider": "Разделител",
  "Event Details Font": "Шрифт за подробности за събитието",
  "Website Link Color": "Цвят на връзката към уебсайта",
  "Developer Info": "Информация за програмисти",
  "User Guide": "Упътване за употреба",
  "Support e-mail": "Поддръжка на имейл",
  "Our Website": "Нашият уебсайт",
  "App Review": "Преглед на приложението",
  "Enjoying App? Leave us a review in the App Market.": "Наслаждавате се на приложението? Оставете ни преглед в App Market.",
  "Review Us": "Прегледайте ни",
  "Connect With Us": "Свържи се с нас",
  "What's your email?": "Какъв е вашият имейл?",
  "Invalid email address!": "Невалиден имейл адрес! ",
  "Comments": "Коментари",
  "We'd love to hear from you. Send us a message.": "Ще се радваме да се свържем с вас.Изпратете ни съобщение.",
  "Message must be at least 5 characters long": "Съобщението трябва да е поне 5 знака",
  "Send": "Изпрати",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Ако искате да се даде възможност на потребителя да превключвате между екраните на календара, активирайте тази опция и изберете вижданията, които искате да се показват. ",
  "Main": "Основен",
  "Localize": "Локализирам",
  "Settings": "Настройки",
  "Layouts": "Формати",
  "Advanced": "Напреднал",
  "Design": "Дизайн",
  "Support": "Поддържа",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Всички локални настройки са (автоматично) въз основа на вашия език. Ако вашият език е в списъка, няма нужда да персонализирате този раздел.",
  "Date Format": "Формат на да��ата",
  "Time Format": "Времеви формат",
  "Text Direction": "Посочване на текст",
  "Left to Right": "Отляво надясно",
  "Right to Left": "От дясно на ляво",
  "Week Starts On": "Седмицата започва на",
  "Agenda Style": "Стил на дневния ред:",
  "Classic": "класически",
  "Modern": "модерен",
  "Agenda Header": "Заглавие на дневния ред",
  "Upcoming Events": "Предстоящи събития",
  "Agenda Event Limit": "Ограничение на събитията в дневния ред",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Надстройте сега и получете много повече функции и се наслаждавайте изцяло на приложението си !",
  "Upgrade Now": "Надстройка сега:",
  "Hosting events that last all day? This lets you show them on your calendar.": "Хостинг събития, които продължават цял ​​ден? Това ви позволява да ги показвате в календара си.",
  "24 hours": "24 часа",
  "Sun": "Неделя",
  "Mon": "Понед",
  "Sat": "Събота",
  "Default": "По подразбиране",
  "Select custom design style for your calendar.": "Изберете персонализиран стил на дизайн за вашия календар.",
  "Style": "Стил",
  "Styles and Colors": "Стилове и цветове",
  "Calendar Name": "Име на календара",
  "Write your Calendar name here": "Напишете името на календара си тук",
  "Enable Search": "Активиране на търсенето",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Това не се вижда от вашите потребители. Задайте имена, за да разграничите вашите календари, когато използвате функцията Boom Calendar Sync.",
  "+ Add Event": "+ Добавяне на събитие",
  "Manage and Sync": "Управление и синхронизиране",
  "Show event details as...": "Показване на подробности за събитието като ...",
  "Tooltip": "Подсказка",
  "Popup": "информационно поле",
  "None": "Нито един",
  "Show Category": "Показване на категория",
  "Header Align": "Подравняване на заглавката",
  "Show Time": "Време за шоу",
  "Hours in Weekly/Daily View": "Часове в седмичен / ежедневен изглед",
  "Share Events": "Споделяйте събития",
  "Shadow": "сянка",
  "Inner Padding": "Вътрешна подплънка",
  "Text": "Текст",
  "Active Button Border": "Активна граница на бутона",
  "Light Mode": "Светлинен режим",
  "Event Text Color": "Цвят на текста на събитието",
  "Dates": "Дати",
  "Skeleton": "скелет",
  "Skeleton Color": "Цвят на скелета",
  "Width": "широчина",
  "Skeleton Style": "Скелет стил",
  "Color": "Цвят",
  "Section Titles": "Заглавия на раздели",
  "Section Content": "Съдържание на раздела",
  "Header": "удар с глава",
  "Map": "Карта",
  "Standard": "Стандартен",
  "Retro": "Ретро",
  "Silver": "Сребро",
  "Night": "Нощ",
  "Dark": "Тъмно",
  "Aubergine": "Патладжан",
  "Map Header": "Заглавие на картата",
  "Show Title in mobile": "Показване на заглавието в мобилни устройства",
  "Card": "Карта",
  "Card View": "Изглед на карта",
  "Card background color": "Цвят на фона на картата",
  "Title font": "Шрифт на заглавието",
  "Desciption font": "Desciption font",
  "Section font": "Раздел за шрифтове",
  "Section divider color": "Цвят на разделител на раздели",
  "General Info": "Обща информация",
  "Venue": "Място на провеждане",
  "Organizer": "Организатор",
  "Search": "Търсене",
  "calendar": "календар",
  "Copy event URL": "Копирайте URL адреса на събитието",
  "Copied!": "Копирано!",
  "Add & Share": "Добавяне и споделяне",
  "Calendar view": "Изглед на календараم",
  "Add Event": "Добавяне на събитие",
  "Uncategorised": "Без категория",
  "More": "Повече",
  "Less": "По-малко",
  "Register": "Регистрирам",
  "Guests": "Гости",
  "unlimited": "неограничен",
  "Show more": "Покажи повече",
  "Add event": "Добавяне на събитие",
  "All Day Event": "Целодневно събитие",
  "Location": "Местоположение",
  "Choose a category": "Избери категория",
  "Venue name": "Име на място",
  "Venue phone": "Телефон на място",
  "Venue email": "Имейл на място",
  "Venue website": "Уебсайт на място",
  "Organizer name": "Име на организатора",
  "Organizer phone": "Телефон за организатор",
  "Organizer email": "Имейл на организатора",
  "Organizer website": "Уебсайт на организатора",
  "Personal info": "Лична информация",
  "First name": "Първо име",
  "Last name": "Фамилия",
  "Email Address": "Имейл адрес",
  "Additional Notes": "допълнителни бележки",
  "Back": "обратно",
  "Save": "Запазете",
  "Next": "Следващия",
  "Your event has been submitted": "Вашето събитие е изпратено",
  "Event submittion has been failed": "Подаването на събитие е неуспешно",
  "e.g. Birthday Party": "напр. Парти за рожден ден",
  "First Name": "Първо име",
  "Last Name": "Фамилия",
  "Phone Number": "Телефонен номер",
  "Address": "Адрес",
  "Your comments": "Твоите коментари",
  "How many guests?": "Колко гости?",
  "Anything else we need to know?": "Още нещо, което трябва да знаем?",
  "Guests:": "Гости:",
  "Submit": "Изпращане",
  "Go to Calendar": "Отидете в Календар",
  "Registration completed successfully!": "Регистрацията завърши успешно!",
  "Please check your registered email address": "Моля, проверете вашия регистриран имейл адрес",
  "Add to Calendar": "Добавяне към календара",
  "Share this Event": "Споделете това събитие",
  "Sorry something went wrong": "Съжалявам нещо се обърка",
  "Back to registration": "Обратно към регистрацията",
  "Date & Location": "Дата и местоположение",
  "Date & Time": "Време за среща",
  "home": "У дома",
  "Header align": "Подравняване на заглавката",
  "Footer": "Долен колонтитул",
  "Categories Filter": "категории Филтър",
  "Show only upcoming": "Показвайте само предстоящите",
  "Card(s) in a row": "Карти (и) в ред",
  "Space between cards": "Интервал между картите",
  "Shown events limit": "Ограничение за показани събития",
  "Style 1": "Стил 1.",
  "Style 2": "Стил 2.",
  "Style 3": "Стил 3",
  "Style 4": "Стил 4",
  "Buttons & Links": "Бутони и връзки",
  "Button corner radius": "Радиус на ъгъла на бутона",
  "Buttons font": "Шрифт на бутоните",
  "Buttons background": "Фон на бутоните",
  "Get notified by Email": "Получете известие по имейл",
  "Review events": "Прегледайте събития",
  "Click on date": "Кликнете върху дата",
  "Add Event button": "Добавяне на бутон за събитие",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Синхронизирането на календара ви позволява да интегрирате вашите събития и сесии с вашия Boom Calendar.",
  "connect": "свържете",
  "Synchronized Calendars": "Синхронизирани календари",
  "Import events": "Импортиране на събития",
  "Disconnect": "Прекъсване",
  "Choose calendar": "Изберете календар",
  "Monitor your Wix events through the sync feature": "Наблюдавайте вашите събития от Wix чрез функцията за синхронизиране",
  "Connect all your Boom calendars available on your website": "Свържете всичките си Boom календари, налични на вашия уебсайт",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "График, присъединяване и управление на срещи за мащабиране точно чрез нашия бум календар.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Наблюдавайте събития за събития чрез функцията за синхронизиране на Event Brite",
  "Email": "електронна поща",
  "Add-ons": "Добавки",
  "Receive notification emails as soon as users add events to your calendar.": "Получаване на имейли за известяване веднага след като потребителите добавят събития към вашия календар.",
  "Enable + button on the calendar header": "Активиране + бутон на календарния заглавие",
  "Accept or decline events added by customers before making them public.": "Приемайте или намалете събития, добавени от клиентите, преди да ги направите публично.",
  "Switch Add Event": "Превключване Добавяне на събитие",
  "Enable your browser cookies to connect to your account.": "Активирайте бисквитките на браузъра да се свържете с профила си.",
  "Learn more": "Научете повече",
  "Print Button": "Бутон за печат",
  "Permit your users to print your Boom Event Calendar in any date range.": "Позволете на потребителите да отпечатат вашия календар на събитието на бум във всеки диапазон на датата.",
  "Show Title on mobile": "Показване на заглавието на мобилен телефон",
  "Show Skeleton on mobile": "Покажи скелета на мобилен телефон",
  "Start 7-day Business trial": "Започнете 7-дневния си бизнес процес",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Насладете се на всички неограничени функции, като продажба на билети, регистрация, добавки за събития на посетители.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Моля, обърнете внимание: В края на пробния период ще бъдете върнати в съществуващия си абонаментен план.",
  "Not Now": "Не сега",
  "Start free trial": "Започнете безплатен пробен период",
  "Congrats!": "Поздравления!",
  "Your 7-day Business trial has been successfully activated.": "Вашият 7-дневен бизнес процес е активиран успешно.",
  "Done": "Свършен",
  "Title font color": "Цвят на заглавието на шрифта",
  "Desciption font color": "Описание Цвят на шрифта",
  "Section font color": "Секция Цвят на шрифта",
  "Card Header": "Главна карта",
  "Category": "Категория",
  "Display at the": "Дисплей в",
  "top": "Горна част",
  "bottom": "дъно",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Покажете филтъра от категорията в горната част или в долната част на календара.Настройките се прилагат само за дневния ред и възгледите на картите",
  "Processing your events": "Обработка на вашите събития",
  "Search for events": "Търсене на събития",
  "There are no events added": "Няма добавени събития",
  "Location: To be determined": "Местоположение: да се определи",
  "No events for selected date": "Няма събития за избрана дата",
  "Uncategorized": "Без категория",
  "Edit event": "Редактиране на събитие",
  "Edit original event": "Редактиране на оригинално събитие",
  "Copy event": "Събитие за копиране",
  "Copy as new event": "Копиране като ново събитие",
  "Delete event": "Изтриване на събитие",
  "Stop repeating on this date": "Спрете да повтаряте на тази дата",
  "Exclude this date": "Изключете тази дата",
  "Location is going to be announced": "Местоположението ще бъде обявено",
  "Fill your personal information": "Попълнете личната си информация",
  "Check Box": "Отметка в квадратчето",
  "Single Choice": "Единичен избор",
  "Option": "Опция",
  "Share Event": "Споделете събитие",
  "Oops! Something went wrong": "Ами!Нещо се обърка",
  "We are sorry this event has already taken place": "Съжаляваме, че това събитие вече се е състояло",
  "Back to calendar": "Обратно към календара",
  "This field is required": "Това поле е задължително",
  "Phone": "Телефон",
  "Number field": "Поле за число",
  "Option": "Опция",
  "Check Box": "Отметка в квадратчето",
  "Single Choice": "Единичен избор",
 "Please provide a valid email" : "Моля, предоставете валиден имейл",
 "Select at least one option" : "Изберете поне една опция",
 "Choose tickets to see total value" : "Изберете билети, за да видите общата стойност",
 "tickets" : "билети",
 "Choose Tickets" : "Изберете билети",
 "Choose payment method" : "Изберете начин на плащане",
 "Pay" : "Плащане",
 "Total" : "Обща сума",
 "Free" : "Безплатно",
 "Buy tickets" : "Купи билети",
 "Sold Out" : "Продадено",
 "Tickets are available" : "Предлагат се билети",
 "Sales End" : "Край на продажбите",
 "Buy tickets" : "Купи билети",
 "Availible from" : "Достъпен от",
 "You will soon receive a confirmation message of successful registration to your email address. You can also check your order details below." : "Скоро ще получите съобщение за потвърждение за успешна регистрация на вашия имейл адрес.Можете също да проверите данните си за поръчката по -долу.",
 "Go to Orders" : "Отидете на поръчки",
 "Go to Details" : "Отидете на подробности",
 "Group ticket" : "Групов билет",
 "Name" : "Име",
 "Price" : "Цена",
 "Order by" : "Подредени по",
 "Order ID" : "ID на поръчка",
 "Group ticket" : "Групов билет",
 "Name" : "Име",
 "Price" : "Цена",
 "Order by" : "Подредени по",
 "Order ID" : "ID на поръчка",
 "Applied" : "Прилага се",
 "Fees" : "Такси"
}
export default bg