let de = {


   /* add event pop-up start*/
  "e.g. Birthday Party": "z.B. Geburtstagsparty",
  "Organizer": "Veranstalter",
  "Location is going to be announced": "Der Standort wird bekannt gegeben",
  "Add Event": "Ereignis hinzufügen",
  "All Day Event": "Ganztägige Veranstaltung",
  "Location": "Ort",
  "General Info": "Allgemeine Information",
  "Description": "Beschreibung",
  "Next": "Nächster",
   "Make your contribution by adding your event to the calendar" : "Machen Sie Ihren Beitrag, indem Sie Ihr Ereignis in den Kalender hinzufügen",
 "Event name" : "Veranstaltungsname",
 "Start time" : "Startzeit",
 "End time" : "Endzeit",
 "Physical location" : "Physischer Standort",
 "Online" : "Online",
 "To be announced" : "Angekündigt werden",
 "Add Image" : "Bild hinzufügen",
 "Event color" : "Ereignisfarbe",
 "Choose categories" : "Wählen Sie Kategorien",
 "There are no categories to select" : "Es gibt keine Kategorien zur Auswahl",
 "Location name" : "Standortnamen",
 "Location email" : "Ort E -Mail",
 "Location phone" : "Standort Telefon",
 "Location website" : "Standortwebsite",
 "Organizer name" : "Organisator Name",
 "Organizer phone" : "Organisator Telefon",
 "Organizer email" : "Organizer -E -Mail",
 "Organizer website" : "Organisator -Website",
/* add event pop-up end*/

  "Categories": "Kategorien",
  "Share this event": "Teile dieses Ereignis",
  "Language": "Sprache",
  "Show Time Zone": "Zeitzone anzeigen",
  "Custom Local Settings": "Benutzerdefinierte lokale Einstellungen",
  "Add and showcase events on your site using a beautiful calendar.": "Hinzufügen und Präsentieren von Ereignissen auf Ihrer Website mithilfe eines schönen Kalenders.",
  "Week Days": "Wochentage",
  "Manage Events": "Ereignisse verwalten",
  "General": "Allgemeines",
  "Layout Picker": "Layoutauswahl",
  "Month": "Monat",
  "Monthly": "Monatlich",
  "Week": "Woche",
  "Weekly": "Wöchentlich",
  "Day": "Tag",
  "Daily": "Täglich",
  "Agenda": "Agenda",
  "Navigation Buttons": "Navigationstasten",
  "Week numbers": "Wochennummern",
  "Include Weekends": "Wochenenden einschließen",
  "All-day": "Den ganzen Tag",
  "All Day": "Den ganzen Tag",
  "Label": "Etikette",
  "Fit to Height": "An Höhe anpassen",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Um die App-Proportionen festzulegen, deaktivieren Sie diese Option manuell und ändern Sie die Größe des Kalenders im Editor.",
  "Default Layout": "Standardlayout",
  "Monthly view": "Monatsansicht",
  "Weekly and Daily view": "Wochen- und Tagesansicht",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Sie können den Besuchern ein einheitlicheres Erlebnis bieten, indem Sie die gleiche Anzahl von Wochen (6) gleichzeitig anzeigen.",
  "Fixed Weekly Layout": "Fixed Weekly Layout",
  "back": "zurück",
  "Row": "Reihe",
  "Hours in Weekly View": "Stunden in Wochenansicht",
  "Hours in Daily View": "Stunden in Tagesansicht",
  "Start": "Start",
  "End": "Ende",
  "At This Hour": "Zu dieser Stunde",
  "Add to": "Hinzufügen",
  "Button": "Taste",
  "Buttons": "Tasten",
  "Sunday": "Sonntag",
  "Monday": "Montag",
  "Tuesday": "Dienstag",
  "Wednesday": "Mittwoch",
  "Thursday": "Dienstag",
  "Friday": "Freitag",
  "Saturday": "Samstag",
  "Default Date": "Standarddatum",
  "year": "Jahr",
  "month": "Monat",
  "mo": "Monat",
  "days": "Tage",
  "ago": "vor",
  "ahead": "voraus",
  "Yesterday": "Gestern",
  "Today": "Heute",
  "Tomorrow": "Morgen",
  "Custom": "Brauch",
  "Set Daily Rows Limit": "Tägliches Zeilenlimit festlegen",
  "Set Proportions": "Proportionen einstellen",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Erlaube dem Besucher, Ereignisse zu lokalen Kalendern hinzuzufügen, Google, Yahoo, Outlook, ICalendar.",
  "Container": "Container",
  "Background": "Hintergrund",
  "Container Background": "Container Hintergrund",
  "Container Borders": "Containerränder",
  "Calendar": "Kalender",
  "Event Info Tooltip": "Event Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Wenn Leute über ein Ereignis fahren, sehen sie alle Informationen dazu in einem Tooltipp.",
  "Event Info Window": "Event Info Fenster",
  "This is the full information window that opens when someone clicks on the event.": "Dies ist das vollständige Informationsfenster, das geöffnet wird, wenn jemand auf das Ereignis klickt.",
  "Use Gradient": "Farbverlauf verwenden",
  "Vertical": "Vertikale",
  "Horizontal": "Horizontal",
  "First": "Zuerst",
  "Second": "Zweite",
  "diagonal": "diagonal",
  "Radial": "Radial",
  "Select option": "Wähle eine Option",
  "Solid": "Solide",
  "Dotted": "Gepunktet",
  "Dashed": "Gestrichelt",
  "Double": "Doppelt",
  "Border Radius": "Border Radius",
  "Padding": "Polsterung",
  "Date Header": "Date Header",
  "Event Default Color": "Ereignisstandardfarbe",
  "Days of Week": "Wochentage",
  "Days of Week Background": "Wochentage Hintergrund",
  "Date": "Datum",
  "Event Title": "Veranstaltungstitel",
  "Highlight today": "Highlight heute",
  "Highlight Color": "Hervorhebungsfarbe",
  "Hide": "Verbergen",
  "Calendar Border Color": "Kalenderrahmenfarbe",
  "Calendar Border Width": "Breite des Kalenderrahmens",
  "Calendar Border Style": "Kalenderrahmenstil",
  "Font Color": "Schriftfarbe",
  "Event Background": "Event Hintergrund",
  "Card Date Color": "Kartendatum Farbe",
  "Title Font": "Überschrift",
  "Date Font": "Datumsschrift",
  "Description Font": "Beschreibungsschrift",
  "Button Background": "Button Hintergrund",
  "Button Text": "Schaltflächentext",
  "Border Color": "Randfarbe",
  "Border Width": "Rahmenbreite",
  "Border Type": "Randtyp",
  "Title": "Titel",
  "Background Color": "Hintergrundfarbe",
  "Divider": "Teiler",
  "Event Details Font": "Schriftart für Ereignisdetails",
  "Website Link Color": "Farbe des Website-Links",
  "Developer Info": "Entwickler info",
  "User Guide": "Benutzerhandbuch",
  "Support e-mail": "Support-E-Mail",
  "Our Website": "Unsere Internetseite",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.": "App genießen? Hinterlassen Sie uns eine Bewertung im App-Markt.",
  "Review Us": "Überprüfen Sie uns",
  "Connect With Us": "Verbinde dich mit uns",
  "What's your email?": "Wie ist deine E-Mail adresse?",
  "Invalid email address!": "Ungültige E-Mail-Adresse!",
  "Comments": "Bemerkungen",
  "We'd love to hear from you. Send us a message.": "Wir würden gerne von Ihnen hören. Senden Sie uns eine Nachricht.",
  "Message must be at least 5 characters long": "Msgstr Nachricht muss mindestens 5 Zeichen lang sein",
  "Send": "Senden",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Wenn Sie dem Benutzer erlauben möchten, zwischen Kalenderansichten zu wechseln, aktivieren Sie diese Option und wählen Sie die Ansichten aus, die Sie anzeigen möchten.",
  "Main": "Main",
  "Localize": "Lokalisieren",
  "Settings": "die Einstellungen",
  "Layouts": "Anordnung",
  "Advanced": "Fortgeschritten",
  "Design": "Entwurf",
  "Support": "Unterstützung",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alle lokalen Einstellungen basieren (automatisch) auf Ihrer Sprache. Wenn Ihre Sprache in der Liste aufgeführt ist, müssen Sie diesen Abschnitt nicht anpassen.",
  "Date Format": "Datumsformat",
  "Time Format": "Zeitformat",
  "Text Direction": "Textrichtung",
  "Left to Right": "Links nach rechts",
  "Right to Left": "Rechts nach links",
  "Week Starts On": "Woche beginnt am",
  "Agenda Style": "Agenda Style",
  "Classic": "Klassisch",
  "Modern": "Modern",
  "Agenda Header": "Agenda Header",
  "Upcoming Events": "Kommende Veranstaltungen",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Rüsten Sie jetzt auf und erhalten Sie viel mehr Funktionen und genießen Sie Ihre APP in vollem Umfang!",
  "Upgrade Now": "Jetzt upgraden",
  "Hosting events that last all day? This lets you show them on your calendar.": "Bewirtung von Events, die den ganzen Tag dauern? So können Sie sie in Ihrem Kalender anzeigen.",
  "24 hours": "24 Stunden",
  "Sat": "Sam",
  "Sun": "Son",
  "Mon": "Mon",
  "Default": "Standard",
  "Select custom design style for your calendar.": "Wählen Sie einen benutzerdefinierten Designstil für Ihren Kalender.",
  "Style": "Stil",
  "Styles and Colors": "Stile und Farben",
  "Calendar Name": "Kalendername",
  "Write your Calendar name here": "Geben Sie hier Ihren Kalendernamen ein",
  "Enable Search": "Suche aktivieren",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Dies ist für Ihre Benutzer nicht sichtbar. Legen Sie Namen fest, um Ihre Kalender zu unterscheiden, wenn Sie die Boom Calendar Sync-Funktion verwenden.",
  "+ Add Event": "+ Ereignis hinzufügen",
  "Manage and Sync": "Verwalten und synchronisieren",
  "Show event details as...": "Eventdetails anzeigen als ...",
  "Tooltip": "Tooltip",
  "Popup": "Infobox",
  "None": "Keiner",
  "Show Category": "Kategorie anzeigenHeader ausrichten",
  "Header Align": "Header ausrichten",
  "Show Time": "Show Time",
  "Hours in Weekly/Daily View": "Stunden in wöchentlicher / täglicher Ansicht",
  "Share Events": "Ereignisse teilen",
  "Shadow": "Schatten",
  "Inner Padding": "Innenpolsterung",
  "Text": "Text",
  "Active Button Border": "Aktiver Tastenrand",
  "Light Mode": "Lichtmodus",
  "Event Text Color": "Ereignistextfarbe",
  "Dates": "Termine",
  "Skeleton": "Skelett",
  "Skeleton Color": "Skelettfarbe",
  "Width": "Breite",
  "Skeleton Style": "Skelett-Stil",
  "Color": "Farbe",
  "Section Titles": "Abschnittsüberschriften",
  "Section Content": "Abschnitt Inhalt",
  "Header": "Header",
  "Map": "Karte",
  "Standard": "Standard",
  "Retro": "Retro",
  "Silver": "Silber",
  "Night": "Nacht",
  "Dark": "Dunkel",
  "Aubergine": "Aubergine",
  "Map Header": "Kartenkopf",
  "Show Title in mobile": "Titel im Handy anzeigen",
  "Card": "Karte",
  "Card View": "Kartenansicht",
  "Card background color": "Kartenhintergrundfarbe",
  "Title font": "Überschrift",
  "Desciption font": "Beschreibung Schriftart",
  "Section font": "Schriftbereich",
  "Section divider color": "Schnittteilerfarbe",
  "Venue": "Veranstaltungsort",
  "Search": "Suche",
  "calendar": "Kalender",
  "Copy event URL": "Ereignis-URL kopieren",
  "Copied!": "Kopiert!",
  "Add & Share": "Hinzufügen und teilen",
  "Calendar view": "Kalenderansicht",
  "Uncategorised": "Nicht kategorisiert",
  "More": "Mehr",
  "Less": "Weniger",
  "Register": "Registrieren",
  "Guests": "Gäste",
  "unlimited": "unbegrenzt",
  "Show more": "Zeig mehr",
  "Add event": "Ereignis hinzufügen",
  "Choose a category": "Wähle eine Kategorie",
  "Venue name": "Veranstaltungsort Namen",
  "Venue phone": "Veranstaltungsort Telefon",
  "Venue email": "Veranstaltungsort E-Mail",
  "Venue website": "Veranstaltungsort Website",
  "Personal info": "Persönliche Informationen",
  "First name": "Vorname",
  "Last name": "Familienname, Nachname",
  "Email Address": "E-Mail-Addresse",
  "Additional Notes": "Zusätzliche Bemerkungen",
  "Back": "Zurück",
  "Save": "Speichern",
  "Your event has been submitted": "Ihre Veranstaltung wurde eingereicht",
  "Event submittion has been failed": "Ereignisübermittlung ist fehlgeschlagen",
  "First Name": "Vorname",
  "Last Name": "Familienname, Nachname",
  "Phone Number": "Telefonnummer",
  "Address": "Adresse",
  "Your comments": "Deine Kommentare",
  "How many guests?": "Wie viele Gäste?",
  "Anything else we need to know?": "Was müssen wir noch wissen?",
  "Guests:": "Gäste:",
  "Submit": "einreichen",
  "Go to Calendar": "Gehen Sie zum Kalender",
  "Registration completed successfully!": "Registrierung erfolgreich abgeschlossen!",
  "Please check your registered email address": "Bitte überprüfen Sie Ihre registrierte E-Mail-Adresse",
  "Add to Calendar": "Zum Kalender hinzufügen",
  "Share this Event": "Teile dieses Ereignis",
  "Sorry something went wrong": "Entschuldigung, etwas ist schief gelaufen",
  "Back to registration": "Zurück zur Registrierung",
  "Date & Location": "Datum & Ort",
  "Date & Time": "Terminzeit",
  "home": "Zuhause",
  "Header align": "Header ausrichten",
  "Footer": "Fusszeile",
  "Categories Filter": "Kategorienfilter",
  "Show only upcoming": "Show nur in Kürze",
  "Card(s) in a row": "Karte (n) hintereinander",
  "Space between cards": "Abstand zwischen den Karten",
  "Shown events limit": "Limit für angezeigte Ereignisse",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Stil 4",
  "Buttons & Links": "Buttons & Links.",
  "Button corner radius": "Eckenradius der Schaltfläche",
  "Buttons font": "Buttons Schriftart",
  "Buttons background": "Schaltflächen Hintergrund",
  "Get notified by Email": "Lassen Sie sich per E-Mail benachrichtigen",
  "Review events": "Überprüfen Sie Ereignisse",
  "Click on date": "Klicken Sie auf Datum",
  "Add Event button": "Schaltfläche Ereignis hinzufügen",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Mit der Kalendersynchronisierung können Sie Ihre Ereignisse und Sitzungen in Ihren Boom-Kalender integrieren.",
  "connect": "verbinden",
  "Synchronized Calendars": "Synchronisierte Kalender",
  "Import events": "Ereignisse importieren",
  "Disconnect": "Trennen",
  "Choose calendar": "Kalender auswählen",
  "Monitor your Wix events through the sync feature": "Überwachen Sie Ihre Wix-Ereignisse über die Synchronisierungsfunktion",
  "Connect all your Boom calendars available on your website": "Verbinden Sie alle Ihre Auslegerkalender auf Ihrer Website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Planen, beteiligen und verwalten Sie Zoom-Meetings direkt über unseren Boom-Kalender.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Überwachen Sie Ihre Event Brite-Ereignisse mithilfe der Event Brite-Synchronisierungsfunktion",
  "Email": "Email",
  "Add-ons": "Add-Ons",
  "Receive notification emails as soon as users add events to your calendar.": "Erhalten Sie Benachrichtigungs-E-Mails, sobald Benutzer Ereignisse in Ihrem Kalender fügen.",
  "Enable + button on the calendar header": "Aktivieren Sie + Button auf dem Kalenderkopf",
  "Accept or decline events added by customers before making them public.": "Akzeptieren oder ablehnen Sie Ereignisse, die von den Kunden hinzugefügt wurden, bevor Sie sie öffentlich machen.",
  "Switch Add Event": "Ereignis wechseln",
  "Enable your browser cookies to connect to your account.": "Aktivieren Sie Ihre Browser-Cookies, um eine Verbindung zu Ihrem Konto herzustellen.",
  "Learn more": "Mehr erfahren",
  "Print Button": "Schaltfläche drucken",
  "Permit your users to print your Boom Event Calendar in any date range.": "Erlauben Sie Ihren Benutzern, Ihren Boom-Ereigniskalender in einem beliebigen Datumsbereich zu drucken.",
  "Show Title on mobile": "Titel auf dem Handy anzeigen",
  "Show Skeleton on mobile": "SKELETON auf Mobile anzeigen",
  "Start 7-day Business trial": "Starten Sie Ihren 7-tägigen Geschäftstest",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Genießen Sie alle unbegrenzten Funktionen, z. B. verkaufen Sie Tickets, Registrierung, Besuchereignis-Add-Ons.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Bitte beachten Sie: Am Ende der Probezeit werden Sie an Ihren vorhandenen Abonnementplan zurückgegeben.",
  "Not Now": "Nicht jetzt",
  "Start free trial": "Kostenlos testen",
  "Congrats!": "Herzlichen Glückwunsch!",
  "Your 7-day Business trial has been successfully activated.": "Ihr 7-Tage-Geschäftstest wurde erfolgreich aktiviert.",
  "Done": "Erledigt",
  "Title font color": "Titel-Schriftfarbe",
  "Desciption font color": "Beschreibung Schriftfarbe",
  "Section font color": "Sektion Schriftfarbe",
  "Card Header": "Kartenkopf",
  "Category": "Kategorie",
  "Display at the": "Anzeige auf der",
  "top": "oben",
  "bottom": "Unterseite",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Zeigen Sie den Kategoriefilter oben oder am unteren Rand des Kalenders an.Die Einstellungen gilt nur für Agenda- und Kartenansichten",
  "Processing your events": "Bearbeitung Ihrer Events",
  "Search for events": "Suche nach Events.",
  "There are no events added": "Es gibt keine Ereignisse hinzugefügt",
  "Location: To be determined": "Ort: ermittelt werden",
  "No events for selected date": "Keine Ereignisse für ausgewähltes Datum",
  "Uncategorized": "Nicht kategorisiert",
  "Edit event": "Ereignis bearbeiten",
  "Edit original event": "Originalereignis bearbeiten",
  "Copy event": "Ereignis kopieren",
  "Copy as new event": "Kopieren Sie als neue Veranstaltung",
  "Delete event": "Ereignis löschen",
  "Stop repeating on this date": "Hör auf, an diesem Datum zu wiederholen",
  "Exclude this date": "Diesen Datum ausschließen",
  "Fill your personal information": "Füllen Sie Ihre persönlichen Daten aus",
  "Check Box": "Kontrollkästchen",
  "Single Choice": "Einzelauswahl",
  "Option": "Möglichkeit",
  "Share Event": "Aktienereignis",
  "Oops! Something went wrong": "Hoppla!Etwas ist schief gelaufen",
  "We are sorry this event has already taken place": "Es tut uns leid, dass diese Veranstaltung bereits stattgefunden hat",
  "Back to calendar": "Zurück zum Kalender",
  "This field is required": "Dieses Feld ist erforderlich",
  "Phone": "Telefon",
  "Number field": "Zahlenfeld",
 "Please provide a valid email" : "Bitte geben Sie eine gültige E -Mail an",
 "Select at least one option" : "Wählen Sie mindestens eine Option aus",
 "Choose tickets to see total value" : "Wählen Sie Tickets, um den Gesamtwert zu sehen",
 "tickets" : "Tickets",
 "Choose Tickets" : "Wählen Sie Tickets",
 "Choose payment method" : "Zahlungsart auswählen",
 "Pay" : "Zahlen",
 "Total" : "Gesamt",
 "Free" : "Frei",
 "Buy tickets" : "Tickets kaufen",
 "Sold Out" : "Ausverkauft",
 "Tickets are available" : "Tickets sind erhältlich",
 "Sales End" : "Verkaufsende",
 "Availible from" : "Verfügbar ab",
 "Go to Orders" : "Gehen Sie zu Bestellungen",
 "Go to Details" : "Gehen Sie zu Details",
 "Group ticket" : "Gruppenkarte",
 "Name" : "Name",
 "Price" : "Preis",
 "Order by" : "Sortieren nach",
 "Order ID" : "Auftragsnummer",
 "Applied" : "Angewandt",
 "Fees" : "Honorare",
 "Enter promo code" : "Geben Sie den Promo -Code ein",
 "Apply" : "Sich bewerben",
 "Promo Code" : "Werbe-Code",
 "Cash" : "Kasse",
 "You can find your e-tickets attached to your email or download them" : "Sie finden Ihre E-Mail-E-Tickets, die an Ihre E-Mail angehängt sind oder sie herunterladen",
 "here" : "hier",
 "Time" : "Zeit",
 "Invalid promo code" : "Ungültiger Promo-Code",
 "Credit card" : "Kreditkarte",
 "You will soon receive a confirmation message of successful registration to your email address." : "Sie erhalten bald eine Bestätigungsnachricht zur erfolgreichen Registrierung an Ihre E -Mail -Adresse.",
 "You can also check your order details below." : "Sie können auch Ihre Bestelldaten unten überprüfen.",
 "at" : "bei",
 "Buy" : "Besorgen",
 "Donation" : "Spende",
 "Enter price" : "Unternehmen",
 "Choose" : "Wählen",
 "Chosen" : "Gewählt",
 "Choose your plan" : "Wählen Sie Ihren Plan",
  "week": "Woche",
  "wk": "Woche",
 "Choose plan cycle" : "Wählen Sie den Planzyklus",
 "months" : "Monate",
 "years" : "Jahre",
 "weeks" : "Wochen",
 "Copy Event Url" : "Ereignis -URL kopieren",
 "You can find your e-tickets attached to your email or print them" : "Sie können Ihre E-Tickets finden, die Ihrer E-Mail angeschlossen sind oder sie drucken",
 "Guest Info" : "Gastinfo",
 "Ticket Info" : "Ticketinformationen",
 "Ticket name" : "Ticketame",
 "Ticket price" : "Ticket Preis",
 "Ticket ID" : "Ticketnummer",
 "If you have any questions contact to organizer" : "Wenn Sie Fragen haben, wenden Sie sich an den Organisator",
 "As soon as event ends" : "Sobald Ereignis endet",
 "1 day after event ends" : "1 Tag nach Ende des Ereignisses",
 "7 days after event ends" : "7 Tage nach Ende des Ereignisses",
 "14 days after event ends" : "14 Tage nach Ende des Ereignisses",
 "30 days after event ends" : "30 Tage nach Ende des Ereignisses",
 "Menu" : "Speisekarte",
 "No event for selected date" : "Keine Veranstaltung für das ausgewählte Datum",
}
export default de