let el = {
  "Language": "Γλώσσα",
  "Show Time Zone": "Εμφάνιση ζώνης ώρας",
  "Custom Local Settings": "Προσαρμοσμένες τοπικές ρυθμίσεις",
  "Add and showcase events on your site using a beautiful calendar.": "Προσθήκη και εμφάνιση συμβάντων στον ιστότοπό σας χρησιμοποιώντας ένα όμορφο ημερολόγιο . ",
  "Week Days": "Εβδομάδες ημέρες",
  "Manage Events": "Διαχείριση εκδηλώσεων",
  "General": "Γενικός",
  "Layout Picker": "Επιλογή διαρρυθμίσεων",
  "Month": "Μήνας",
  "Monthly": "Μηνιαίος",
  "Week": "Εβδομάδα",
  "Weekly": "Εβδομαδιαίος",
  "Day": "Ημέρα",
  "Daily": "Καθημερινά",
  "Agenda": "Ημερήσια διάταξη",
  "Navigation Buttons": "Κουμπιά πλοήγησης",
  "Week numbers": "Αριθμοί εβδομάδας",
  "Include Weekends": "Συμπερίληψη Σαββατοκύριακου ",
  "All-day": "Ολη μέρα",
  "All Day": "Ολη μέρα",
  "Label": "Επιγραφή",
  "Fit to Height": "Προσαρμογή σε Ύψος",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Για να ρυθμίσετε τις αναλογίες εφαρμογών, απενεργοποιήστε χειροκίνητα αυτή την επιλογή και αλλάξτε το μέγεθος του Ημερολογίου στον επεξεργαστή.",
  "Default Layout": "Προεπιλεγμένη διάταξη",
  "Monthly view": "Μηνιαία προβολή",
  "Weekly and Daily view": "Εβδομαδιαία και ημερήσια προβολή",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Μπορείτε να δώσετε στους επισκέπτες μια πιο συνεπή εμπειρία δείχνοντας τον ίδιο αριθμό εβδομάδων ( 6) κάθε φορά.",
  "Fixed Weekly Layout": "Σταθερή εβδομαδιαία διάταξη",
  "back": " πίσω ",
  "Row": "Σειρά",
  "Hours in Weekly View": "Ώρες στην εβδομαδιαία προβολή",
  "Hours in Daily View": "Ώρες στην καθημερινή προβολή",
  "Start": "Αρχή",
  "End": "Τέλος",
  "At This Hour": "Σε αυτήν την ώρα",
  "Add to": "Προσθήκη στο",
  "Button": "Κουμπί",
  "Buttons": "Κουμπιά",
  "Sunday": "Κυριακή",
  "Monday": "Δευτέρα",
  "Tuesday": "Τρίτη",
  "Wednesday": "Τετάρτη",
  "Thursday": " Πέμπτη ",
  "Friday": "Παρασκευή",
  "Saturday": "Σάββατο",
  "Default Date": "Ημερομηνία προεπιλογής",
  "year": " έτος ",
  "month": " μήνας ",
  "days": " ημέρες ",
  "ago": " πριν ",
  "ahead": " μπροστά ",
  "Yesterday": "Εχθές",
  "Today": "Σήμερα",
  "Tomorrow": "Αύριο",
  "Custom": "Εθιμο",
  "Set Daily Rows Limit": "Ορισμός ημερήσιων ορίων γραμμών",
  "Set Proportions": "Ρύθμιση αναλογιών",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Επιτρέψτε στον επισκέπτη να προσθέσει συμβάν στο τοπικό Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Δοχείο",
  "Background": "Ιστορικό",
  "Container Background": "Ιστορικό κοντέινερ",
  "Container Borders": "Περιοχή δοχείων",
  "Calendar": "Ημερολόγιο",
  "Event Info Tooltip": "Πληροφορίες συμβάντος συμβάντων συμβάντων",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Όταν οι άνθρωποι αιωρούνται πάνω από ένα συμβάν, θα δουν όλες τις πληροφορίες σχετικά με αυτό σε μια επεξήγηση εργαλείου ",
  "Event Info Window": "Παράθυρο πληροφοριών συμβάντος",
  "This is the full information window that opens when someone clicks on the event.": "Αυτό είναι το πλήρες παράθυρο πληροφοριών που ανοίγει όταν κάποιος κάνει κλικ στο συμβάν. ",
  "Use Gradient": "Χρήση κλίσης",
  "Vertical": "Κατακόρυφος",
  "Horizontal": "Οριζόντιος",
  "First": "Πρώτα",
  "Second": "Δεύτερος",
  "diagonal": " διαγώνιος ",
  "Radial": "Ακτινικός",
  "Select option": "Επιλογή επιλογής",
  "Solid": "Στερεός",
  "Dotted": "Διάσπαρτος",
  "Dashed": "Διακεκομμένη",
  "Double": "Διπλό",
  "Border Radius": "Ακτίνα ορίου",
  "Padding": "Υλικό παραγεμίσματος",
  "Date Header": "Κεφαλίδα ημερομηνίας",
  "Event Default Color": "Χρώμα προεπιλογής συμβάντος",
  "Days of Week": "Ημέρες της εβδομάδας",
  "Days of Week Background": "Ημέρες της εβδομάδας",
  "Date": "Ημερομηνία",
  "Event Title": "Τίτλος εκδήλωσης",
  "Highlight today": "Επισημάνετε σήμερα",
  "Highlight Color": "Επισημάνετε χρώμα",
  "Hide": "Κρύβω",
  "Calendar Border Color": "Χρώμα περιθωρίου ημερολογίου",
  "Calendar Border Width": "Πλάτος περιθωρίου ημερολογίου",
  "Calendar Border Style": "Στυλ γραμμής πλαισίου",
  "Font Color": "Χρώμα γραμματοσειράς",
  "Event Background": "Ιστορικό συμβάντων",
  "Card Date Color": "Χρόνος ημερομηνίας κάρτας",
  "Title Font": "Γραμματοσειρά τίτλου",
  "Date Font": "Ημερομηνία γραμματοσειράς",
  "Description Font": "Γραμματοσειρά περιγραφής",
  "Button Background": "Κουμπί Background",
  "Button Text": "Κείμενο κουμπιού",
  "Border Color": "Χρώμα πλαισίου",
  "Border Width": "Πλάτος περιθωρίου",
  "Border Type": "Τύπος περιγράμματος",
  "Title": "Τίτλος",
  "Description": "Περιγραφή",
  "Background Color": "Χρώμα του φόντου",
  "Divider": "Διαιρών",
  "Event Details Font": "Λεπτομέρειες συμβάντος γραμματοσειράς",
  "Website Link Color": "Χρώμα συνδέσμου ιστότοπου",
  "Developer Info": "Πληροφορίες προγραμματιστή",
  "User Guide": "ΟΔΗΓΟΣ ΧΡΗΣΤΗ",
  "Support e-mail": "Υποστήριξη",
  "Our Website": "Η ιστοσελίδα μας",
  "App Review": "Ενημέρωση εφαρμογής",
  "Enjoying App? Leave us a review in the App Market.": "Απολαύστε την εφαρμογή; Αφήστε μας μια κριτική στην αγορά εφαρμογών. ",
  "Review Us": "Εξετάστε μας",
  "Connect With Us": "Σύνδεση με εμάς",
  "What's your email?": "Ποιο είναι το email σας; ",
  "Invalid email address!": "Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου! ",
  "Comments": "Σχόλια",
  "We'd love to hear from you. Send us a message.": "Θα θέλαμε να σας ακούσουμε. Στείλτε μας ένα μήνυμα. ",
  "Message must be at least 5 characters long": "Μήνυμα πρέπει να έχει μήκος τουλάχιστον 5 χαρακτήρων",
  "Send": "Στείλετε",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Αν θέλετε να επιτρέψετε στο χρήστη να αλλάξει τις προβολές ημερολογίου, ενεργοποιήστε αυτήν την επιλογή και επιλέξτε τις προβολές που θέλετε να εμφανίσετε.",
  "Main": "Κύριος",
  "Localize": "Εντοπίζω",
  "Settings": "Ρυθμίσεις",
  "Layouts": "Διατάξεις",
  "Advanced": "Προχωρημένος",
  "Design": "Σχέδιο",
  "Support": "Υποστήριξη",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Όλες οι τοπικές ρυθμίσεις βασίζονται (αυτόματα) στη γλώσσα σας. Εάν η γλώσσα σας βρίσκεται στη λίστα, δεν χρειάζεται να προσαρμόσετε αυτήν την ενότητα.",
  "Date Format": "Μορφή ημερομηνίας",
  "Time Format": "Μορφή ώρας",
  "Text Direction": "Κατεύθυνση κειμένου",
  "Left to Right": "Από αριστερά προς τα δεξιά",
  "Right to Left": "Δεξιά προς τα αριστερά",
  "Week Starts On": "Εβδομάδα ξεκινά",
  "Agenda Style": "Ατζέντα στυλ",
  "Classic": "Κλασσικός",
  "Modern": "Μοντέρνο",
  "Agenda Header": "Ημερολόγιο ημερήσιας διάταξης",
  "Upcoming Events": "Επερχόμενα γεγονότα",
  "Agenda Event Limit": "Όριο εκδήλωσης ατζέντας",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Αναβαθμίστε τώρα και αποκτήστε περισσότερα χαρακτηριστικά και απολαύστε το APP σας πλήρως!",
  "Upgrade Now": "Αναβάθμισε τώρα",
  "Hosting events that last all day? This lets you show them on your calendar.": "Φιλοξενία γεγονότων που διαρκούν όλη την ημέρα; Αυτό σας επιτρέπει να τα εμφανίσετε στο ημερολόγιό σας",
  "24 hours": "24 ώρες",
  "Sun": "Κυριακή",
  "Mon": "Δευτέρα",
  "Sat": "Σάββατο",
  "Default": "Προκαθορισμένο",
  "Select custom design style for your calendar.": "Επιλέξτε το προσαρμοσμένο στυλ σχεδιασμού για το ημερολόγιό σας.",
  "Style": "Στυλ",
  "Styles and Colors": "Στυλ και χρώματα",
  "Calendar Name": "Όνομα ημερολογίου",
  "Write your Calendar name here": "Γράψτε το όνομα του ημερολογίου σας εδώ",
  "Enable Search": "Ενεργοποίηση αναζήτησης",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Αυτό δεν είναι ορατό στους χρήστες σας. Ορίστε ονόματα για να διαφοροποιήσετε τα ημερολόγιά σας όταν χρησιμοποιείτε τη λειτουργία Συγχρονισμός ημερολογίου Boom.",
  "+ Add Event": "+ Προσθήκη εκδήλωσης",
  "Manage and Sync": "Διαχείριση και συγχρονισμός",
  "Show event details as...": "Εμφάνιση λεπτομερειών εκδήλωσης ως ...",
  "Tooltip": "Επεξήγηση εργαλείου",
  "Popup": "Πλαίσιο πληροφοριών",
  "None": "Κανένας",
  "Show Category": "Εμφάνιση κατηγορίας",
  "Header Align": "Ευθυγράμμιση κεφαλίδας",
  "Show Time": "Εμφάνιση ώρας",
  "Hours in Weekly/Daily View": "Ώρες σε εβδομαδιαία / καθημερινή προβολή",
  "Share Events": "Κοινοποίηση εκδηλώσεων",
  "Shadow": "Σκιά",
  "Inner Padding": "Εσωτερική επένδυση",
  "Text": "Κείμενο",
  "Active Button Border": "Περίγραμμα ενεργού κουμπιού",
  "Light Mode": "Λειτουργία φωτισμού",
  "Event Text Color": "Χρώμα κειμένου συμβάντος",
  "Dates": "Ημερομηνίες",
  "Skeleton": "Σκελετός",
  "Skeleton Color": "Χρώμα σκελετού",
  "Width": "Πλάτος",
  "Skeleton Style": "Στυλ σκελετού",
  "Color": "Χρώμα",
  "Section Titles": "Τίτλοι Ενότητας",
  "Section Content": "Περιεχόμενο Ενότητας",
  "Header": "Επί κεφαλής",
  "Map": "Χάρτης",
  "Standard": "Πρότυπο",
  "Retro": "Ρετρό",
  "Silver": "Ασήμι",
  "Night": "Νύχτα",
  "Dark": "Σκοτάδι",
  "Aubergine": "Μελιτζάνα",
  "Map Header": "Κεφαλίδα χάρτη",
  "Show Title in mobile": "Εμφάνιση τίτλου σε κινητό",
  "Card": "Κάρτα",
  "Card View": "Προβολή καρτών",
  "Card background color": "Χρώ��α φόντου κάρτας",
  "Title font": "Γραμματοσειρά τίτλου",
  "Desciption font": "Γραμματοσειρά περιγραφής",
  "Section font": "Ενότητα γραμματοσειράς",
  "Section divider color": "Χρώμα διαχωριστικού τμήματος",
  "Categories": "Κατηγορίες",
  "Share this event": "Μοιραστείτε αυτήν την εκδήλωση",
  "General Info": "Γενικές πληροφορίες",
  "Venue": "Τόπος συναντήσεως",
  "Organizer": "Διοργανωτής",
  "Search": "Αναζήτηση",
  "calendar": "Ημερολόγιο",
  "Copy event URL": "Αντιγραφή διεύθυνσης URL συμβάντος",
  "Copied!": "Αντιγράφηκε!",
  "Add & Share": "Προσθήκη & κοινή χρήση",
  "Calendar view": "Προβολή ημερολογίουم",
  "Add Event": "Προσθήκη εκδήλωσης",
  "Uncategorised": "Χωρίς κατηγορία",
  "More": "Περισσότερο",
  "Less": "Πιο λιγο",
  "Register": "Κανω ΕΓΓΡΑΦΗ",

  "Guests": "Επισκέπτες",
  "unlimited": "απεριόριστος",
  "Show more": "Δείτε περισσότερα",
  "Add event": "Προσθήκη εκδήλωσης",
  "All Day Event": "Ολοήμερο γεγονός",
  "Location": "Τοποθεσία",
  "Choose a category": "Επιλέξτε μια κατηγορία",
  "Venue name": "Όνομα χώρου",
  "Venue phone": "Venue phone",
  "Venue email": "Ηλεκτρονικό ταχυδρομείο Venue",
  "Venue website": "Ιστοσελίδα τόπου συναντήσεως",
  "Organizer name": "Όνομα οργανωτή",
  "Organizer phone": "Τηλέφωνο οργανωτή",
  "Organizer email": "Ηλεκτρονικό ταχυδρομείο οργανωτή",
  "Organizer website": "Ιστοσελίδα διοργανωτή",
  "Personal info": "Προσωπικές πληροφορίες",
  "First name": "Ονομα",
  "Last name": "Επίθετο",
  "Email Address": "Διεύθυνση ηλεκτρονικού ταχυδρομείου",
  "Additional Notes": "Επιπρόσθετες σημειώσεις",
  "Back": "Πίσω",
  "Save": "Σώσει",
  "Next": "Επόμενο",
  "Your event has been submitted": "Ηεκδήλωσή σας έχει υποβληθεί",
  "Event submittion has been failed": "Ηυποβολή εκδήλωσης απέτυχε",
  "e.g. Birthday Party": "π.χ. Πάρτι γενεθλίων",
  "First Name": "Ονομα",
  "Last Name": "Επίθετο",
  "Phone Number": "Τηλεφωνικό νούμερο",
  "Address": "Διεύθυνση",
  "Your comments": "Τα σχόλια σας",
  "How many guests?": "Πόσους επισκέπτες;",
  "Anything else we need to know?": "Οτιδήποτε άλλο πρέπει να γνωρίζουμε;",
  "Guests:": "Επισκέπτες:",
  "Submit": "υποβάλλουν",
  "Go to Calendar": "Μεταβείτε στο Ημερολόγιο",
  "Registration completed successfully!": "Η εγγραφή ολοκληρώθηκε με επιτυχία!",
  "Please check your registered email address": "Ελέγξτε την καταχωρισμένη διεύθυνση email σας",
  "Add to Calendar": "Προσθήκη στο Ημερολόγιο",
  "Share this Event": "Μοιραστείτε αυτό το συμβάν",
  "Sorry something went wrong": "Συγνώμη, κάτι πήγε στραβά",
  "Back to registration": "Επιστροφή στην εγγραφή",
  "Date & Location": "Ημερομηνία & τοποθεσία",
  "Date & Time": "Ημερομηνία ώρα",
  "home": "Zuhause",
  "Header align": "Ευθυγράμμιση κεφαλίδας",
  "Footer": "Fusszeile",
  "Categories Filter": "κατηγορίες Φίλτρο",
  "Show only upcoming": "Show nur in Kürze",
  "Card(s) in a row": "Karte (n) hintereinander",
  "Space between cards": "Abstand zwischen den Karten",
  "Shown events limit": "Limit für angezeigte Ereignisse",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Στυλ 4",
  "Buttons & Links": "Buttons & Links.",
  "Button corner radius": "Ακτίνα γωνίας κουμπιού",
  "Buttons font": "Γραμματοσειρά κουμπιών",
  "Buttons background": "Schaltflächen Hintergrund",
  "Get notified by Email": "Lassen Sie sich per E-Mail benachrichtigen",
  "Review events": "Ελέγξτε τις εκδηλώσεις",
  "Click on date": "Κάντε κλικ στην ημερομηνία",
  "Add Event button": "Προσθήκη κουμπιού συμβάντος",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Η συγχρονισμός του ημερολογίου σας επιτρέπει να ενσωματώσετε τα συμβάντα και τις συνεδρίες σας με το ημερολόγιο της έκρηξης.",
  "connect": "verbinden",
  "Synchronized Calendars": "Συγχρονισμένα ημερολόγια",
  "Import events": "Ereignisse importieren",
  "Disconnect": "Αποσυνδέω",
  "Choose calendar": "Kalender auswählen",
  "Monitor your Wix events through the sync feature": "Überwachen Sie Ihre Wix-Ereignisse über die Synchronisierungsfunktion",
  "Connect all your Boom calendars available on your website": "Verbinden Sie alle Ihre Auslegerkalender auf Ihrer Website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Προγραμματίστε, λάβετε μέρος και διαχειριστείτε τις συσκέψεις Zoom μέσω του Ημερολογίου Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Überwachen Sie Ihre Event Brite-Ereignisse mithilfe der Event Brite-Synchronisierungsfunktion",
  "Email": "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
  "Add-ons": "Πρόσθετα",
  "Receive notification emails as soon as users add events to your calendar.": "Λάβετε μηνύματα ειδοποίησης μόλις οι χρήστες προσθέτουν συμβάντα στο ημερολόγιό σας.",
  "Enable + button on the calendar header": "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.": "Να αποδεχθούν ή να απορρίπτονται τα γεγονότα που προστέθηκαν από τους πελάτες προτού τις δημοσιοποιηθούν.",
  "Switch Add Event": "Διακόπτης Προσθήκη συμβάντος",
  "Enable your browser cookies to connect to your account.": "Ενεργοποιήστε τα cookies του προγράμματος περιήγησης για να συνδεθείτε με το λογαριασμό σας.",
  "Learn more": "Learn more",
  "Print Button": "Κουμπί εκτύπωσης",
  "Permit your users to print your Boom Event Calendar in any date range.": "Επιτρέψτε στους χρήστες σας να εκτυπώσουν το ημερολόγιο εκδήλωσης Boom σε οποιοδήποτε εύρος ημερομηνιών.",
  "Show Title on mobile": "Εμφάνιση τίτλου στο κινητό",
  "Show Skeleton on mobile": "Εμφάνιση σκελετού στο κινητό",
  "Start 7-day Business trial": "Ξεκινήστε την επιχείρησή σας 7 ημερών",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Απολαύστε όλα τα απεριόριστα χαρακτηριστικά, όπως πωλούν εισιτήρια, εγγραφή, πρόσθετα συμβάντων επισκεπτών.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Σημείωση: Στο τέλος της δοκιμαστικής περιόδου, θα επιστραφεί στο υπάρχον πρόγραμμα συνδρομής σας.",
  "Not Now": "Οχι τώρα",
  "Start free trial": "Ξεκινήστε τη ΔΩΡΕΑΝ δοκιμή",
  "Congrats!": "Συγχαρητήρια!",
  "Your 7-day Business trial has been successfully activated.": "Η επιχειρηματική δοκιμή σας 7 ημερών έχει ενεργοποιηθεί με επιτυχία.",
  "Done": "Εγινε",
  "Title font color": "Χρώμα γραμματοσειράς τίτλου",
  "Desciption font color": "Περιγραφή Χρώμα γραμματοσειράς",
  "Section font color": "Χρώμα γραμματοσειράς ενότητας",
  "Card Header": "Κεφαλίδα καρτών",
  "Category": "Κατηγορία",
  "Display at the": "Εμφάνιση στο",
  "top": "μπλουζα",
  "bottom": "κάτω μέρος",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Παρουσιάστε το φίλτρο κατηγορίας στην κορυφή ή στο κάτω μέρος του ημερολογίου.Οι ρυθμίσεις ισχύουν μόνο για την ημερήσια διάταξη και τις προβολές καρτών",
  "Processing your events": "Επεξεργασία των γεγονότών σας",
  "Search for events": "Αναζήτηση για εκδηλώσεις",
  "There are no events added": "Δεν υπάρχουν συμβάντα",
  "Location: To be determined": "Τοποθεσία: Να προσδιοριστεί",
  "No events for selected date": "Δεν υπάρχουν συμβάντα για επιλεγμένη ημερομηνία",
  "Uncategorized": "Μη ταξινομημένος",
  "Edit event": "Επεξεργασία συμβάντος",
  "Edit original event": "Επεξεργασία πρωτότυπου γεγονότος",
  "Copy event": "Αντιγραφή",
  "Copy as new event": "Αντιγράψτε ως νέο συμβάν",
  "Delete event": "Διαγραφή συμβάντος",
  "Stop repeating on this date": "Σταματήστε να επαναλαμβάνετε την ημερομηνία αυτή",
  "Exclude this date": "Εξαιρέστε αυτήν την ημερομηνία",
  "Location is going to be announced": "Η τοποθεσία πρόκειται να ανακοινωθεί",
  "Fill your personal information": "Συμπληρώστε τα προσωπικά σας στοιχεία",
  "Check Box": "Πλαίσιο ελέγχου",
  "Single Choice": "Μεμονωμένη επιλογή",
  "Option": "Επιλογή",
  "Share Event": "Εκδήλωση κοινής χρήσης",
  "Oops! Something went wrong": "Ωχ!Κάτι πήγε στραβά",
  "We are sorry this event has already taken place": "Λυπούμαστε που έχει ήδη πραγματοποιηθεί αυτή η εκδήλωση",
  "Back to calendar": "Επιστροφή στο ημερολόγιο",
  "This field is required": "Αυτό το πεδίο απαιτείται",
  "Phone": "Τηλέφωνο",
  "Number field": "Πεδίο αριθμού",
  "Option": "Επιλογή",
  "Check Box": "Πλαίσιο ελέγχου",
  "Single Choice": "Μεμονωμένη επιλογή",
 "Please provide a valid email" : "Δώστε ένα έγκυρο email",
 "Select at least one option" : "Επιλέξτε τουλάχιστον μία επιλογή",
 "Choose tickets to see total value" : "Επιλέξτε εισιτήρια για να δείτε συνολική αξία",
 "tickets" : "εισιτήρια",
 "Choose Tickets" : "Επιλέξτε εισιτήρια",
 "Choose payment method" : "Διαλέξτε μέθοδο πληρωμής",
 "Pay" : "Πληρωμή",
 "Total" : "Σύνολο",
 "Free" : "Ελεύθερος",
 "Buy tickets" : "Αγορά εισιτηρίων",
 "Sold Out" : "Εξαντλημένα",
 "Tickets are available" : "Τα εισιτήρια είναι διαθέσιμα",
 "Sales End" : "Λήξη πωλήσεων",
 "Buy tickets" : "Αγορά εισιτηρίων"
}
export default el