let en = {
  "Language": "Language",
  "Show Time Zone": "Show Time Zone",
  "Custom Local Settings": "Custom Local Settings",
  "Add and showcase events on your site using a beautiful calendar.": "Add and showcase events on your site using a beautiful calendar.",
  "Week Days": "Week Days",
  "Manage Events": "Manage Events",
  "General": "General",
  "Layout Picker": "Layout Picker",
  "Month": "Month",
  "Monthly": "Monthly",
  "Week": "Week",
  "Weekly": "Weekly",
  "Day": "Day",
  "Daily": "Daily",
  "Agenda": "Agenda",
  "Navigation Buttons": "Navigation Buttons",
  "Week numbers": "Week numbers",
  "Include Weekends": "Include Weekends",
  "All-day": "All-day",
  "All Day": "All day",
  "Label": "Label",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "To set App proportions manually disable this option and resize Calendar in Editor.",
  "Default Layout": "Default Layout",
  "Monthly view": "Monthly view",
  "Weekly and Daily view": "Weekly and Daily view",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.",
  "Fixed Weekly Layout": "Fixed Weekly Layout",
  "back": "back",
  "Row": "Row",
  "Hours in Weekly View": "Hours in Weekly View",
  "Hours in Daily View": "Hours in Daily View",
  "Start": "Start",
  "End": "End",
  "At This Hour": "At This Hour",
  "Add to": "Add to",
  "Button": "Button",
  "Buttons": "Buttons",
  "Sunday": "Sunday",
  "Monday": "Monday",
  "Tuesday": "Tuesday",
  "Wednesday": "Wednesday",
  "Thursday": "Thursday",
  "Friday": "Friday",
  "Saturday": "Saturday",
  "Default Date": "Default Date",
  "year": "year",
  "month": "month",
  "days": "days",
  "ago": "ago",
  "ahead": "ahead",
  "Yesterday": "Yesterday",
  "Today": "Today",
  "Tomorrow": "Tomorrow",
  "Custom": "Custom",
  "Set Daily Rows Limit": "Set Daily Rows Limit",
  "Set Proportions": "Set Proportions",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Allow visitor to add event to local Calendars: Google, Yahoo, Outlook, ICalendar.",
  "Container": "Container",
  "Background": "Background",
  "Container Background": "Container Background",
  "Container Borders": "Container Borders",
  "Calendar": "Calendar",
  "Event Info Tooltip": "Event Info Tooltip/Popup",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "When people hover over an event they’ll see all the info about it in a tooltip.",
  "Event Info Window": "Event Info Window",
  "This is the full information window that opens when someone clicks on the event.": "This is the full information window that opens when someone clicks on the event.",
  "Use Gradient": "Use Gradient",
  "Vertical": "Vertical",
  "Horizontal": "Horizontal",
  "First": "First",
  "Second": "Second",
  "diagonal": "diagonal",
  "Radial": "Radial",
  "Select option": "Select option",
  "Solid": "Solid",
  "Dotted": "Dotted",
  "Dashed": "Dashed",
  "Double": "Double",
  "Border Radius": "Border Radius",
  "Padding": "Padding",
  "Date Header": "Date Header",
  "Event Default Color": "Event Default Color",
  "Days of Week": "Days of Week",
  "Days of Week Background": "Days of Week Background",
  "Date": "Date",
  "Event Title": "Event Title",
  "Highlight today": "Highlight today",
  "Highlight Color": "Highlight Color",
  "Hide": "Hide",
  "Calendar Border Color": "Calendar Border Color",
  "Calendar Border Width": "Calendar Border Width",
  "Calendar Border Style": "Calendar Border Style",
  "Section Titles": "Section Titles",
  "Section Content": "Section Content",
  "Event Background": "Event Background",
  "Card Date Color": "Card Date Color",
  "Title Font": "Title Font",
  "Date Font": "Date Font",
  "Description Font": "Description Font",
  "Button Background": "Button Background",
  "Button Text": "Button Text",
  "Border Color": "Border Color",
  "Border Width": "Border Width",
  "Border Type": "Border Type",
  "Title": "Title",
  "Description": "Description",
  "Background Color": "Background Color",
  "Divider": "Divider",
  "Event Details Font": "Event Details Font",
  "Website Link Color": "Link Color",
  "Developer Info": "Developer Info",
  "User Guide": "Guides & Chat",
  "Support e-mail": "Support e-mail",
  "Our Website": "Our Website",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.": "Enjoying App? Leave us a review in the App Market.",
  "Review Us": "Review Us",
  "Connect With Us": "Connect With Us",
  "What's your email?": "What's your email?",
  "Invalid email address!": "Invalid email address!",
  "Comments": "Comments",
  "We'd love to hear from you. Send us a message.": "We'd love to hear from you. Send us a message.",
  "Message must be at least 5 characters long": "Message must be at least 5 characters long",
  "Send": "Send",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.",
  "Main": "Main",
  "Localize": "Localize",
  "Settings": "Settings",
  "Layouts": "Layouts",
  "Advanced": "Advanced",
  "Design": "Design",
  "Support": "Support",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.",
  "Date Format": "Date Format",
  "Time Format": "Time Format",
  "Text Direction": "Text Direction",
  "Left to Right": "Left to Right",
  "Right to Left": "Right to Left",
  "Week Starts On": "Week Starts On",
  "Agenda Style": "Agenda Style",
  "Classic": "Classic",
  "Modern": "Modern",
  "Agenda Header": "Agenda Header",
  "Upcoming Events": "Upcoming Events",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Upgrade now and get a lot more features and enjoy your APP in full!",
  "Upgrade Now": "Upgrade Now",
  "Hosting events that last all day? This lets you show them on your calendar.": "Hosting events that last all day? This lets you show them on your calendar.",
  "24 hours": "24 hours",
  "Sun": "Sun",
  "Mon": "Mon",
  "Sat": "Sat",
  "Default": "Default",
  "Style": "Style",
  "Calendar Name": "Calendar Name",
  "Write your Calendar name here": "Write your Calendar name here",
  "Enable Search": "Enable Search",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.",
  "+ Add Event": "+ Add Event",
  "Manage and Sync": "Manage and Sync",
  "Show event details as...": "Show event details as...",
  "Tooltip": "Tooltip",
  "Popup": "Popup",
  "None": "None",
  "Show Category": "Show Category",
  "Header Align": "Header Align",
  "Show Time": "Show Time",
  "Hours in Weekly/Daily View": "Hours in Weekly/Daily View",
  "Share Events": "Share Events",
  "Shadow": "Shadow",
  "Inner Padding": "Inner Padding",
  "Text": "Text",
  "Active Button Border": "Active Button Border",
  "Light Mode": "Light Mode",
  "Event Text Color": "Event Text Color",
  "Dates": "Dates",
  "Skeleton": "Skeleton",
  "Skeleton Color": "Skeleton Color",
  "Width": "Width",
  "Skeleton Style": "Skeleton Style",
  "Color": "Color",
  "Header": "Header",
  "Map": "Map",
  "Standard": "Standard",
  "Retro": "Retro",
  "Silver": "Silver",
  "Night": "Night",
  "Dark": "Dark",
  "Aubergine": "Aubergine",
  "Map Header": "Map Header",
  "Show Title in mobile": "Show Title in mobile",
  "Card": "Card",
  "Card View": "Card View",
  "Card background color": "Card background color",
  "Title font": "Title font",
  "Desciption font": "Description font",
  "Section font": "Font section",
  "Section divider color": "Section divider color",
  "Font Color": "Font Color",
  "General Info": "General Info",
  "Venue": "Venue",
  "Organizer": "Organizer",
  "Search": "Search",
  "calendar": "calendar",
  "Share this event": "Share this event",
  "Copy event URL": "Copy event URL",
  "Copied!": "Copied!",
  "Add & Share": "Add & Share",
  "Calendar view": "Calendar view",
  "Add Event": "Add Event",
  "Uncategorised": "Uncategorised",
  "Categories": "Categories",
  "More": "More",
  "Less": "Less",
  "Register": "Register",
  "There are no events": "There are no events",
  "Guests": "Guests",
  "unlimited": "unlimited",
  "Show more": "Show more",
  "Add event": "Add event",
  "All Day Event": "All Day Event",
  "Location": "Location",
  "Choose a category": "Choose a category",
  "Venue name": "Venue name",
  "Venue phone": "Venue phone",
  "Venue email": "Venue email",
  "Venue website": "Venue website",
  "Organizer name": "Organizer name",
  "Organizer phone": "Organizer phone",
  "Organizer email": "Organizer email",
  "Organizer website": "Organizer website",
  "Personal info": "Personal info",
  "First name": "First name",
  "Last name": "Last name",
  "Email Address": "Email Address",
  "Additional Notes": "Additional Notes",
  "Back": "Back",
  "Save": "Save",
  "Next": "Next",
  "Your event has been submitted": "Your event has been submitted",
  "Event submittion has been failed": "Event submittion has been failed",
  "e.g. Birthday Party": "e.g. Birthday Party",
  "First Name": "First Name",
  "Last Name": "Last Name",
  "Phone Number": "Phone Number",
  "Address": "Address",
  "Your comments": "Your comments",
  "How many guests?": "How many guests?",
  "Anything else we need to know?": "Anything else we need to know?",
  "Guests:": "Guests:",
  "Submit": "Submit",
  "Go to Calendar": "Go to Calendar",
  "Registration completed successfully!": "Registration completed successfully!",
  "Please check your registered email address": "Please check your registered email address",
  "Add to Calendar": "Add to Calendar",
  "Share this Event": "Share this Event",
  "Sorry something went wrong": "Sorry something went wrong",
  "Back to registration": "Back to registration",
  "Date & Location": "Date & Location",
  "Date & Time": "Date & Time",
  "home":"home",
  "Header align":"Header align",
  "Footer":"Footer",
  "Categories Filter":"Categories Filter",
  "Show only upcoming":"Show only upcoming",
  "Card(s) in a row":"Card(s) in a row",
  "Space between cards":"Space between cards",
  "Shown events limit":"Shown events limit",
  "Style 1":"Style 1",
  "Style 2":"Style 2",
  "Style 3":"Style 3",
  "Style 4":"Style 4",
  "Buttons & Links":"Buttons & Links",
  "Button corner radius":"Button corner radius",
  "Buttons font":"Buttons font",
  "Buttons background":"Buttons background",
  "Get notified by Email":"Get notified by Email",
  "Review events":"Review events",
  "Click on date":"Click on date",
  "Add Event button":"Add Event button",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":"Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
  "connect":"connect",
  "Synchronized Calendars":"Synchronized Calendars",
  "Import events":"Import events",
  "Disconnect":"Disconnect",
  "Choose calendar":"Choose calendar",
  "Monitor your Wix events through the sync feature":"Monitor your Wix events through the sync feature",
  "Connect all your Boom calendars available on your website":"Connect all your Boom calendars available on your website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":"Schedule, join, and manage Zoom meetings right through our Boom Calendar.",
  "Monitor your Event Brite events through the Event Brite sync feature":"Monitor your Event Brite events through the Event Brite sync feature",
  "Email":"Email",
  "Add-ons":"Add-ons",
  "Switch Add Event":"Switch Add Event",
  "Enable your browser cookies to connect to your account.":"Enable your browser cookies to connect to your account.",
  "Learn more":"Learn more",
  "Print Button" : "Print Button",
  "Permit your users to print your Boom Event Calendar in any date range." : "Permit your users to print your Boom Event Calendar in any date range.",
  "Show Title on mobile": "Show Title on mobile",
  "Show Skeleton on mobile": "Show Skeleton on mobile",
  "Start 7-day Business trial": "Start 7-day Business trial",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Please note: At the end of the trial period, you will be returned to your existing subscription plan.",
  "Not Now": "Not Now",
  "Start free trial": "Free trial",
  "Congrats!": "Congrats!",
  "Your 7-day Business trial has been successfully activated.": "Your 7-day Business trial has been successfully activated.",
  "Done": "Done",
  "Title font color" : "Title font color",
  "Desciption font color" : "Description font color",
  "Section font color" : "Section font color",
  "Card Header" : "Card Header",
  "Category" : "Category",
  "Display at the" : "Display at the",
  "top" : "top",
  "bottom" : "bottom",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only" : "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only"
}
export default en;