let fi = {
 "Categories" : "Luokat",
 "Share this event" : "Jaa tämä tapahtuma",
 "Language" : "Kieli",
 "Show Time Zone" : "Näytä aikavyöhyke",
 "Custom Local Settings" : "Mukautetut paikalliset asetukset",
 "Add and showcase events on your site using a beautiful calendar." : "Lisää ja esittele tapahtumia sivustollesi kauniilla kalenterilla.",
 "Week Days" : "Viikkopäivät",
 "Manage Events" : "Hallitse tapahtumia",
 "General" : "Yleinen",
 "Layout Picker" : "Poiminta",
 "Month" : "Kuukausi",
 "Monthly" : "Kuukausittain",
 "Week" : "Viikko",
 "Weekly" : "Viikoittain",
 "Day" : "Päivä",
 "Daily" : "Päivittäin",
 "Agenda" : "Esityslista",
 "Navigation Buttons" : "Navigointipainikkeet",
 "Week numbers" : "Viikonumerot",
 "Include Weekends" : "Sisällytä viikonloppuja",
 "All-day" : "Koko päivä",
 "All Day" : "Koko päivä",
 "Label" : "Merkitä",
 "Fit to Height" : "Sopia korkeuteen",
 "To set App proportions manully disable this option and resize Calendar in Editor." : "Aseta sovellusosuudet poistamaan tämän vaihtoehdon manuaalisesti käytöstä ja muuttamaan kalenterin kokoa editorissa.",
 "Default Layout" : "Laiminlyönti",
 "Monthly view" : "Kuukausittainen näkymä",
 "Weekly and Daily view" : "Viikko- ja päivittäinen näkymä",
 "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time." : "Voit antaa kävijöille johdonmukaisemman kokemuksen näyttämällä saman määrän viikkoja (6) kerrallaan.",
 "Fixed Weekly Layout" : "Kiinteä viikoittainen asettelu",
 "back" : "takaisin",
 "Row" : "Rivi",
 "Hours in Weekly View" : "Tunnit viikoittain",
 "Hours in Daily View" : "Tunteja päivittäisessä näkymässä",
 "Start" : "alkaa",
 "End" : "Loppu",
 "At This Hour" : "Tähän aikaan",
 "Button" : "Painike",
 "Buttons" : "Painikkeet",
 "Sunday" : "sunnuntai",
 "Monday" : "maanantai",
 "Tuesday" : "tiistai",
 "Wednesday" : "keskiviikko",
 "Thursday" : "torstai",
 "Friday" : "perjantai",
 "Saturday" : "Lauantai",
 "Default Date" : "Oletuspäivämäärä",
 "year" : "vuosi",
 "month" : "kuukausi",
 "mo" : "MO",
 "days" : "päivä",
 "ago" : "sitten",
 "ahead" : "eteenpäin",
 "Yesterday" : "Eilen",
 "Today" : "Tänään",
 "Tomorrow" : "Huomenna",
 "Custom" : "Mukautettu",
 "Set Daily Rows Limit" : "Aseta päivittäiset rivit",
 "Set Proportions" : "Aseta mittasuhteet",
 "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar." : "Anna vierailijan lisätä tapahtumaa paikallisiin calnedarsiin: Google, Yahoo, Outlook, Icalendar.",
 "Container" : "Astia",
 "Background" : "Tausta",
 "Container Background" : "Konttitausta",
 "Container Borders" : "Konttien rajat",
 "Calendar" : "Kalenteri",
 "Event Info Tooltip" : "Tapahtumatiedot työkaluvihje",
 "When people hover over an event they’ll see all the info about it in a tooltip." : "Kun ihmiset leijuvat tapahtuman yli, he näkevät kaikki tiedot siitä työkaluvinkkiin.",
 "Event Info Window" : "Tapahtumatietoikkuna",
 "This is the full information window that opens when someone clicks on the event." : "Tämä on koko tietoikkuna, joka avautuu, kun joku napsauttaa tapahtumaa.",
 "Use Gradient" : "Käyttää kaltevuutta",
 "Vertical" : "Pystysuora",
 "Horizontal" : "Vaakasuora",
 "First" : "Ensimmäinen",
 "Second" : "Toinen",
 "diagonal" : "diagonaali",
 "Radial" : "Säteilevä",
 "Select option" : "Valitse vaihtoehto",
 "Solid" : "Kiinteä",
 "Dotted" : "Katkoviiva",
 "Dashed" : "Katkoviiva",
 "Double" : "Kaksinkertainen",
 "Border Radius" : "Reunusäde",
 "Padding" : "Pehmuste",
 "Date Header" : "Päiväysotsikko",
 "Event Default Color" : "Tapahtuman oletusväri",
 "Days of Week" : "Viikonpäivät",
 "Days of Week Background" : "Viikonpäivien tausta",
 "Date" : "Päivämäärä",
 "Event Title" : "Tapahtuman otsikko",
 "Highlight today" : "Korostaa tänään",
 "Highlight Color" : "Korostaa väriä",
 "Hide" : "Piilottaa",
 "Calendar Border Color" : "Kalenterin reunaväri",
 "Calendar Border Width" : "Kalenterin reunan leveys",
 "Calendar Border Style" : "Kalenterin rajatyyli",
 "Font Color" : "Fontin väri",
 "Event Background" : "Tapahtuman tausta",
 "Card Date Color" : "Kortin päivämäärä",
 "Title Font" : "Otsikkofontti",
 "Date Font" : "Päivämäärän fontti",
 "Description Font" : "Kuvaus kirjasin",
 "Button Background" : "Napin tausta",
 "Button Text" : "Nappiteksti",
 "Border Color" : "Reunuksen väri",
 "Border Width" : "Rajan leveys",
 "Border Type" : "Reunatyyppi",
 "Title" : "Otsikko",
 "Description" : "Kuvaus",
 "Background Color" : "Taustaväri",
 "Divider" : "Jakaja",
 "Event Details Font" : "Tapahtumatiedot fontti",
 "Website Link Color" : "Verkkosivuston väri",
 "Developer Info" : "Kehittäjätiedot",
 "User Guide" : "Käyttöohjeet",
 "Support e-mail" : "Tukea sähköpostiviestiä",
 "Our Website" : "Meidän nettisivumme",
 "App Review" : "APP -arvostelu",
 "Enjoying App? Leave us a review in the App Market." : "Nautitko sovelluksesta?Jätä meille arvostelu sovellusmarkkinoille.",
 "Review Us" : "Tarkista meidät",
 "Connect With Us" : "Yhdistä meihin",
 "What's your email?" : "Mikä on sähköpostisi?",
 "Invalid email address!" : "Virheellinen sähköpostiosoite!",
 "Comments" : "Kommentit",
 "We'd love to hear from you. Send us a message." : "Haluaisimme kuulla sinusta.Lähetä meille viesti.",
 "Message must be at least 5 characters long" : "Viestin on oltava vähintään 5 merkkiä pitkä",
 "Send" : "Lähettää",
 "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show." : "Jos haluat antaa käyttäjän vaihtaa kalenterinäkymät, ota tämä vaihtoehto käyttöön ja valitse näkymät, jotka haluat näyttää.",
 "Main" : "Pää-",
 "Localize" : "Paikallistaa",
 "Settings" : "asetukset",
 "Layouts" : "Asettelu",
 "Advanced" : "Pitkälle kehittynyt",
 "Design" : "Design",
 "Support" : "Tuki",
 "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section." : "Kaikki paikalliset asetukset ovat (automaattisesti) kielen perusteella.Jos kielesi on luettelossa, tätä osaa ei tarvitse mukauttaa.",
 "Date Format" : "Päivämäärämuoto",
 "Time Format" : "Aikamuoto",
 "Text Direction" : "Tekstin suunta",
 "Left to Right" : "Vasemmalta oikealle",
 "Right to Left" : "Oikealta vasemmalle",
 "Week Starts On" : "Viikko alkaa",
 "Agenda Style" : "Esityslistan tyyli",
 "Classic" : "Klassikko",
 "Modern" : "Moderni",
 "Agenda Header" : "Esityslistan otsikko",
 "Upcoming Events" : "Tulevat tapahtumat",
 "Agenda Event Limit" : "Esityslistan tapahtumaraja",
 "Upgrade now and get a lot more features and enjoy your APP in full!" : "Päivitä nyt ja hanki paljon enemmän ominaisuuksia ja nauti sovelluksestasi kokonaan!",
 "Upgrade Now" : "Päivitä nyt",
 "Hosting events that last all day? This lets you show them on your calendar." : "Isännöintitapahtumat, jotka kestävät koko päivän?Tämän avulla voit näyttää ne kalenterissasi.",
 "24 hours" : "24 tuntia",
 "Sun" : "Aurinko",
 "Mon" : "Maanantai",
 "Sat" : "Istua",
 "Default" : "Laiminlyönti",
 "Select custom design style for your calendar." : "Valitse kalenterisi mukautettu suunnittelutyyli.",
 "Style" : "Tyyli",
 "Styles and Colors" : "Tyylit ja värit",
 "Calendar Name" : "Kalenterin nimi",
 "Write your Calendar name here" : "Kirjoita kalenterimesi tähän",
 "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function." : "Tämä ei ole käyttäjille näkyvä.Aseta nimet kalenterisi erottamiseksi, kun käytetään puomikalenterin synkronointitoimintoa.",
 "General Info" : "Yleiset tiedot",
 "Venue" : "Paikka",
 "Organizer" : "Järjestäjä",
 "Search" : "Hae",
 "Add to" : "Lisätä",
 "calendar" : "kalenteri",
 "Copy event URL" : "Kopioi tapahtuman URL -osoite",
 "Copied!" : "Kopioi!",
 "Add & Share" : "Lisää ja jaa",
 "Map" : "Kartta",
 "Calendar view" : "Kalenterinäkymä",
 "Add Event" : "Lisätä tapahtumaa",
 "Uncategorised" : "Luokittelematon",
 "More" : "Lisää",
 "Less" : "Vähemmän",
 "Register" : "Rekisteröidä",
 "Card" : "Kortti",
 "Guests" : "Vieraat",
 "unlimited" : "rajoittamaton",
 "Show more" : "Näytä lisää",
 "Enable Search" : "Ota haku käyttöön",
 "+ Add Event" : "+ Lisää tapahtuma",
 "Manage and Sync" : "Hallita ja synkronoida",
 "Show event details as..." : "Näytä tapahtuman yksityiskohdat ...",
 "Tooltip" : "Työkalu",
 "Popup" : "Ponnahdusikkuna",
 "None" : "Ei mitään",
 "Show Category" : "Näyttelykategoria",
 "Header Align" : "Otsikko kohdistaa",
 "Show Time" : "Esitysaika",
 "Hours in Weekly/Daily View" : "Tunnit viikoittain/päivittäisessä näkymässä",
 "Share Events" : "Jaa tapahtumat",
 "Shadow" : "Varjo",
 "Inner Padding" : "Sisäselvitys",
 "Text" : "Teksti",
 "Active Button Border" : "Aktiivinen painike reuna",
 "Light Mode" : "Valotila",
 "Event Text Color" : "Tapahtumatekstiväri",
 "Dates" : "Päivämäärät",
 "Skeleton" : "Luuranko",
 "Skeleton Color" : "Luurankoväri",
 "Width" : "Leveys",
 "Skeleton Style" : "Luurankotyyli",
 "Color" : "Väri",
 "Section Titles" : "Osastonimikkeet",
 "Section Content" : "Osiosisältö",
 "Header" : "Otsikko",
 "Standard" : "Standardi",
 "Retro" : "Retro",
 "Silver" : "Hopea",
 "Night" : "Yö",
 "Dark" : "Tumma",
 "Aubergine" : "Munakoiso",
 "Map Header" : "Karttaotsikko",
 "Show Title in mobile" : "Näytä otsikko matkapuhelimessa",
 "Card View" : "Kortinkuva",
 "Card background color" : "Kortin taustaväri",
 "Title font" : "Otsikkofontti",
 "Desciption font" : "Desciption font",
 "Section font" : "Osiofontti",
 "Section divider color" : "Osanjakajan väri",
 "Add event" : "Lisätä tapahtumaa",
 "All Day Event" : "Koko päivän tapahtuma",
 "Location" : "Sijainti",
 "Choose a category" : "Valitse kategoria",
 "Venue name" : "Tapahtumapaikan nimi",
 "Venue phone" : "Tapahtumapaikan puhelin",
 "Venue email" : "Tapahtumapaikan sähköposti",
 "Venue website" : "Tapahtumapaikan verkkosivusto",
 "Organizer name" : "Järjestäjän nimi",
 "Organizer phone" : "Järjestäjäpuhelin",
 "Organizer email" : "Järjestäjän sähköposti",
 "Organizer website" : "Järjestäjän verkkosivusto",
 "Personal info" : "Henkilökohtaiset tiedot",
 "First name" : "Etunimi",
 "Last name" : "Sukunimi",
 "Email Address" : "Sähköpostiosoite",
 "Additional Notes" : "Lisämerkinnät",
 "Back" : "Takaisin",
 "Save" : "Tallentaa",
 "Next" : "Seuraava",
 "Your event has been submitted" : "Tapahtumasi on lähetetty",
 "Event submittion has been failed" : "Tapahtuman lähettäminen on epäonnistunut",
 "e.g. Birthday Party" : "esim.Syntymäpäiväjuhlat",
 "First Name" : "Etunimi",
 "Last Name" : "Sukunimi",
 "Phone Number" : "Puhelinnumero",
 "Address" : "Osoite",
 "Your comments" : "Kommenttisi",
 "How many guests?" : "Kuinka monta vierasta?",
 "Anything else we need to know?" : "Mitä muuta meidän on tiedettävä?",
 "Guests:" : "Vieraat:",
 "Submit" : "Lähetä",
 "Go to Calendar" : "Mennä kalenteriin",
 "Registration completed successfully!" : "Rekisteröinti valmistui onnistuneesti!",
 "Please check your registered email address" : "Tarkista rekisteröity sähköpostiosoite",
 "Add to Calendar" : "Lisää kalenteriin",
 "Share this Event" : "Jaa tämä tapahtuma",
 "Sorry something went wrong" : "Pahoittelut, jotain meni pieleen",
 "Back to registration" : "Takaisin rekisteröintiin",
 "Date & Location" : "Päivämäärä ja sijainti",
 "Date & Time" : "Treffiaika",
 "home" : "Koti",
 "Header align" : "Otsikko kohdistaa",
 "Footer" : "Alatunniste",
 "Categories Filter" : "Kategoriat suodatin",
 "Show only upcoming" : "Näytä vain tuleva",
 "Card(s) in a row" : "Kortti (t) peräkkäin",
 "Space between cards" : "Tilaa korttien välillä",
 "Shown events limit" : "Näytetyt tapahtumat rajoittavat",
 "Style 1" : "Tyyli 1",
 "Style 2" : "Tyyli 2",
 "Style 3" : "Tyyli 3",
 "Style 4" : "Tyyli 4",
 "Buttons & Links" : "Napit ja linkit",
 "Button corner radius" : "Nappikulman säde",
 "Buttons font" : "Painikkeet fontti",
 "Buttons background" : "Napit",
 "Get notified by Email" : "Saada ilmoitusta sähköpostitse",
 "Review events" : "Tarkastele tapahtumia",
 "Click on date" : "Napsauta päivämäärää",
 "Add Event button" : "Lisää tapahtumapainike",
 "Calendar sync allows you to integrate your events and sessions with your Boom Calendar." : "Kalenterisynkronointi antaa sinun integroida tapahtumat ja istunnot puomikalenteriin.",
 "connect" : "kytkeä",
 "Synchronized Calendars" : "Synkronoidut kalenterit",
 "Import events" : "Tuontitapahtumat",
 "Disconnect" : "Katkaista",
 "Choose calendar" : "Valitse kalenteri",
 "Monitor your Wix events through the sync feature" : "Seuraa WIX -tapahtumiasi synkronointiominaisuuden kautta",
 "Connect all your Boom calendars available on your website" : "Yhdistä kaikki verkkosivustollasi käytettävissä olevat puomikalenterit",
 "Schedule, join, and manage Zoom meetings right through our Boom Calendar." : "Aikataulu, liity ja hallitse zoom -kokouksia suoraan puomikalenterimme kautta.",
 "Monitor your Event Brite events through the Event Brite sync feature" : "Seuraa Eventbrite -tapahtumiasi Eventbrite Sync -ominaisuuden kautta",
 "Email" : "Sähköposti",
 "Add-ons" : "Lisäosat",
 "Receive notification emails as soon as users add events to your calendar." : "Vastaanota ilmoitussähköposteja heti, kun käyttäjät lisäävät tapahtumia kalenteriin.",
 "Enable + button on the calendar header" : "Ota käyttöön + -painike kalenterin otsikossa",
 "Accept or decline events added by customers before making them public." : "Hyväksy tai hylkää asiakkaiden lisäämisen ennen niiden julkistamista.",
 "Switch Add Event" : "Kytkin Lisää tapahtuma",
 "Enable your browser cookies to connect to your account." : "Ota selain -evästeesi yhteyden muodostamiseen tilillesi.",
 "Learn more" : "Oppia lisää",
 "Print Button" : "Tulostuspainike",
 "Permit your users to print your Boom Event Calendar in any date range." : "Anna käyttäjien tulostaa Boom -tapahtumakalenterisi millä tahansa ajanjaksolla.",
 "Show Title on mobile" : "Näytä otsikko matkapuhelimella",
 "Show Skeleton on mobile" : "Näytä luuranko matkapuhelimella",
 "Start 7-day Business trial" : "Aloita 7 päivän yrityskoe",
 "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons." : "Nauti kaikista rajoittamattomista ominaisuuksista, kuten myydä lippuja, rekisteröintiä, vierailutapahtumien lisäosia.",
 "Please note: At the end of the trial period, you will be returned to your existing subscription plan." : "Huomaa: Koeajan lopussa sinut palautetaan nykyiseen tilaussuunnitelmaan.",
 "Not Now" : "Ei nyt",
 "Start free trial" : "Aloita ilmainen kokeilu",
 "Congrats!" : "Onnittelut!",
 "Your 7-day Business trial has been successfully activated." : "Seitsemän päivän yrityskoe on aktivoitu onnistuneesti.",
 "Done" : "Tehty",
 "Title font color" : "Otsikkofonttiväri",
 "Desciption font color" : "Desciption font -väri",
 "Section font color" : "Osiofonttiväri",
 "Card Header" : "Kortin otsikko",
 "Category" : "Kategoria",
 "Display at the" : "Näytä",
 "top" : "ylhäältä",
 "bottom" : "pohja",
 "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only" : "Esittele luokkasuodatin kalenterin yläosassa tai alareunassa.Asetukset koskevat vain esityslistan ja kortinäkymiä",
 "Processing your events" : "Tapahtumien käsittely",
 "Search for events" : "Etsi tapahtumia",
 "There are no events added" : "Tapahtumia ei ole lisätty",
 "Location: To be determined" : "Sijainti: määritettävä",
 "No events for selected date" : "Ei tapahtumia valitulle päivälle",
 "Uncategorized" : "Luokittelematon",
 "Edit event" : "Muokkaustapahtuma",
 "Edit original event" : "Muokkaa alkuperäinen tapahtuma",
 "Copy event" : "Kopiotapahtuma",
 "Copy as new event" : "Kopioi uusi tapahtuma",
 "Delete event" : "Poistaa tapahtuma",
 "Stop repeating on this date" : "Lopeta toistaminen tänä päivänä",
 "Exclude this date" : "Sulje pois tämä päivämäärä",
 "Location is going to be announced" : "Sijainti ilmoitetaan",
 "Fill your personal information" : "Täytä henkilökohtaiset tietosi",
 "Check Box" : "Valintaruutu",
 "Single Choice" : "Yksi valinta",
 "Option" : "Vaihtoehto",
 "Share Event" : "Jaa tapahtuma",
 "Oops! Something went wrong" : "Oho!Jotain meni pieleen",
 "We are sorry this event has already taken place" : "Olemme pahoillamme, että tämä tapahtuma on jo tapahtunut",
 "Back to calendar" : "Takaisin kalenteriin",
 "This field is required" : "Tämä kenttä pitää täyttää",
 "Phone" : "Puhelin",
 "Number field" : "Lukukenttä",
 "Option" : "Vaihtoehto",
 "Check Box" : "Valintaruutu",
 "Single Choice" : "Yksi valinta",
 "Please provide a valid email" : "Anna kelvollinen sähköposti",
 "Select at least one option" : "Valitse vähintään yksi vaihtoehto",
 "Choose tickets to see total value" : "Valitse liput nähdäksesi kokonaisarvon",
 "tickets" : "liput",
 "Choose Tickets" : "Valitse liput",
 "Choose payment method" : "Valitse maksutapa",
 "Pay" : "Maksaa",
 "Total" : "Kaikki yhteensä",
 "Free" : "Vapaa",
 "Buy tickets" : "Osta lippuja",
 "Sold Out" : "Loppuunmyyty",
 "Tickets are available" : "Liput ovat saatavilla",
 "Sales End" : "Myyntipää",
 "Buy tickets" : "Osta lippuja",
 "Availible from" : "saatavilla",
 "Go to Orders" : "Mennä käskyihin",
 "Go to Details" : "Siirry yksityiskohtiin",
 "Group ticket" : "Ryhmälippu",
 "Name" : "Nimi",
 "Price" : "Hinta",
 "Order by" : "Tilata",
 "Order ID" : "tilausnumero",
 "Group ticket" : "Ryhmälippu",
 "Name" : "Nimi",
 "Price" : "Hinta",
 "Order by" : "Tilata",
 "Order ID" : "tilausnumero",
 "Applied" : "Sovellettu",
 "Fees" : "Palkkiot",
 "Enter promo code" : "Kirjoita tarjouskoodi",
 "Apply" : "Käytä",
 "Promo Code" : "Tarjouskoodi",
 "Cash" : "Käteinen raha",
 "You can find your e-tickets attached to your email or download them" : "Löydät sähköpostiisi liitetyt sähköiset lippuja tai lataa ne",
 "here" : "tässä",
 "Time" : "Aika",
 "Invalid promo code" : "Virheellinen tarjouskoodi",
 "Credit card" : "Luottokortti",
 "You will soon receive a confirmation message of successful registration to your email address." : "Saat pian vahvistusviestin onnistuneesta rekisteröinnistä sähköpostiosoitteeseesi.",
 "You can also check your order details below." : "Voit myös tarkistaa tilauksen yksityiskohdat alla.",
 "at" : "at",
 "Buy" : "Ostaa",
 "Donation" : "Lahjoitus",
 "Enter price" : "Antaa hintaan",
 "Choose" : "Valita",
 "Chosen" : "Valittu",
 "Choose your plan" : "Valitse suunnitelmasi",
 "week" : "viikko",
 "wk" : "viitat",
 "Choose plan cycle" : "Valitse suunnitelma sykli",
 "months" : "kuukaudet",
 "years" : "vuotta",
 "weeks" : "viikot",
 "Copy Event Url" : "Kopioi tapahtuman URL -osoite",
 "You can find your e-tickets attached to your email or print them" : "Löydät sähköpostiisi liitetyt sähköiset lippuja tai tulosta ne",
 "Guest Info" : "Vierastiedot",
 "Ticket Info" : "Lipputiedot",
 "Ticket name" : "Lipun nimi",
 "Ticket price" : "Lipun hinta",
 "Ticket ID" : "Lipputunnus",
 "If you have any questions contact to organizer" : "Jos sinulla on kysyttävää järjestäjälle",
 "If you have any questions contact to organizer" : "Jos sinulla on kysyttävää järjestäjälle",
 "As soon as event ends" : "Heti kun tapahtuma päättyy",
 "1 day after event ends" : "1 päivä tapahtuman päättymisen jälkeen",
 "7 days after event ends" : "7 päivää tapahtuman päättymisen jälkeen",
 "14 days after event ends" : "14 päivää tapahtuman päättymisen jälkeen",
 "30 days after event ends" : "30 päivää tapahtuman päättymisen jälkeen",
 "Menu" : "Valikko",
 "No event for selected date" : "Ei tapahtumaa valitulle päivälle"
}
export default fi