let he = {
  "Categories": "קטגוריות",
  "Share this event": "שתפו אירוע זה",
  "Language": "שפה",
  "Show Time Zone": "הצג אזור זמן",
  "Custom Local Settings": "הגדרות מקומיות בהתאמה אישית",
  "Add and showcase events on your site using a beautiful calendar.": "הוסף והציג אירועים באתר שלך באמצעות לוח שנה יפה . ",
  "Week Days": "ימי חול",
  "Manage Events": "נהל אירועים",
  "General": "כללי",
  "Layout Picker": "בורר פריסה",
  "Month": "חודש",
  "Monthly": "חודשי",
  "Week": "שבוע",
  "Weekly": "שבועי",
  "Day": "יום",
  "Daily": "יומי",
  "Agenda": "סדר יום",
  "Navigation Buttons": "כפתורי ניווט",
  "Week numbers": "מספרי שבוע",
  "Include Weekends": "כלול סופי שבוע",
  "All-day": "כל היום",
  "All Day": "כל היום",
  "Label": "תווית",
  "Fit to Height": "מתאים לגובה",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "כדי להגדיר פרופורציות של אפליקציות בטל באופן ידני אפשרות זו ולשנות את גודל לוח השנה בעורך. ",
  "Default Layout": "מערך ברירת מחדל",
  "Monthly view": "תצוגה חודשית",
  "Weekly and Daily view": "תצוגה שבועית ויומית",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "אתה יכול להעניק למבקרים חוויה עקבית יותר על ידי הצגת מספר זהה של שבועות ( 6) בכל פעם.",
  "Fixed Weekly Layout": "מתווה שבועי קבוע",
  "back": " בחזרה ",
  "Row": "שורה",
  "Hours in Weekly View": "שעות בתצוגה שבועית",
  "Hours in Daily View": "שעות בתצוגה יומית",
  "Start": "הַתחָלָה",
  "End": "סוֹף",
  "At This Hour": "בשעה זו",
  "Button": "כפתור",
  "Buttons": "כפתורים",
  "Sunday": "יום ראשון",
  "Monday": "יום שני",
  "Tuesday": "יום שלישי",
  "Wednesday": "יום רביעי",
  "Thursday": "יום חמישי",
  "Friday": "יום שישי",
  "Saturday": "יום שבת",
  "Default Date": "תאריך ברירת מחדל",
  "year": " שנה ",
  "month": " חודש ",
  "days": " ימים ",
  "ago": " לפני ",
  "ahead": " קדימה ",
  "Yesterday": "אתמול",
  "Today": "היום",
  "Tomorrow": "מחר",
  "Custom": "המותאם אישית",
  "Set Daily Rows Limit": "הגדר מגבלת שורות יומיות",
  "Set Proportions": "קבע פרופורציות",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "אפשר המבקר להוסיף האירוע המקומי Calnedars , Google, Yahoo, Outlook, iCalendar . ",
  "Container": "מיכל",
  "Background": "רקע כללי",
  "Container Background": "רקע מיכל",
  "Container Borders": "גבולות מיכל",
  "Calendar": "לוח שנה",
  "Event Info Tooltip": "הסבר הכלים למידע על אירועים",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "כשאנשים מרחפים מעל אירוע הם יראו את כל המידע על זה בסמל הכלים. ",
  "Event Info Window": "חלון פרטי אירוע",
  "This is the full information window that opens when someone clicks on the event.": "זהו חלון המידע המלא שנפתח כשמישהו לוחץ על האירוע. ",
  "Use Gradient": "השתמש בשיפוע",
  "Vertical": "אנכי",
  "Horizontal": "אופקי",
  "First": "ראשון",
  "Second": "שני",
  "diagonal": " אלכסון ",
  "Radial": "רדיאלי",
  "Select option": "בחר אפשרות",
  "Solid": "מוצק",
  "Dotted": "מנוקד",
  "Dashed": "מקווקו",
  "Double": "כפול",
  "Border Radius": "רדיוס הגבול",
  "Padding": "ריפוד",
  "Date Header": "כותרת תאריך",
  "Event Default Color": "צבע ברירת מחדל לאירוע",
  "Days of Week": "ימי השבוע",
  "Days of Week Background": "רקע ימי השבוע",
  "Date": "תַאֲרִיך",
  "Event Title": "כותרת האירוע",
  "Highlight today": "הדגש היום",
  "Highlight Color": "הדגש צבע",
  "Hide": "להתחבא",
  "Calendar Border Color": "צבע גבול לוח שנה",
  "Calendar Border Width": "רוחב גבול לוח השנה",
  "Calendar Border Style": "סגנון גבול לוח שנה",
  "Font Color": "צבע גופן",
  "Event Background": "רקע אירוע",
  "Card Date Color": "צבע תאריך כרטיס",
  "Title Font": "גופן כותרת",
  "Date Font": "גופן תאריך",
  "Description Font": "גופן תיאור",
  "Button Background": "רקע כפתור",
  "Button Text": "טקסט כפתור",
  "Border Color": "צבע גבול",
  "Border Width": "רוחב גבול",
  "Border Type": "סוג גבול",
  "Title": "כותרת",
  "Description": "תיאור",
  "Background Color": "צבע רקע",
  "Divider": "מחיצה",
  "Event Details Font": "גופן פרטי האירוע",
  "Website Link Color": "צבע קישור לאתר",
  "Developer Info": "מידע על מפתחים",
  "User Guide": "מדריך למשתמש",
  "Support e-mail": "תמיכה בדואר אלקטרוני",
  "Our Website": "האתר שלנו",
  "App Review": "סקירת אפליקציות",
  "Enjoying App? Leave us a review in the App Market.": "נהנה מאפליקציה? השאר לנו ביקורת בשוק האפליקציות. ",
  "Review Us": "סקור אותנו",
  "Connect With Us": "התחבר אלינו",
  "What's your email?": "מה המייל שלך?",
  "Invalid email address!": "כתובת דוא\"ל לא חוקית!",
  "Comments": "הערות",
  "We'd love to hear from you. Send us a message.": "נשמח לשמוע ממך. שלח לנו הודעה. ",
  "Message must be at least 5 characters long": "ההודעה חייבת להיות לפחות 5 תווים",
  "Send": "שלח",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "אם ברצונך לאפשר למשתמש לעבור בין תצוגות לוח השנה, הפעל אפשרות זו ובחר את התצוגות שברצונך להציג. ",
  "Main": "עיקרי",
  "Localize": "לוקליזציה",
  "Settings": "הגדרות",
  "Layouts": "פריסות",
  "Advanced": "מתקדם",
  "Design": "עיצוב",
  "Support": "תמיכה",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "כל ההגדרות המקומיות מבוססות (אוטומטית) על פי שפתך. אם השפה שלך ברשימה, אין צורך להתאים אישית את החלק הזה.",
  "Date Format": "פורמט תאריך",
  "Time Format": "פורמט זמן",
  "Text Direction": "כיוון טקסט",
  "Left to Right": "משמאל לימין",
  "Right to Left": "מימין לשמאל",
  "Week Starts On": "השבוע מתחיל",
  "Agenda Style": "סגנון אג'נדה",
  "Classic": "קלַאסִי",
  "Modern": "מוֹדֶרנִי",
  "Agenda Header": "כותרת סדר יום",
  "Upcoming Events": "אירועים קרובים",
  "Agenda Event Limit": "מגבלת אירועי סדר יום",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "שדרג עכשיו וקבל הרבה יותר תכונות ותיהנה מהאפליקציה שלך במלואה!",
  "Upgrade Now": "שדרג עכשיו",
  "Hosting events that last all day? This lets you show them on your calendar.": "אירוח אירועים שנמשך כל היום? זה מאפשר לך להראות אותם בלוח השנה שלך.",
  "24 hours": "24 שעות",
  "Sat": "יום שבת",
  "Sun": "יום ראשון",
  "Mon": "יום שני",
  "Default": "ברירת מחדל",
  "Select custom design style for your calendar.": "בחר סגנון עיצוב מותאם אישית ללוח השנה שלך.",
  "Style": "סגנון",
  "Styles and Colors": "סגנונות וצבעים",
  "Calendar Name": "שם לוח השנה",
  "Write your Calendar name here": "כתוב כאן את שם לוח השנה",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "זה לא גלוי למשתמשים שלך. הגדר שמות כדי להבדיל את לוחות השנה שלך בעת השימוש בפונקציית סנכרון לוח השנה של Boom.",
  "General Info": "מידע כללי",
  "Venue": "מָקוֹם מִפגָשׁ",
  "Organizer": "מְאַרגֵן",
  "Search": "לחפש",
  "Add to": "להוסיף ל",
  "calendar": "לוּחַ שָׁנָה",
  "Copy event URL": "העתק כתובת אתר לאירוע",
  "Copied!": "מוּעֲתָק!",
  "Add & Share": "הוסף ושיתוף",
  "Map": "מַפָּה",
  "Calendar view": "תצוגת לוח שנה",
  "Add Event": "הוסף אירועث",
  "Uncategorised": "ללא קטגוריה",
  "More": "יותר",
  "Less": "פָּחוּת",
  "Register": "הירשם",
  "Card": "כַּרְטִיס",

  "Guests": "אורחים",
  "unlimited": "ללא הגבלה",
  "Show more": "להראות יותר",
  "Enable Search": "אפשר חיפוש",
  "+ Add Event": "+ הוסף אירוע",
  "Manage and Sync": "ניהול וסנכרון",
  "Show event details as...": "הצג פרטי אירוע כ ...",
  "Tooltip": "הסבר כלים",
  "Popup": "תיבת מידע",
  "None": "אף אחד",
  "Show Category": "הצג קטגוריה",
  "Header Align": "יישור כותרת",
  "Show Time": "הצגת זמן",
  "Hours in Weekly/Daily View": "שעות בתצוגה שבועית / יומית",
  "Share Events": "שתף אירועים",
  "Shadow": "צֵל",
  "Inner Padding": "ריפוד פנימי",
  "Text": "טֶקסט",
  "Active Button Border": "גבול כפתור פעיל",
  "Light Mode": "מצב אור",
  "Event Text Color": "צבע טקסט אירוע",
  "Dates": "תאריכים",
  "Skeleton": "שֶׁלֶד",
  "Skeleton Color": "צבע השלד",
  "Width": "רוֹחַב",
  "Skeleton Style": "סגנון השלד",
  "Color": "צֶבַע",
  "Section Titles": "כותרות קטע",
  "Section Content": "תוכן המדור",
  "Header": "כּוֹתֶרֶת",
  "Standard": "תֶקֶן",
  "Retro": "רטרו",
  "Silver": "כסף",
  "Night": "לַיְלָה",
  "Dark": "אפל",
  "Aubergine": "חציל",
  "Map Header": "כותרת מפה",
  "Show Title in mobile": "הצג כותרת בנייד",
  "Card View": "תצוגת כרטיס",
  "Card background color": "צבע רקע כרטיס",
  "Title font": "גופן כותרת",
  "Desciption font": "גופן תיאור",
  "Section font": "קטע גופן",
  "Section divider color": "צבע מחלק חתך",
  "Add event": "הוסף אירוע",
  "All Day Event": "אירוע לכל היום",
  "Location": "מקום",
  "Choose a category": "בחר קטגוריה",
  "Venue name": "שם המקום",
  "Venue phone": "טלפון במקום",
  "Venue email": "דוא\"ל במקום",
  "Venue website": "אתר המקום",
  "Organizer name": "שם מארגן",
  "Organizer phone": "טלפון מארגן",
  "Organizer email": "דוא\"ל מארגן",
  "Organizer website": "אתר מארגן",
  "Personal info": "מידע אישי",
  "First name": "שם פרטי",
  "Last name": "שם משפחה",
  "Email Address": "כתובת דוא\"ל",
  "Additional Notes": "הערות נוספות",
  "Back": "חזור",
  "Save": "להציל",
  "Next": "הַבָּא",
  "Your event has been submitted": "האירוע שלך הוגש",
  "Event submittion has been failed": "הגשת האירוע נכשלה",
  "e.g. Birthday Party": "לְמָשָׁל. מסיבת יום הולדת",
  "First Name": "שם פרטי",
  "Last Name": "שם משפחה",
  "Phone Number": "מספר טלפון",
  "Address": "כתובת",
  "Your comments": "התגובות שלך",
  "How many guests?": "כמה אורחים?",
  "Anything else we need to know?": "עוד משהו שאנחנו צריכים לדעת?",
  "Guests:": "אורחים:",
  "Submit": "שלח",
  "Go to Calendar": "עבור ליומן",
  "Registration completed successfully!": "ההרשמה הושלמה בהצלחה!",
  "Please check your registered email address": "אנא בדוק את כתובת הדוא\"ל הרשומה שלך",
  "Add to Calendar": "הוסף ליומן",
  "Share this Event": "שתפו אירוע זה",
  "Sorry something went wrong": "מצטערים, משהו השתבש",
  "Back to registration": "חזרה להרשמה",
  "Date & Location": "תאריך ומיקום",
  "Date & Time": "תאריך שעה",
  "home": "בית",
  "Header align": "יישור הכותרת",
  "Footer": "כותרת תחתונה",
  "Categories Filter": "קטגוריות סינון",
  "Show only upcoming": "הצג רק בקרוב",
  "Card(s) in a row": "כרטיס / ים ברצף",
  "Space between cards": "רווח בין קלפים",
  "Shown events limit": "מגבלת אירועים שהוצגה",
  "Style 1": "סגנון 1",
  "Style 2": "סגנון 2",
  "Style 3": "סגנון 3.",
  "Style 4": "סגנון 4",
  "Buttons & Links": "כפתורים וקישורים",
  "Button corner radius": "רדיוס פינת כפתור",
  "Buttons font": "גופן כפתורים",
  "Buttons background": "לחצנים רקע",
  "Get notified by Email": "קבל הודעה בדוא\"ל",
  "Review events": "סקור אירועים",
  "Click on date": "לחץ על תאריך",
  "Add Event button": "כפתור הוסף אירוע",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "סנכרון לוח השנה מאפשר לך לשלב את האירועים וההפעלות שלך עם לוח השנה של הבום שלך.",
  "connect": "לְחַבֵּר",
  "Synchronized Calendars": "לוחות שנה מסונכרנים",
  "Import events": "ייבא אירועים",
  "Disconnect": "לְנַתֵק",
  "Choose calendar": "בחר לוח שנה",
  "Monitor your Wix events through the sync feature": "עקוב אחר אירועי ה- Wix שלך באמצעות תכונת הסינכרון",
  "Connect all your Boom calendars available on your website": "חבר את כל לוחות השנה של Boom הזמינים באתר שלך",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "לוח הזמנים, הצטרף וננהל מפגשי זום דרך היומן שלנו בום.",
  "Monitor your Event Brite events through the Event Brite sync feature": "עקוב אחר אירועי Brite האירועים שלך באמצעות תכונת הסינכרון של Event Brite",
  "Email": "אימייל",
  "Add-ons": "תוספות",
  "Receive notification emails as soon as users add events to your calendar.": "קבלת הודעות דוא\"ל בהקדם האפשרי כמשתמשים להוסיף אירועים ללוח השנה שלך.",
  "Enable + button on the calendar header": "הפעל + כפתור בכותרת היומן",
  "Accept or decline events added by customers before making them public.": "קבל או ירידה באירועים שנוספו על ידי לקוחות לפני ביצועם ציבוריים.",
  "Switch Add Event": "מתג להוסיף אירוע",
  "Enable your browser cookies to connect to your account.": "הפעל עוגיות הדפדפן שלך כדי להתחבר לחשבון שלך.",
  "Learn more": "למד עוד",
  "Print Button": "Bouton d'impression",
  "Permit your users to print your Boom Event Calendar in any date range.": "היתר למשתמשים שלך להדפיס את לוח האירוע של בום בכל טווח תאריך.",
  "Show Title on mobile": "הצג כותרת על נייד",
  "Show Skeleton on mobile": "הצג שלד על נייד",
  "Start 7-day Business trial": "התחל את המשפט העסקי של 7 ימים",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "ליהנות מכל התכונות הבלתי מוגבלות, כגון למכור כרטיסים, רישום, תוספות אירוע מבקרים.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "שים לב: בסוף תקופת הניסיון תוחזר לתוכנית המנוי הקיימת שלך.",
  "Not Now": "לא עכשיו",
  "Start free trial": "להתחיל ניסיון ללא תשלום",
  "Congrats!": "מזל טוב!",
  "Your 7-day Business trial has been successfully activated.": "המשפט העסקי של 7 ימים שלך הופעל בהצלחה.",
  "Done": "בוצע",
  "Title font color": "כותרת צבע גופן",
  "Desciption font color": "תיאור צבע גופן",
  "Section font color": "סעיף צבע גופן",
  "Card Header": "כותרת כרטיס",
  "Category": "קטגוריה",
  "Display at the": "תצוגה ב",
  "top": "חלק עליון",
  "bottom": "תַחתִית",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "הצג את מסנן הקטגוריה בחלק העליון או בחלק התחתון של היומן.ההגדרות חלות על תצוגות אג'נדה וכרטיס בלבד",
  "Processing your events": "עיבוד האירועים שלך",
  "Search for events": "חפש אירועים",
  "There are no events added": "לא הוסיף אירועים",
  "Location: To be determined": "מיקום: כדי לקבוע",
  "No events for selected date": "אין אירועים לתאריך שנבחר",
  "Uncategorized": "לא מסווג",
  "Edit event": "ערוך אירוע",
  "Edit original event": "ערוך אירוע מקורי",
  "Copy event": "אירוע העתק",
  "Copy as new event": "העתק כאירוע חדש",
  "Delete event": "מחק אירוע",
  "Stop repeating on this date": "הפסק לחזור בתאריך זה",
  "Exclude this date": "תכלול תאריך זה",
  "Location is going to be announced": "המיקום הולך להיות מוכרז",
  "Fill your personal information": "מלא את המידע האישי שלך",
  "Check Box": "תיבת סימון",
  "Single Choice": "בחירה יחידה",
  "Option": "אוֹפְּצִיָה",
  "Share Event": "שתף אירוע",
  "Oops! Something went wrong": "אופס!משהו השתבש",
  "We are sorry this event has already taken place": "אנו מצטערים שהאירוע הזה כבר התרחש",
  "Back to calendar": "חזרה ללוח השנה",
  "This field is required": "זהו שדה חובה",
  "Phone": "טלפון",
  "Number field": "שדה מספר",
  "Option": "אוֹפְּצִיָה",
  "Check Box": "תיבת סימון",
  "Single Choice": "בחירה יחידה",
 "Please provide a valid email" : "אנא ספק דוא\"ל תקף",
 "Select at least one option" : "בחר לפחות אפשרות אחת"
}
export default he
