let hi = {
  "Categories": "श्रेणियाँ",
  "Share this event": "इस घटना को साझा करें",
  "Language": "भाषा",
  "Show Time Zone": "समय क्षेत्र दिखाएं",
  "Custom Local Settings": "कस्टम स्थानीय सेटिंग",
  "Add and showcase events on your site using a beautiful calendar.": "एक सुंदर कैलेंडर का उपयोग करके अपनी साइट पर इवेंट जोड़ें और दिखाएं । ",
  "Week Days": "सप्ताह के दिन",
  "Manage Events": "ईवेंट प्रबंधित करें",
  "General": "सामान्य",
  "Layout Picker": "लेआउट पिकर",
  "Month": "महीना",
  "Monthly": "महीने के",
  "Week": "सप्ताह",
  "Weekly": "साप्ताहिक",
  "Day": "दिवस",
  "Daily": "रोज",
  "Agenda": "एजेंडा",
  "Navigation Buttons": "नेविगेशन बटन",
  "Week numbers": "सप्ताह संख्या",
  "Include Weekends": "सप्ताहांत शामिल करें",
  "All-day": "पूरे दिन",
  "All Day": "पूरे दिन",
  "Label": "लेबल",
  "Fit to Height": "फिट टू हाइट",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "ऐप अनुपात सेट करने के लिए इस विकल्प को मैन्युअल रूप से अक्षम करें और संपादक में कैलेंडर का आकार बदलें। ",
  "Default Layout": "मूलभूत ढांचा",
  "Monthly view": "मासिक दृश्य",
  "Weekly and Daily view": "साप्ताहिक और दैनिक दृश्य",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "आप एक बार में एक ही सप्ताह ( 6) दिखा कर आगंतुकों को अधिक सुसंगत अनुभव दे सकते हैं ।",
  "Fixed Weekly Layout": "फिक्स्ड साप्ताहिक लेआउट",
  "back": " वापस ",
  "Row": "पंक्ति",
  "Hours in Weekly View": "साप्ताहिक दृश्य में घंटे",
  "Hours in Daily View": "दैनिक दृश्य में घंटे",
  "Start": "शुरू",
  "End": "समाप्त",
  "At This Hour": "इस घंटे",
  "Button": "बटन",
  "Buttons": "बटन",
  "Sunday": "रविवार",
  "Monday": "सोमवार",
  "Tuesday": "मंगलवार",
  "Wednesday": "बुधवार",
  "Thursday": " गुरुवार ",
  "Friday": "शुक्रवार",
  "Saturday": "शनिवार",
  "Default Date": "डिफ़ॉल्ट तिथि",
  "year": " वर्ष ",
  "month": " महीना ",
  "days": " दिन ",
  "ago": " पहले ",
  "ahead": " आगे ",
  "Yesterday": "बिता कल",
  "Today": "आज",
  "Tomorrow": "आने वाला कल",
  "Custom": "कस्टम",
  "Set Daily Rows Limit": "दैनिक पंक्तियाँ सीमा निर्धारित करें",
  "Set Proportions": "सेट अनुपात",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "आगंतुक को स्थानीय कैलेंडर में घटना जोड़ने की अनुमति दें , Google, Yahoo, Outlook, ICalendar । ",
  "Container": "कंटेनर",
  "Background": "पृष्ठभूमि",
  "Container Background": "कंटेनर पृष्ठभूमि",
  "Container Borders": "कंटेनर बॉर्डर",
  "Calendar": "कैलेंडर",
  "Event Info Tooltip": "घटना की जानकारी टूलटिप",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "जब लोग किसी घटना पर होवर करते हैं तो वे इसके बारे ��ें सारी जानकारी टूलटिप में देखेंगे। ",
  "Event Info Window": "इवेंट इंफो विंडो",
  "This is the full information window that opens when someone clicks on the event.": "यह पूरी जानकारी विंडो है जो किसी के घटना पर क्लिक करने पर खुलती है। ",
  "Use Gradient": "ग्रेडिएंट का उपयोग करें",
  "Vertical": "लंबवत",
  "Horizontal": "क्षैतिज",
  "First": "प्रथम",
  "Second": "दूसरा",
  "diagonal": " विकर्ण ",
  "Radial": "रेडियल",
  "Select option": "विकल्प चुनें",
  "Solid": "ठोस",
  "Dotted": "बिंदीदार",
  "Dashed": "डैश्ड",
  "Double": "डबल",
  "Border Radius": "सीमा त्रिज्या",
  "Padding": "गद्दी",
  "Date Header": "तिथि हैडर",
  "Event Default Color": "ईवेंट डिफ़ॉल्ट रंग",
  "Days of Week": "सप्ताह के दिन",
  "Days of Week Background": "सप्ताह की पृष्ठभूमि के दिन",
  "Date": "दिनांक",
  "Event Title": "कार्यक्रम का शीर्षक",
  "Highlight today": "आज हाइलाइट करें",
  "Highlight Color": "हाइलाइट रंग",
  "Hide": "छिपाना",
  "Calendar Border Color": "कैलेंडर बॉर्डर कलर",
  "Calendar Border Width": "कैलेंडर बॉर्डर चौड़ाई",
  "Calendar Border Style": "कैलेंडर बॉर्डर स्टाइल",
  "Font Color": "लिपि का रंग",
  "Event Background": "इवेंट बैकग्राउंड",
  "Card Date Color": "कार्ड की तारीख का रंग",
  "Title Font": "टाइटल फ़ॉन्ट",
  "Date Font": "दिनांक फ़ॉन्ट",
  "Description Font": "विवरण विवरण",
  "Button Background": "बटन पृष्ठभूमि",
  "Button Text": "टेक्स्ट बटन",
  "Border Color": "किनारे का रंग",
  "Border Width": "सीमा चौड़ाई",
  "Border Type": "सीमा प्रकार",
  "Title": "शीर्षक",
  "Description": "विवरण",
  "Background Color": "पीछे का रंग",
  "Divider": "विभाजक",
  "Event Details Font": "ईवेंट विवरण फ़ॉन्ट",
  "Website Link Color": "वेबसाइट लिंक रंग",
  "Developer Info": "डेवलपर",
  "User Guide": "उपयोगकर्ता गाइड",
  "Support e-mail": "ई-मेल का समर्थन करें",
  "Our Website": "हमारी वेबसाइट",
  "App Review": "ऐप रिव्यू",
  "Enjoying App? Leave us a review in the App Market.": "ऐप का आनंद लेना । ऐप मार्केट में हमें एक समीक्षा छोड़ दें । ",
  "Review Us": "हमारी समीक्षा करें",
  "Connect With Us": "हमसे जुडे",
  "What's your email?": "आपका ईमेल क्या है? ",
  "Invalid email address!": "अमान्य ईमेल पता! ",
  "Comments": "टिप्पणियाँ",
  "We'd love to hear from you. Send us a message.": "हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें। ",
  "Message must be at least 5 characters long": "संदेश कम से कम 5 वर्ण लंबा होना चाहिए",
  "Send": "भेजें",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "यदि आप उपयोगकर्ता को कैलेंडर विचारों के बीच स्विच करने की अनुमति देना चाहते हैं, तो इस विकल्प को सक्षम करें औ�� उन विचारों को चुनें जिन्हें आप दिखाना चाहते हैं। ",
  "Main": "मुख्य",
  "Localize": "स्थानीय बनाना",
  "Settings": "सेटिंग्स",
  "Layouts": "लेआउट",
  "Advanced": "उन्नत",
  "Design": "डिज़ाइन",
  "Support": "समर्थन",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "आपकी भाषा के आधार पर सभी स्थानीय सेटिंग्स (स्वचालित रूप से) हैं। यदि आपकी भाषा सूची में है, तो इस अनुभाग को अनुकूलित करने की कोई आवश्यकता नहीं है।",
  "Date Format": "डेटा प्रारूप",
  "Time Format": "समय प्रारूप",
  "Text Direction": "पाठ की दिशा",
  "Left to Right": "बाएं से दाएं",
  "Right to Left": "दाएं से बाएं",
  "Week Starts On": "सप्ताह की शुरुआत",
  "Agenda Style": "एजेंडा स्टाइल",
  "Classic": "क्लासिक",
  "Modern": "आधुनिक",
  "Agenda Header": "एजेंडा हैडर",
  "Upcoming Events": "आने वाले कार्यक्रम",
  "Agenda Event Limit": "एजेंडा इवेंट लिमिट",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "अब अपग्रेड करें और बहुत अधिक सुविधाएं प्राप्त करें और अपने एपीपी का पूरा आनंद लें!",
  "Upgrade Now": "अभी अपग्रेड करें",
  "Hosting events that last all day? This lets you show them on your calendar.": "पूरे दिन चलने वाली घटनाओं की मेजबानी करना; इससे आप उन्हें अपने कैलेंडर पर दिखा सकते हैं।",
  "24 hours": "चौबीस घंटे",
  "Sun": "रविवार",
  "Mon": "सोमवार",
  "Sat": "शनिवार",
  "Default": "चूक",
  "Select custom design style for your calendar.": "अपने कैलेंडर के लिए कस्टम डिज़ाइन शैली का चयन करें।",
  "Style": "अंदाज",
  "Styles and Colors": "शैलियाँ और रंग",
  "Calendar Name": "कैलेंडर का नाम",
  "Write your Calendar name here": "अपने कैलेंडर का नाम यहाँ लिखें",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "यह आपके उपयोगकर्ताओं को दिखाई नहीं देता है। बूम कैलेंडर सिंक फ़ंक्शन का उपयोग करते समय अपने कैलेंडर को अलग करने के लिए नाम सेट करें।",
  "General Info": "सामान्य जानकारी",
  "Venue": "स्थान",
  "Organizer": "व्यवस्था करनेवाला",
  "Search": "खोज",
  "Add to": "में जोड़े",
  "calendar": "पंचांग",
  "Copy event URL": "ईवेंट URL की प्रतिलिपि बनाएँ",
  "Copied!": "מוּעֲתָק!",
  "Add & Share": "जोड़ें और साझा करें",
  "Map": "नक्शा",
  "Calendar view": "कैलेंडर दृश्य",
  "Add Event": "कार्यक्रम जोड़ेंث",
  "Uncategorised": "अवर्गीकृत",
  "More": "अधिक",
  "Less": "कम",
  "Register": "रजिस्टर करें",
  "Card": "कार्ड",

  "Guests": "मेहमानों",
  "unlimited": "��सीमित",
  "Show more": "और दिखाओ",
  "Enable Search": "खोज सक्षम करें",
  "+ Add Event": "+ ईवेंट जोड़ें",
  "Manage and Sync": "प्रबंधित करें और सिंक करें",
  "Show event details as...": "घटना का विवरण दिखाएं ...",
  "Tooltip": "टूलटिप",
  "Popup": "जानकारी बॉक्स",
  "None": "कोई नहीं",
  "Show Category": "श्रेणी दिखाएँ",
  "Header Align": "हैडर संरेखित करें",
  "Show Time": "शो टाइम",
  "Hours in Weekly/Daily View": "साप्ताहिक / दैनिक दृश्य में घंटे",
  "Share Events": "घटनाओं को साझा करें",
  "Shadow": "साया",
  "Inner Padding": "इनर पैडिंग",
  "Text": "टेक्स्ट",
  "Active Button Border": "सक्रिय बटन बॉर्डर",
  "Light Mode": "लाइट मोड",
  "Event Text Color": "इवेंट टेक्स्ट कलर",
  "Dates": "खजूर",
  "Skeleton": "कंकाल",
  "Skeleton Color": "कंकाल का रंग",
  "Width": "चौड़ाई",
  "Skeleton Style": "कंकाल शैली",
  "Color": "रंग",
  "Section Titles": "अनुभाग शीर्षक",
  "Section Content": "अनुभाग सामग्री",
  "Header": "हैडर",
  "Standard": "मानक",
  "Retro": "रेट्रो",
  "Silver": "चांदी",
  "Night": "रात",
  "Dark": "अंधेरा",
  "Aubergine": "बैंगन",
  "Map Header": "नक्शा हैडर",
  "Show Title in mobile": "मोबाइल में शीर्षक दिखाएं",
  "Card View": "कार्ड देखें",
  "Card background color": "कार्ड पृष्ठभूमि का रंग",
  "Title font": "टाइटल फ़ॉन्ट",
  "Desciption font": "वर्णन फ़ॉन्ट",
  "Section font": "फ़ॉन्ट अनुभाग",
  "Section divider color": "खंड विभक्त रंग",
  "Add event": "कार्यक्रम जोड़ें",
  "All Day Event": "पूरे दिन की घटना",
  "Location": "स्थान",
  "Choose a category": "कोई श्रेणी चुनें",
  "Venue name": "स्थल का नाम",
  "Venue phone": "वेन्यू फोन",
  "Venue email": "वेन्यू ईमेल",
  "Venue website": "स्थल वेबसाइट",
  "Organizer name": "आयोजक का नाम",
  "Organizer phone": "आयोजक फोन",
  "Organizer email": "आयोजक ईमेल",
  "Organizer website": "आयोजक वेबसाइट",
  "Personal info": "व्यक्तिगत जानकारी",
  "First name": "पहला नाम",
  "Last name": "उपनाम",
  "Email Address": "ईमेल पता",
  "Additional Notes": "अतिरिक्त नोट्स",
  "Back": "वापस",
  "Save": "सहेजें",
  "Next": "आगे",
  "Your event has been submitted": "आपका ईवेंट सबमिट कर दिया गया है",
  "Event submittion has been failed": "इवेंट सबमिशन फेल हो गया है",
  "e.g. Birthday Party": "जैसे जन्मदिन उत्सव",
  "First Name": "पहला नाम",
  "Last Name": "उपनाम",
  "Phone Number": "फ़ोन नंबर",
  "Address": "पता",
  "Your comments": "आपकी टिप्पणी",
  "How many guests?": "कितने मेहमान?",
  "Anything else we need to know?": "हमें कुछ और जानना चाहिए?",
  "Guests:": "मेहमान:",
  "Submit": "प्रस्तुत",
  "Go to Calendar": "עבור ליומן",
  "Registration completed successfully!": "पंजीकरण सफलतापूर्वक पूरा हुआ!",
  "Please check your registered email address": "कृपया अपना पंजीकृत ईमेल पता जांचें",
  "Add to Calendar": "कैलेंडर में जोड़ें",
  "Share this Event": "इस घटना को साझा करें",
  "Sorry something went wrong": "क्षमा करें, कुछ गलत हो गया",
  "Back to registration": "वापस पंजीकरण के लिए",
  "Date & Location": "दिनांक और स्थान",
  "Date & Time": "दिनांक और समय",
  "home": "घर",
  "Header align": "Header align",
  "Footer": "फ़ुटबाल",
  "Categories Filter": "श्रेणियां फ़िल्टर",
  "Show only upcoming": "केवल आगामी दिखाएं",
  "Card(s) in a row": "एक पंक्ति में कार्ड",
  "Space between cards": "कार्ड के बीच की जगह",
  "Shown events limit": "दिखाया घटनाओं की सीमा",
  "Style 1": "शैली 1",
  "Style 2": "शैली २",
  "Style 3": "शैली ३",
  "Style 4": "शैली ४",
  "Buttons & Links": "Buttons & Links",
  "Button corner radius": "बटन कोने त्रिज्या",
  "Buttons font": "बटन फ़ॉन्ट",
  "Buttons background": "बटन पृष्ठभूमि",
  "Get notified by Email": "ईमेल द्वारा अधिसूचित हो जाओ",
  "Review events": "घटनाक्रम की समीक्षा",
  "Click on date": "तारीख पर क्लिक करें",
  "Add Event button": "ईवेंट बटन जोड़ें",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "कैलेंडर सिंक आपको अपने बूम कैलेंडर के साथ अपनी घटनाओं और सत्रों को एकीकृत करने की अनुमति देता है।",
  "connect": "connect",
  "Synchronized Calendars": "सिंक्रनाइज़ कैलेंडर्स",
  "Import events": "घटनाओं को आयात करें",
  "Disconnect": "डिस्कनेक्ट",
  "Choose calendar": "कैलेंडर चुनें",
  "Monitor your Wix events through the sync feature": "सिंक सुविधा के माध्यम से अपनी Wix घटनाओं की निगरानी करें",
  "Connect all your Boom calendars available on your website": "अपनी वेबसाइट पर उपलब्ध अपने सभी बूम कैलेंडर को कनेक्ट करें",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "हमारे बूम कैलेंडर के माध्यम से सही ज़ूम मीटिंग्स को शेड्यूल करें, जुड़ें और प्रबंधित करें।",
  "Monitor your Event Brite events through the Event Brite sync feature": "इवेंट ब्राइट सिंक फीचर के माध्यम से अपने ईवेंट ब्राइट इवेंट्स की निगरानी करें",
  "Email": "ईमेल",
  "Add-ons": "ऐड-ऑन",
  "Receive notification emails as soon as users add events to your calendar.": "Receive notification emails as soon as users add events to your calendar.",
  "Enable + button on the calendar header": "कैलेंडर हेडर पर + बटन सक्षम करें",
  "Accept or decline events added by customers before making them public.": "उन्हें सार्वजनिक करने से पहले ग्राहकों द्वारा जोड़े गए घटनाओं को स्वीकार या अस्वीकार करें।",
  "Switch Add Event": "स्विच इवेंट स्विच करें",
  "Enable your browser cookies to connect to your account.": "अपने खाते से कनेक्ट करने के लिए अपनी ब्राउज़र कुकीज़ सक्षम करें।",
  "Learn more": "और अधिक जानें",
  "Print Button": "Bouton d'impression",
  "Permit your users to print your Boom Event Calendar in any date range.": "अपने उपयोगकर्ताओं को किसी भी तारीख सीमा में अपने बूम इवेंट कैलेंडर को प्रिंट करने की अनुमति दें।",
  "Show Title on mobile": "मोबाइल पर शीर्षक दिखाएं",
  "Show Skeleton on mobile": "मोबाइल पर कंकाल दिखाएं",
  "Start 7-day Business trial": "अपना 7-दिन का व्यवसाय परीक्षण शुरू करें",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "टिकट, पंजीकरण, आगंतुक घटना ऐड-ऑन बेचने जैसी सभी असीमित सुविधाओं का आनंद लें।",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "कृपया ध्यान दें: परीक्षण अवधि के अंत में, आपको अपनी मौजूदा सदस्यता योजना में वापस कर दिया जाएगा।",
  "Not Now": "अभी नहीं",
  "Start free trial": "निशुल्क आजमाइश शुरु करें",
  "Congrats!": "बधाई!",
  "Your 7-day Business trial has been successfully activated.": "आपका 7-दिवसीय व्यवसाय परीक्षण सफलतापूर्वक सक्रिय हो गया है।",
  "Done": "किया हुआ",
  "Title font color": "शीर्षक फ़ॉन्ट रंग",
  "Desciption font color": "विवरण फ़ॉन्ट रंग",
  "Section font color": "खंड फ़ॉन्ट रंग",
  "Card Header": "कार्ड हेडर",
  "Category": "श्रेणी",
  "Display at the": "पर प्रदर्शित",
  "top": "ऊपर",
  "bottom": "नीचे",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "शीर्ष पर या कैलेंडर के नीचे श्रेणी फ़िल्टर का प्रदर्शन करें।सेटिंग्स केवल एजेंडा और कार्ड के दृश्यों पर लागू होती हैं",
  "Processing your events": "अपनेघटनाओंका संसाधन",
  "Search for events": "घटनाओं के लिए खोजें",
  "There are no events added": "कोई घटना नहीं है",
  "Location: To be determined": "स्थान: निर्धारित किया जाना है",
  "No events for selected date": "चयनित तिथि के लिए कोई घटना नहीं",
  "Uncategorized": "अवर्गीकृत",
  "Edit event": "संपादन कार्यक्रम",
  "Edit original event": "मूल घटना संपादित करें",
  "Copy event": "प्रतिलिपि घटना",
  "Copy as new event": "नई घटना के रूप में कॉपी करें",
  "Delete event": "घटना को हटा दें",
  "Stop repeating on this date": "इस तिथि को दोहराना बंद करें",
  "Exclude this date": "इस तिथि को छोड़ दें",
  "Location is going to be announced": "स्थान की घोषणा की जा रही है",
  "Fill your personal information": "अपनी व्यक्तिगत जानकारी भरें",
  "Check Box": "चेक बॉक्स",
  "Single Choice": "एकल विकल्प",
  "Option": "विकल्प",
  "Share Event": "शेयर घटना",
  "Oops! Something went wrong": "उफ़!कुछ गलत हो गया",
  "We are sorry this event has already taken place": "हमें खेद है कि यह घटना पहले ही हो चुकी है",
  "Back to calendar": "वापस कैलेंडर पर",
  "This field is required": "यह फ़ील्ड आवश्यक है",
  "Phone": "फ़ोन",
  "Number field": "संख्या क्षेत्र",
  "Option": "विकल्प",
  "Check Box": "चेक बॉक्स",
  "Single Choice": "एकल विकल्प",
 "Please provide a valid email" : "कृपया सही ईमेल पता बताएं",
 "Select at least one option" : "कम से कम एक विकल्प चुनें",
 "Choose tickets to see total value" : "कुल मूल्य देखने के लिए टिकट चुनें",
 "tickets" : "टिकट",
 "Choose Tickets" : "टिकट चुनें",
 "Choose payment method" : "भुगतान विधि चुनें",
 "Pay" : "भुगतान करना",
 "Total" : "कुल",
 "Free" : "मुक्त",
 "Buy tickets" : "टिकट खरीदो"
}
export default hi