let hu = {
  /* add event pop-up start*/
  "e.g. Birthday Party": "például. Szülinapi buli",
  Organizer: "Szervező",
  "Location is going to be announced": "A helyet bejelentik",
  "Add Event": "Esemény hozzáadása",
  "All Day Event": "Egész napos esemény",
  Location: "Elhelyezkedés",
  "General Info": "Általános információ",
  Description: "Leírás",
  Next: "Következő",
  "Make your contribution by adding your event to the calendar":
    "Hozzájáruljon azáltal, hogy hozzáadja az eseményt a naptárhoz",
  "Event name": "Esemény neve",
  "Start time": "Kezdési idő",
  "End time": "Idő vége",
  "Physical location": "Fizikai elhelyezkedés",
  Online: "Online",
  "To be announced": "Be kell hirdetni",
  "Add Image": "Kép hozzáadása",
  "Event color": "Eseményszín",
  "Choose categories": "Válassza ki a kategóriákat",
  "There are no categories to select":
    "Nincsenek kategóriák a kiválasztandó kategóriákkal",
  "Location name": "A helyszín neve",
  "Location email": "Helyszín e -mail",
  "Location phone": "Hely telefon",
  "Location website": "Helyszín",
  "Organizer name": "Szervező neve",
  "Organizer phone": "Szervező telefon",
  "Organizer email": "Szervező e -mail",
  "Organizer website": "Szervező webhely",
  "Add meeting link": "Találkozó link hozzáadása",
  "Choose category": "Válassza a Kategória lehetőséget",
  Cancel: "Megszünteti",
  Publish: "Közzétesz",
  /* add event pop-up end*/

  Categories: "Kategóriáks",
  "Share this event": "Ossza meg ezt az eseményt",
  Language: "Nyelv",
  "Show Time Zone": "Mutasson Idő zónát",
  "Custom Local Settings": "Egyedi hely beállítás",
  "Add and showcase events on your site using a beautiful calendar.":
    "Adj hozzá eseményeket az oldaladhoz, ezzel a csodás naptárral.",
  "Week Days": "Hétköznapok",
  "Manage Events": "Események kezelése",
  General: "Általános",
  "Layout Picker": "Kinézet választó",
  Month: "Hónap",
  Monthly: "Havonta",
  Week: "Hét",
  Weekly: "Hetente",
  Day: "Nap",
  Daily: "Naponta",
  Agenda: "Napirend",
  "Navigation Buttons": "Irányító gombok",
  "Week numbers": "Hetek számozása",
  "Include Weekends": "Hétvégét belevéve",
  "All Day": "Egész nap",
  Label: "Felirat",
  "Fit to Height": "Magassághoz igazítva",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Az alkalmazás méretének manuális beállításához tiltsale ezt a lehetőséget, és méretezzé át a Naptár szerkesztőben.",
  "Default Layout": "Alapértelmezett nézet",
  "Monthly view": "Havi nézet",
  "Weekly and Daily view": "Heti és Napi nézet",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "A látogatóknak nyújts következetesebb érzést azzal, hogy ugyanazt a hetet mutatod.",
  "Fixed Weekly Layout": "Fix heti kinézet",
  back: "vissza",
  Row: "Sor",
  "Hours in Weekly View": "Órák a heti nézetben",
  "Hours in Daily View": "Órák a napi nézetben",
  Start: "Rajt",
  End: "Vég",
  "At This Hour": "Ebben az órában",
  Button: "Gomb",
  Buttons: "Gombok",
  Sunday: "Vasárnap",
  Monday: "Hétfő",
  Tuesday: "Kedd",
  Wednesday: "Szerda",
  Thursday: "Csütörtök",
  Friday: "Péntek",
  Saturday: "Szombat",
  "Default Date": "Alapértelmezett dátum",
  year: "év",
  month: "hónap",
  mo: "hónap",
  days: "napok",
  ago: "előtt",
  ahead: "előre",
  Yesterday: "Tegnap",
  Today: "Ma",
  Tomorrow: "Holnap",
  Custom: "Egyedi",
  "Set Daily Rows Limit": "Állíts napi sor limitet",
  "Set Proportions": "Állíts tagolást",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Engedélyezd a látogatóknak, hogy hozzáadják az eseményeket a saját naptárjukhoz = Google, Yahoo, Outlook, ICalender.",
  Container: "Tartó",
  Background: "Háttér",
  "Container Background": "Tartó háttér",
  "Container Borders": "Tartó keretek",
  Calendar: "Naptár",
  "Event Info Tooltip": "Esemény info tanács",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Amikor az emberek az egérmutatót egy esemény fölé viszik, akkor azerről szóló összes információt egy leírásban látják.",
  "Event Info Window": "Esemény Info Ablak",
  "This is the full information window that opens when someone clicks on the event.":
    "Ez a full információ ablak, ha valaki rákattint az eseményre,Use Gradient = Használja a színátmenetet",
  "Use Gradient": "Használja a színátmenetet",
  Vertical: "Vertikális",
  Horizontal: "Horizontális",
  First: "Első",
  Second: "Második",
  diagonal: "átló",
  Radial: "Sugár",
  "Select option": "Választható opció",
  Solid: "Szolid",
  Dotted: "Pontos",
  Dashed: "Szaggatott",
  Double: "Kettős",
  "Border Radius": "Határ sugár",
  Padding: "Tömés",
  "Date Header": "Dátum fejléc",
  "Event Default Color": "Esemény alapértelmezett szín",
  "Days of Week": "A hét napjai",
  "Days of Week Background": "A hét napjai háttere",
  Date: "Dátum",
  "Event Title": "Esemény címe",
  "Highlight today": "Kiemelés ma",
  "Highlight Color": "Kiemelés szín",
  Hide: "Elrejt",
  "Calendar Border Color": "Naptár keret szín",
  "Calendar Border Width": "Naptár keret szélesség",
  "Calendar Border Style": "Naptár keret stílus",
  "Font Color": "Betűtípus szín",
  "Event Background": "Esemény háttér",
  "Card Date Color": "Kártya datum szín",
  "Title Font": "Cím betűtípus",
  "Date Font": "Dátum betűtípus",
  "Description Font": "Leírás betűtípus",
  "Button Background": "Gomb háttér",
  "Button Text": "Gomb szöveg",
  "Border Color": "Keret szín",
  "Border Width": "Keret szélesség",
  "Border Type": "Keret típus",
  Title: "Cím",
  "Background Color": "Háttér szín",
  Divider: "Osztó",
  "Event Details Font": "Esemény leírás betűtípus",
  "Website Link Color": "Weboldal link szín",
  "Developer Info": "Fejlesztői Info",
  "User Guide": "Használati útmutató",
  "Support e-mail": "Ügyfélszolgálat e-mail",
  "Our Website": "Mi weboldalunk",
  "App Review": "App értékelés",
  "Enjoying App? Leave us a review in the App Market.":
    "Tetszik az app? Írj egy értékelés az App Marketben.",
  "Review Us": "Értékelj minket",
  "Connect With Us": "Lépj kapcsolatban velünk",
  "What's your email?": "Mi az email címed?",
  "Invalid email address!": "Helytelen email cím!",
  Comments: "Kommentek",
  "We'd love to hear from you. Send us a message.":
    "Örömmel hallunk felőled! Írj üzenetet nekünk.",
  "Message must be at least 5 characters long":
    "Az üzenetnek minimum 5 karakter hosszúságúnak kell hogy legyen",
  Send: "Küldés",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ha azt szeretnéd hogy a felhasználók tudjanak váltani a naptár nézet között, engedélyezd ezt a opciót és válassza ki a megjeleníteni kívánt nézetet.",
  Main: "Főoldal",
  Localize: "Hely",
  Settings: "Beállítások",
  Layouts: "Kinézetek",
  Advanced: "Haladó",
  Design: "Kinézet",
  Support: "Segítség",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Az összes helyi beállítás (automatikusan) az Ön nyelvén alapul. Ha az Ön nyelve szerepel a listán, akkor nem kell testreszabnia ezt a részt.",
  "Date Format": "Dátum formátum",
  "Time Format": "Idő formátum",
  "Text Direction": "Szöveg irány",
  "Left to Right": "Balról jobbra",
  "Right to Left": "Jobbról balra",
  "Week Starts On": "Hét kezdés",
  "Agenda Style": "Napirend stílus",
  Classic: "Klasszikus",
  Modern: "Modern",
  "Agenda Header": "Napirend fejléc",
  "Upcoming Events": "Közeledő események",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Bővíts most és aktiválj több lehetőséget, hogy teljes mértékben élvezd az APP- ot!",
  "Upgrade Now": "Bővíts most",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Egésznapos események? Ez lehetővé teszi, hogy megmutassa őket a naptárban.",
  "24 hours": "24 órás",
  Sun: "Vas",
  Mon: "Hét",
  Sat: "Szom",
  Default: "Alapértelmezett",
  Style: "Stílus",
  "Calendar Name": "Naptár neve",
  "Write your Calendar name here": "Írja ide a naptár nevét",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ez a felhasználók számára nem látható. Nevek beállítása a naptárak megkülönböztetésére a Boom Calendar Sync funkció használatakor.",
  Venue: "Helyszín",
  Search: "Keresés",
  "Add to": "Hozzáad",
  calendar: "naptár",
  "Copy event URL": "Másolja az esemény URL-jét",
  "Copied!": "Másolt!",
  "Add & Share": "Hozzáadás és megosztás",
  Map: "Térkép",
  "Calendar view": "Naptár nézet",
  Uncategorised: "Uncategorized",
  More: "Több",
  Less: "Kevésbé",
  Register: "Regisztráció",
  Card: "Kártya",

  Guests: "Vendégek",
  unlimited: "korlátlan",
  "Show more": "Mutass többet",
  "Enable Search": "A keresés engedélyezése",
  "+ Add Event": "+ Esemény hozzáadása",
  "Manage and Sync": "Kezelés és szinkronizálás",
  "Show event details as...": "Mutassa az esemény részleteit mint ...",
  Tooltip: "Tooltip",
  Popup: "Információs doboz",
  None: "Egyik sem",
  "Show Category": "Kategória megjelenítése",
  "Header Align": "Fejléc igazítása",
  "Show Time": "Mutasd az időt",
  "Hours in Weekly/Daily View": "Órák heti / napi nézetben",
  "Share Events": "Események megosztása",
  Shadow: "Árnyék",
  "Inner Padding": "Belső párna",
  Text: "Szöveg",
  "Active Button Border": "Aktív gomb szegély",
  "Light Mode": "Világos mód",
  "Event Text Color": "Esemény szöveg színe",
  Dates: "Időpontok",
  Skeleton: "Csontváz",
  "Skeleton Color": "Csontváz szín",
  Width: "Szélesség",
  "Skeleton Style": "Csontváz stílus",
  Color: "Szín",
  "Section Titles": "Szakasz címei",
  "Section Content": "Szakasz tartalma",
  Header: "Fejléc",
  Standard: "Alapértelmezett",
  Retro: "Retro",
  Silver: "Ezüst",
  Night: "Éjszaka",
  Dark: "Sötét",
  Aubergine: "Padlizsán",
  "Map Header": "Térkép fejléce",
  "Show Title in mobile": "Mutasd a címet mobilon",
  "Card View": "Kártya nézet",
  "Card background color": "Kártya háttér színe",
  "Title font": "Cím betűtípusa",
  "Desciption font": "Leírás betűtípus",
  "Section font": "Betűkészlet szakasz",
  "Section divider color": "Szakaszelválasztó színe",
  "Add event": "Esemény hozzáadása",
  "Choose a category": "Válasszon kategóriát",
  "Venue name": "Helyszín neve",
  "Venue phone": "Helyszín telefon",
  "Venue email": "Helyszín e-mail",
  "Venue website": "Helyszín helyszíne",
  "Personal info": "Személyes adatok",
  "First name": "Keresztnév",
  "Last name": "Vezetéknév",
  "Email Address": "Email cím",
  "Additional Notes": "További megjegyzések",
  Back: "Vissza",
  Save: "Megment",
  "Your event has been submitted": "Az esemény beküldve",
  "Event submittion has been failed": "Az esemény beküldése nem sikerült",
  "First Name": "Keresztnév",
  "Last Name": "Vezetéknév",
  "Phone Number": "Telefonszám",
  Address: "Cím",
  "Your comments": "Az Ön észrevételei",
  "How many guests?": "Hány vendég?",
  "Anything else we need to know?": "Van még valami, amit tudnunk kell?",
  "Guests:": "Vendégek:",
  Submit: "Beküldés",
  "Go to Calendar": "Nyissa meg a Naptár lehetőséget",
  "Registration completed successfully!":
    "A regisztráció sikeresen befejeződött!",
  "Please check your registered email address":
    "Kérjük, ellenőrizze regisztrált e-mail címét",
  "Add to Calendar": "Hozzáadás a naptárhoz",
  "Share this Event": "Ossza meg ezt az eseményt",
  "Sorry something went wrong": "Elnézést, valami nem ment jól",
  "Back to registration": "Vissza a regisztrációhoz",
  "Date & Location": "Dátum és hely",
  "Date & Time": "Dátum idő",
  home: "itthon",
  "Header align": "Fejléc igazítása",
  Footer: "Lábléc",
  "Categories Filter": "kategóriák Szűrés",
  "Show only upcoming": "Csak a közelgő megjelenítése",
  "Card(s) in a row": "Kártya (k) egymás után",
  "Space between cards": "Hely a kártyák között",
  "Shown events limit": "A megjelenített események korlátozása",
  "Style 1": "1. stílus",
  "Style 2": "2. stílus",
  "Style 3": "3. stílus",
  "Style 4": "4. stílus",
  "Buttons & Links": "Gombok és linkek",
  "Button corner radius": "Gomb sarok sugara",
  "Buttons font": "Gombok betűtípusa",
  "Buttons background": "Gombok háttér",
  "Get notified by Email": "Értesítést kap e-mailben",
  "Review events": "Tekintse át az eseményeket",
  "Click on date": "Kattintson a dátumra",
  "Add Event button": "Esemény gomb hozzáadása",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "A Naptár szinkronizálása lehetővé teszi az események és munkamenetek integrálását a Boom Naptárral.",
  connect: "csatlakozzon",
  "Synchronized Calendars": "Szinkronizált naptárak",
  "Import events": "Események importálása",
  Disconnect: "Kapcsolat bontása",
  "Choose calendar": "Válasszon naptárt",
  "Monitor your Wix events through the sync feature":
    "Figyelje a Wix eseményeit a szinkronizálási szolgáltatáson keresztül",
  "Connect all your Boom calendars available on your website":
    "Csatlakoztassa az összes webhelyén elérhető Boom-naptárt",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Ütemezzen, csatlakozzon és kezelje a Zoom értekezleteket közvetlenül a Boom naptárunkon keresztül.",
  "Monitor your Event Brite events through the Event Brite sync feature":
    "Figyelje az Event Brite eseményeit az Event Brite szinkronizálási szolgáltatásán keresztül",
  Email: "Email",
  "Add-ons": "Kiegészítők",
  "Receive notification emails as soon as users add events to your calendar.":
    "Értesítési e-maileket kapunk, amint a felhasználók eseményeket adnak a naptárhoz.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Elfogadja vagy csökkentse az ügyfelek által hozzáadott eseményeket, mielőtt nyilvánosságra hozná őket.",
  "Switch Add Event": "Kapcsoló hozzáadása esemény",
  "Enable your browser cookies to connect to your account.":
    "Engedélyezze a böngésző cookie-kat, hogy csatlakozzon fiókjához.",
  "Learn more": "Tudj meg többet",
  "Print Button": "Nyomtatás gomb",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Engedélyezze a felhasználók számára, hogy bármilyen dátumtartományban nyomtassák a Boom eseménynaptárát.",
  "Show Title on mobile": "A cím megjelenítése a mobilon",
  "Show Skeleton on mobile": "A csontváz megjelenítése a mobilon",
  "Start 7-day Business trial": "Indítsa el a 7 napos üzleti tárgyalást",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Élvezze az összes korlátlan funkciót, például jegyeket, regisztrációt, látogató esemény-kiegészítőket.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Kérjük, vegye figyelembe: A próbaidőszak végén visszaküldjük a meglévő előfizetési tervét.",
  "Not Now": "Nem most",
  "Start free trial": "Ingyenes próba indítása",
  "Congrats!": "Gratula!",
  "Your 7-day Business trial has been successfully activated.":
    "A 7 napos üzleti tárgyalás sikeresen aktiválódott.",
  Done: "Kész",
  "Title font color": "Cím betűtípus színe",
  "Desciption font color": "Leírás Font Szín",
  "Section font color": "Szakasz betűtípus színe",
  "Card Header": "Kártya fejléc",
  Category: "Kategória",
  "Display at the": "Megjelenik a",
  top: "top",
  bottom: "alsó",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Mutassa be a kategória-szűrőt a naptár tetején vagy alján.A beállítások csak napirendre és kártyára vonatkoznak",
  "Processing your events": "Az események feldolgozása",
  "Search for events": "Események keresése",
  "There are no events added": "Nincsenek események hozzáadva",
  "Location: To be determined": "Helyszín: Meg kell határozni",
  "No events for selected date": "Nincsenek események a kiválasztott dátumra",
  Uncategorized: "Nem kategorizálatlan",
  "Edit event": "Esemény szerkesztése",
  "Edit original event": "Eredeti esemény szerkesztése",
  "Copy event": "Másolási esemény",
  "Copy as new event": "Másoljon új eseményként",
  "Delete event": "Esemény törlése",
  "Stop repeating on this date": "Hagyd abba az ismétlést ezen a dátumon",
  "Exclude this date": "Kivéve ezt a dátumot",
  "Fill your personal information": "Töltse ki személyes adatait",
  "Check Box": "Jelölőnégyzet",
  "Single Choice": "Egyetlen választás",
  Option: "választási lehetőség",
  "Share Event": "Megosztási esemény",
  "Oops! Something went wrong": "Hoppá!Valami elromlott",
  "We are sorry this event has already taken place":
    "Sajnáljuk, hogy ez az esemény már megtörtént",
  "Back to calendar": "Vissza a naptárhoz",
  "This field is required": "Ez a mező kötelező",
  Phone: "Telefon",
  "Number field": "Számmező",
  "Please provide a valid email": "Kérjük, adjon meg érvényes e -mailt",
  "Select at least one option": "Válasszon legalább egy lehetőséget",
  "Choose tickets to see total value":
    "Válassza a Jegyeket a teljes érték megtekintéséhez",
  tickets: "jegyek",
  "Choose Tickets": "Válassza a Jegyeket",
  "Choose payment method": "Válassz fizetési módot",
  Pay: "Fizetés",
  Total: "Teljes",
  Free: "Ingyenes",
  "Buy tickets": "Jegyeket vesz",
  "Sold Out": "Elkelt",
  "Tickets are available": "Jegyek elérhetők",
  "Sales End": "Értékesítési cél",
  "Availible from": "elérhető ekkortól",
  "Go to Orders": "Menjen a megrendelésekre",
  "Go to Details": "Lépjen a részletekre",
  "Group ticket": "Csoportjegy",
  Name: "Név",
  Price: "Ár",
  "Order by": "Rendezés",
  "Order ID": "Rendelés azonosító",
  Applied: "Alkalmazott",
  Fees: "Díj",
  "Enter promo code": "Írja be a promóciós kódot",
  Apply: "Alkalmaz",
  "Promo Code": "Promóciós kód",
  Cash: "Készpénz",
  "You can find your e-tickets attached to your email or download them":
    "Megtalálhatja az e-mailhez csatolt e-jegyeket, vagy letöltheti azokat",
  here: "itt",
  Time: "Idő",
  "Invalid promo code": "Érvénytelen promóciós kód",
  "Credit card": "Hitelkártya",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Hamarosan megerősítő üzenetet kap a sikeres regisztrációról az e -mail címére.",
  "You can also check your order details below.":
    "Az alábbiakban ellenőrizheti a megrendelés részleteit is.",
  at: "nál nél",
  Buy: "megvesz",
  Donation: "Adomány",
  "Enter price": "Vállalkozás",
  Choose: "Választ",
  Chosen: "Választott",
  "Choose your plan": "Válassza ki a tervét",
  week: "hét",
  wk: "hét",
  "Choose plan cycle": "Válassza a Planciklus lehetőséget",
  months: "hónapok",
  years: "évek",
  weeks: "hetek",
  "Copy Event Url": "Másolja az esemény URL -jét",
  "You can find your e-tickets attached to your email or print them":
    "Megtalálhatja az e-mailhez csatolt e-jegyeket, vagy kinyomtathatja azokat",
  "Guest Info": "Vendéginformáció",
  "Ticket Info": "Jegyinformáció",
  "Ticket name": "Jegynév",
  "Ticket price": "Jegyár",
  "Ticket ID": "Jegy -azonosító",
  "If you have any questions contact to organizer":
    "Ha bármilyen kérdése van, vegye fel a kapcsolatot a szervezővel",
  "As soon as event ends": "Amint az esemény véget ér",
  "1 day after event ends": "1 nappal az esemény vége után",
  "7 days after event ends": "7 nappal az esemény vége után",
  "14 days after event ends": "14 nappal az esemény vége után",
  "30 days after event ends": "30 nappal az esemény vége után",
  Menu: "Menü",
  "No event for selected date": "Nincs esemény a kiválasztott dátumra",
  "All day event": "Egész napos esemény",
  "Add location": "Adj hozzá helyet",
  "The field is required": "A mező szükséges",
  "Please provide a valid url": "Kérjük, adjon meg egy érvényes URL -t",
  Bold: "Bátor",
  Italic: "Dőlt betű",
  Underline: "Aláhúzás",
  Link: "Link",
  "Bulleted list": "Ábrázolt lista",
  "Numbered list": "Számozott lista",
  Website: "Weboldal",
};
export default hu;
