let it = {

  /* add event pop-up start*/
  "e.g. Birthday Party": "per esempio. Festa di compleanno",
  "Organizer": "Organizzatore",
  "Location is going to be announced": "La posizione verrà annunciata",
  "Add Event": "Aggiungi evento",
  "All Day Event": "Evento tutto il giorno",
  "Location": "Posizione",
  "General Info": "Informazioni generali",
  "Description": "Descrizione",
  "Next": "Il prossimo",
   "Make your contribution by adding your event to the calendar" : "Dai il tuo contributo aggiungendo il tuo evento al calendario",
 "Event name" : "Nome dell'evento",
 "Start time" : "Ora di inizio",
 "End time" : "Tempo scaduto",
 "Physical location" : "Luogo fisico",
 "Online" : "in linea",
 "To be announced" : "Essere annunciato",
 "Add Image" : "Aggiungi immagine",
 "Event color" : "Colore dell'evento",
 "Choose categories" : "Scegli le categorie",
 "There are no categories to select" : "Non ci sono categorie da selezionare",
 "Location name" : "Nome del luogo",
 "Location email" : "Email di posizione",
 "Location phone" : "Posizione Telefono",
 "Location website" : "Sito web di posizione",
 "Organizer name" : "Nome organizzatore",
 "Organizer phone" : "Telefono organizzatore",
 "Organizer email" : "Email dell'organizzatore",
 "Organizer website" : "Sito web dell'organizzatore",
/* add event pop-up end*/


  "Categories": "Categorie",
  "Share this event": "Condividi questo evento",
  "Language": "Linguaggio",
  "Show Time Zone": "Mostra fuso orario",
  "Custom Local Settings": "Impostazioni locali personalizzate",
  "Add and showcase events on your site using a beautiful calendar.": "Aggiungi e mostra gli eventi sul tuo sito utilizzando un bellissimo calendario . ",
  "Week Days": "Giorni della settimana",
  "Manage Events": "Gestisci eventi",
  "General": "Generale",
  "Layout Picker": "Selettore layout",
  "Month": "Mese",
  "Monthly": "Mensile",
  "Week": "Settimana",
  "Weekly": "Settimanalmente",
  "Day": "Giorno",
  "Daily": "Quotidiano",
  "Agenda": "Agenda",
  "Navigation Buttons": "Pulsanti di navigazione",
  "Week numbers": "Numeri settimanali",
  "Include Weekends": "Includi fine settimana",
  "All-day": "Tutto il giorno",
  "All Day": "Tutto il giorno",
  "Label": "Etichetta",
  "Fit to Height": "Adatta all'altezza",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Per impostare proporzioni app disabilita manualmente questa opzione e ridimensiona il calendario in Editor. ",
  "Default Layout": "Layout predefinito",
  "Monthly view": "Vista mensile",
  "Weekly and Daily view": "Vista settimanale e giornaliera",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Puoi offrire ai visitatori un'esperienza più coerente mostrando lo stesso numero di settimane ( 6) alla volta.",
  "Fixed Weekly Layout": "Layout settimanale fisso",
  "back": "indietro",
  "Row": "Riga",
  "Hours in Weekly View": "Ore nella vista settimanale",
  "Hours in Daily View": "Ore nella vista giornaliera",
  "Start": "Inizio",
  "End": "Fine",
  "At This Hour": "A quest'ora",
  "Button": "Pulsante",
  "Buttons": "Pulsanti",
  "Sunday": "Domenica",
  "Monday": "Lunedi",
  "Tuesday": "Martedì",
  "Wednesday": "Mercoledì",
  "Thursday": " Giovedì ",
  "Friday": "Venerdì",
  "Saturday": "Sabato",
  "Default Date": "Data predefinita",
  "year": " anno ",
  "month": " mese ",
  "mo": " mese ",
  "days": " giorni ",
  "ago": " ago ",
  "ahead": " avanti ",
  "Yesterday": "Ieri",
  "Today": "Oggi",
  "Tomorrow": "Domani",
  "Custom": "Custom",
  "Set Daily Rows Limit": "Imposta limite righe giornaliere",
  "Set Proportions": "Imposta proporzioni",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Consenti al visitatore di aggiungere un evento ai Calnedars locali , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Contenitore",
  "Background": "Sfondo",
  "Container Background": "Sfondo contenitore",
  "Container Borders": "Confini del contenitore",
  "Calendar": "Calendario",
  "Event Info Tooltip": "Descrizione info evento",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Quando le persone passano il mouse sopra un evento vedranno tutte le informazioni a riguardo in una descrizione comandi. ",
  "Event Info Window": "Finestra informazioni evento",
  "This is the full information window that opens when someone clicks on the event.": "Questa è la finestra con le informazioni complete che si apre quando qualcuno fa clic sull'evento. ",
  "Use Gradient": "Usa sfumatura",
  "Vertical": "Verticale",
  "Horizontal": "Orizzontale",
  "First": "Primo",
  "Second": "Secondo",
  "diagonal": " diagonale ",
  "Radial": "Radiale",
  "Select option": "Selezionare l'opzione",
  "Solid": "Solido",
  "Dotted": "Tratteggiata",
  "Dashed": "Tratteggiata",
  "Double": "Doppio",
  "Border Radius": "Raggio di confine",
  "Padding": "Imbottitura",
  "Date Header": "Intestazione data",
  "Event Default Color": "Colore predefinito evento",
  "Days of Week": "Giorni della settimana",
  "Days of Week Background": "Sfondo giorni della settimana",
  "Date": "Data",
  "Event Title": "Titolo evento",
  "Highlight today": "Evidenzia oggi",
  "Highlight Color": "Evidenzia colore",
  "Hide": "Nascondere",
  "Calendar Border Color": "Colore bordo calendario",
  "Calendar Border Width": "Larghezza bordo calendario",
  "Calendar Border Style": "Stile bordo calendario",
  "Font Color": "Colore del carattere",
  "Event Background": "Sfondo dell'evento",
  "Card Date Color": "Colore data carta",
  "Title Font": "Carattere del titolo",
  "Date Font": "Carattere data",
  "Description Font": "Carattere descrizione",
  "Button Background": "Sfondo pulsante",
  "Button Text": "Testo pulsante",
  "Border Color": "Colore del bordo",
  "Border Width": "Larghezza del bordo",
  "Border Type": "Tipo di bordo",
  "Title": "Titolo",
  "Background Color": "Colore di sfondo",
  "Divider": "Divisore",
  "Event Details Font": "Carattere dettagli evento",
  "Website Link Color": "Colore link sito Web",
  "Developer Info": "Informazioni sviluppatore",
  "User Guide": "Guida utente",
  "Support e-mail": "Supporto e-mail",
  "Our Website": "Il nostro sito web",
  "App Review": "Revisione app",
  "Enjoying App? Leave us a review in the App Market.": "Ti piace l'app? Lasciaci una recensione nel mercato delle app. ",
  "Review Us": "Revisionaci",
  "Connect With Us": "Mettiti in comunicazione con noi",
  "What's your email?": "Qual è la tua email? ",
  "Invalid email address!": "Indirizzo email non valido! ",
  "Comments": "Commenti",
  "We'd love to hear from you. Send us a message.": "Ci piacerebbe avere tue notizie. Inviaci un messaggio. ",
  "Message must be at least 5 characters long": "Il messaggio deve contenere almeno 5 caratteri",
  "Send": "Inviare",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Se si desidera consentire all'utente di alternare le visualizzazioni del calendario, abilitare questa opzione e scegliere le visualizzazioni che si desidera mostrare. ",
  "Main": "Principale",
  "Localize": "Localizzare",
  "Settings": "Impostazioni",
  "Layouts": "Disposizione",
  "Advanced": "Avanzati",
  "Design": "Disegno",
  "Support": "Supporto",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Tutte le impostazioni locali sono (automaticamente) in base alla tua lingua. Se la tua lingua è nell'elenco, non è necessario personalizzare questa sezione.",
  "Date Format": "Formato data",
  "Time Format": "Formato orario",
  "Text Direction": "Direzione del testo",
  "Left to Right": "Da sinistra a destra",
  "Right to Left": "Da destra a sinistra",
  "Week Starts On": "La settimana inizia",
  "Agenda Style": "Stile agenda",
  "Classic": "Classico",
  "Modern": "Moderno",
  "Agenda Header": "Intestazione agenda",
  "Upcoming Events": "Prossimi eventi",
  "Agenda Event Limit": "Limite evento agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Esegui l'upgrade ora e ottieni molte più funzioni e goditi appieno la tua APP!",
  "Upgrade Now": "Aggiorna ora",
  "Hosting events that last all day? This lets you show them on your calendar.": "Ospitare eventi che durano tutto il giorno? Questo ti consente di mostrarli sul tuo calendario.",
  "24 hours": "24 ore",
  "Sat": "Sab",
  "Sun": "Dom",
  "Mon": "Lun",
  "Default": "Predefinito",
  "Select custom design style for your calendar.": "Seleziona uno stile di design personalizzato per il tuo calendario.",
  "Style": "Stile",
  "Styles and Colors": "Stili e colori",
  "Calendar Name": "Nome del calendario",
  "Write your Calendar name here": "Scrivi qui il nome del tuo calendario",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Questo non è visibile ai tuoi utenti. Imposta i nomi per differenziare i tuoi calendari quando usi la funzione Sincronizzazione Boom Calendar.",
  "Venue": "sede",
  "Search": "Ricerca",
  "Add to": "Aggiungere a",
  "calendar": "calendario",
  "Copy event URL": "Copia l'URL dell'evento",
  "Copied!": "Copiato!",
  "Add & Share": "Aggiungi e condividi",
  "Map": "Carta geografica",
  "Calendar view": "Visualizzazione calendario",
  "Uncategorised": "Non categorizzato",
  "More": "Di Più",
  "Less": "Di meno",
  "Register": "Registrati",
  "Card": "Carta",

  "Guests": "Ospiti",
  "unlimited": "illimitato",
  "Show more": "Mostra di più",
  "Enable Search": "Abilita ricerca",
  "+ Add Event": "+ Aggiungi evento",
  "Manage and Sync": "Gestisci e sincronizza",
  "Show event details as...": "Mostra i dettagli dell'evento come ...",
  "Tooltip": "tooltip",
  "Popup": "Info box",
  "None": "Nessuna",
  "Show Category": "Mostra categoria",
  "Header Align": "Allinea intestazione",
  "Show Time": "Orario dello spettacolo",
  "Hours in Weekly/Daily View": "Ore in Vista settimanale / giornaliera",
  "Share Events": "Condividi eventi",
  "Shadow": "Ombra",
  "Inner Padding": "Imbottitura interna",
  "Text": "Testo",
  "Active Button Border": "Bordo pulsante attivo",
  "Light Mode": "Modalità luce",
  "Event Text Color": "Colore del testo dell'evento",
  "Dates": "Date",
  "Skeleton": "Scheletro",
  "Skeleton Color": "Colore scheletro",
  "Width": "Larghezza",
  "Skeleton Style": "Stile scheletro",
  "Color": "Colore",
  "Section Titles": "Titoli di sezione",
  "Section Content": "Contenuto della sezione",
  "Header": "Intestazione",
  "Standard": "Standard",
  "Retro": "Retrò",
  "Silver": "Argento",
  "Night": "Notte",
  "Dark": "Buio",
  "Aubergine": "Melanzana",
  "Map Header": "Intestazione della mappa",
  "Show Title in mobile": "Mostra il titolo sul cellulare",
  "Card View": "Visualizzazione scheda",
  "Card background color": "Colore di sfondo della carta",
  "Title font": "Carattere del titolo",
  "Desciption font": "Carattere descrizione",
  "Section font": "Sezione dei caratteri",
  "Section divider color": "Colore divisore di sezione",
  "Add event": "Aggiungi evento",
  "Choose a category": "Scegli una categoria",
  "Venue name": "Nome sede",
  "Venue phone": "Telefono sede",
  "Venue email": "Email sede",
  "Venue website": "Sito web della sede",
  "Personal info": "Informazioni personali",
  "First name": "Nome di battesimo",
  "Last name": "Cognome",
  "Email Address": "Indirizzo email",
  "Additional Notes": "Note aggiuntive",
  "Back": "Indietro",
  "Save": "Salva",
  "Your event has been submitted": "Il tuo evento è stato inviato",
  "Event submittion has been failed": "\tLinvio dellevento non è riuscito",
  "First Name": "Nome di battesimo",
  "Last Name": "Cognome",
  "Phone Number": "Numero di telefono",
  "Address": "Indirizzo",
  "Your comments": "I tuoi commenti",
  "How many guests?": "Quanti ospiti?",
  "Anything else we need to know?": "C'è qualcos'altro che dobbiamo sapere?",
  "Guests:": "Ospiti:",
  "Submit": "Invia",
  "Go to Calendar": "Vai al calendario",
  "Registration completed successfully!": "Registrazione completata con successo!",
  "Please check your registered email address": "Per favore controlla il tuo indirizzo email registrato",
  "Add to Calendar": "Aggiungi al calendario",
  "Share this Event": "Condividi questo evento",
  "Sorry something went wrong": "מצטערים, משהו השתבש",
  "Back to registration": "Torna alla registrazione",
  "Date & Location": "Data e posizione",
  "Date & Time": "Appuntamento",
  "home": "casa",
  "Header align": "Allineamento intestazione",
  "Footer": "Piè di pagina",
  "Categories Filter": "Filtro categorie",
  "Show only upcoming": "Mostra solo in arrivo",
  "Card(s) in a row": "Carta / e di fila",
  "Space between cards": "Spazio tra le carte",
  "Shown events limit": "Limite eventi mostrato",
  "Style 1": "Stile 1",
  "Style 2": "Stile 2.",
  "Style 3": "Stile 3",
  "Style 4": "Stile 4",
  "Buttons & Links": "Pulsanti e collegamenti",
  "Button corner radius": "Raggio dell'angolo del pulsante",
  "Buttons font": "Carattere dei pulsanti",
  "Buttons background": "Sfondo di pulsanti",
  "Get notified by Email": "Ricevi una notifica tramite e-mail",
  "Review events": "Rivedi gli eventi",
  "Click on date": "Fare clic sulla data",
  "Add Event button": "Pulsante Aggiungi evento",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Calendar Sync ti consente di integrare i tuoi eventi e le tue sessioni con il tuo calendario BOOM.",
  "connect": "Collegare",
  "Synchronized Calendars": "Calendari sincronizzati",
  "Import events": "Importa eventi",
  "Disconnect": "Disconnetti",
  "Choose calendar": "Scegli il calendario",
  "Monitor your Wix events through the sync feature": "Monitora i tuoi eventi Wix attraverso la funzione di sincronizzazione",
  "Connect all your Boom calendars available on your website": "Collega tutti i tuoi calendari Boom disponibili sul tuo sito web",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Pianifica, partecipa e gestisci le riunioni Zoom direttamente tramite il nostro calendario Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Monitora i tuoi eventi Event Brite tramite la funzione di sincronizzazione Event Brite",
  "Email": "E-mail",
  "Add-ons": "Componenti aggiuntivi",
  "Receive notification emails as soon as users add events to your calendar.": "Ricevere e-mail di notifica non appena gli utenti aggiungono eventi al tuo calendario.",
  "Enable + button on the calendar header": "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.": "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Switch Aggiungi evento",
  "Enable your browser cookies to connect to your account.": "Abilita i cookie del browser di connettersi al tuo account.",
  "Learn more": "Per saperne di più",
  "Print Button": "印刷ボタン",
  "Permit your users to print your Boom Event Calendar in any date range.": "Permetti ai tuoi utenti di stampare il calendario degli eventi BOOM in qualsiasi intervallo di date.",
  "Show Title on mobile": "Mostra titolo su Mobile",
  "Show Skeleton on mobile": "Mostra scheletro sul cellulare",
  "Start 7-day Business trial": "Inizia il tuo processo aziendale di 7 giorni",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Goditi tutte le funzionalità illimitate, come il biglietto di vendita, la registrazione, i componenti aggiuntivi degli eventi dei visitatori.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Nota: alla fine del periodo di prova, verrà restituito al piano di abbonamento esistente.",
  "Not Now": "Non adesso",
  "Start free trial": "Inizia la prova gratuita",
  "Congrats!": "Congratulazioni!",
  "Your 7-day Business trial has been successfully activated.": "Il tuo processo aziendale di 7 giorni è stato attivato con successo.",
  "Done": "Fatto",
  "Title font color": "Titolo del carattere Color.",
  "Desciption font color": "Descrizione Font Color.",
  "Section font color": "Sezione Carattere Colore",
  "Card Header": "Intestazione della carta",
  "Category": "Categoria",
  "Display at the": "Mostra al",
  "top": "superiore",
  "bottom": "parte inferiore",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Mostra il filtro della categoria in alto o nella parte inferiore del calendario.Le impostazioni si applicano solo all'agenda e alle viste delle carte",
  "Processing your events": "Elaborare i tuoi eventi",
  "Search for events": "Cerca eventi",
  "There are no events added": "Non ci sono eventi aggiunti",
  "Location: To be determined": "Posizione: da determinare",
  "No events for selected date": "Nessun evento per data selezionata",
  "Uncategorized": "Non categorizzato",
  "Edit event": "Modifica evento",
  "Edit original event": "Modifica evento originale",
  "Copy event": "Copia evento",
  "Copy as new event": "Copia come nuovo evento",
  "Delete event": "Elimina evento",
  "Stop repeating on this date": "Smetti di ripetere in questa data",
  "Exclude this date": "Escludere questa data",
  "Fill your personal information": "Riempi le tue informazioni personali",
  "Check Box": "Casella di controllo",
  "Single Choice": "Scelta singola",
  "Option": "Opzione",
  "Share Event": "Evento di condivisione",
  "Oops! Something went wrong": "Oops!Qualcosa è andato storto",
  "We are sorry this event has already taken place": "Ci dispiace che questo evento abbia già avuto luogo",
  "Back to calendar": "Torna al calendario",
  "This field is required": "Questo campo è obbligatorio",
  "Phone": "Telefono",
  "Number field": "Campo numerico",
 "Please provide a valid email" : "Per favore inserisci un'email valida",
 "Select at least one option" : "Seleziona almeno un'opzione",
 "Sold Out" : "Venduto",
 "Tickets are available" : "I biglietti sono disponibili",
 "Sales End" : "Fine delle vendite",
 "Buy tickets" : "Comprare biglietti",
 "Availible from" : "Disponibile dal",
 "Go to Orders" : "Vai agli ordini",
 "Go to Details" : "Vai ai dettagli",
 "Group ticket" : "Biglietto di gruppo",
 "Name" : "Nome",
 "Price" : "Prezzo",
 "Order by" : "Ordinato da",
 "Order ID" : "ID ordine",
 "Applied": "Applicato",
 "Fees" : "Commissioni",
 "Enter promo code" : "Immettere il codice promozionale",
 "Apply" : "Applicare",
 "Promo Code" : "Codice promozionale",
 "Cash" : "Contanti",
 "You can find your e-tickets attached to your email or download them" : "Puoi trovare i tuoi biglietti elettronici allegati alla tua e-mail o scaricarli",
 "here" : "qui",
 "Time" : "Volta",
 "Invalid promo code" : "Codice promozionale non valido",
 "Credit card" : "Carta di credito",
 "You will soon receive a confirmation message of successful registration to your email address." : "Presto riceverai un messaggio di conferma della registrazione riuscita al tuo indirizzo email.",
 "You can also check your order details below." : "Di seguito puoi anche controllare i dettagli dell'ordine.",
 "at" : "a",
 "Buy" : "Acquistare",
 "Donation" : "Donazione",
 "Enter price" : "Impresa",
 "Choose" : "Scegliere",
 "Chosen" : "Scelto",
 "Choose your plan" : "Scegli il tuo piano",
  "week": "settimana",
  "wk": "settimana",
 "Choose plan cycle" : "Scegli il ciclo del piano",
 "months" : "mesi",
 "years" : "anni",
 "weeks" : "settimane",
 "Copy Event Url" : "Copia URL evento",
 "You can find your e-tickets attached to your email or print them" : "Puoi trovare i tuoi biglietti elettronici allegati alla tua e-mail o stamparli",
 "Guest Info" : "Informazioni per gli ospiti",
 "Ticket Info" : "Informazioni sul biglietto",
 "Ticket name" : "Nome del biglietto",
 "Ticket price" : "Prezzo del biglietto",
 "Ticket ID" : "Ticket ID",
 "If you have any questions contact to organizer" : "Se hai domande contatta per l'organizzatore",
 "As soon as event ends" : "Non appena l'evento termina",
 "1 day after event ends" : "1 giorno dopo la fine dell'evento",
 "7 days after event ends" : "7 giorni dopo la fine dell'evento",
 "14 days after event ends" : "14 giorni dopo la fine dell'evento",
 "30 days after event ends" : "30 giorni dopo la fine dell'evento",
 "Menu" : "Menù",
 "No event for selected date" : "Nessun evento per la data selezionata",
 "All day event" : "Evento per tutto il giorno",
 "Add location" : "Aggiungi luogo",
 "The field is required" : "Il campo è richiesto",
 "Please provide a valid url" : "Si prega di fornire un URL valido",
 "Add meeting link" : "Aggiungi il link di incontro"
}
export default it