let ja = {
  /* add event pop-up start*/
  "e.g. Birthday Party": "例えば。 誕生日会",
  Organizer: "主催者",
  "Location is going to be announced": "場所が発表されます",
  "Add Event": "イベントを追加",
  "All Day Event": "終日イベント",
  Location: "ロケーション",
  "General Info": "一般的な情報",
  Description: "「説明」",
  Next: "次",
  "Make your contribution by adding your event to the calendar":
    "カレンダーにイベントを追加して貢献してください",
  "Event name": "イベント名",
  "Start time": "始まる時間",
  "End time": "終了時間",
  "Physical location": "物理的な位置",
  Online: "オンライン",
  "To be announced": "発表される",
  "Add Image": "画像を追加",
  "Event color": "イベントカラー",
  "Choose categories": "カテゴリを選択します",
  "There are no categories to select": "選択するカテゴリはありません",
  "Location name": "場所の名前",
  "Location email": "ロケーションメール",
  "Location phone": "ロケーション電話",
  "Location website": "場所のウェブサイト",
  "Organizer name": "オーガナイザー名",
  "Organizer phone": "オーガナイザー電話",
  "Organizer email": "オーガナイザーメール",
  "Organizer website": "主催者のウェブサイト",
  "Add meeting link": "会議リンクを追加します",
  "Choose category": "カテゴリを選択します",
  Cancel: "キャンセル",
  Publish: "公開",
  /* add event pop-up end*/

  Categories: "カテゴリ",
  "Share this event": "このイベントを共有する",
  Language: "言語",
  "Show Time Zone": "タイムゾーンを表示",
  "Custom Local Settings": "カスタムローカル設定",
  "Add and showcase events on your site using a beautiful calendar.":
    "美しいカレンダーを使ってあなたのサイトにイベントを追加して展示する。",
  "Week Days": "平日",
  "Manage Events": "イベント管理",
  General: "一般",
  "Layout Picker": "レイアウトピッカー",
  Month: "月",
  Monthly: "毎月",
  Week: "週間",
  Weekly: "毎週",
  Day: "日",
  Daily: "毎日",
  Agenda: "アジェンダ",
  "Navigation Buttons": "ナビゲーションボタン",
  "Week numbers": "週番号",
  "Include Weekends": "週末を含める",
  "All-day": "一日中",
  "All Day": "一日中",
  Label: "ラベル",
  "Fit to Height": "「高さに合わせる」",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "「アプリのプロポーションを設定するには、このオプションを手動で無効にして、エディタのカレンダーのサイズを変更します。」",
  "Default Layout": "デフォルトレイアウト",
  "Monthly view": "月別ビュー",
  "Weekly and Daily view": "週次と日次の表示",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "「一度に同じ週数（6）を表示することで、訪問者により一貫したエクスペリエンスを提供できます。」",
  "Fixed Weekly Layout": "毎週の固定レイアウト",
  back: " 戻る",
  Row: "行",
  "Hours in Weekly View": "週間ビューの時間",
  "Hours in Daily View": "デイリービューの時間",
  Start: "開始",
  End: "終わり",
  "At This Hour": "「この時」",
  Button: "ボタン",
  Buttons: "ボタン",
  Sunday: "日曜日",
  Monday: "月曜",
  Tuesday: "火曜日",
  Wednesday: "水曜日",
  Thursday: " 木曜日",
  Friday: "金曜日",
  Saturday: "土曜日",
  "Default Date": "デフォルトの日付",
  year: " 年",
  month: " 月",
  mo: " 月",
  days: " 日数",
  ago: " 前",
  ahead: " 先",
  Yesterday: "昨日",
  Today: "今日",
  Tomorrow: "明日",
  Custom: "カスタム",
  "Set Daily Rows Limit": "1日の行数の上限を設定",
  "Set Proportions": "「比率の設定」",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "訪問者が地元のCalnedarsにイベントを追加することを許可する,Google、Yahoo、Outlook、ICalendar 。",
  Container: "容器",
  Background: "バックグラウンド",
  "Container Background": "コンテナの背景",
  "Container Borders": "コンテナの枠線",
  Calendar: "カレンダー",
  "Event Info Tooltip": "イベント情報ツールチップ",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "「イベントにカーソルを合わせると、ツールチップにそのイベントに関するすべての情報が表示されます。」",
  "Event Info Window": "イベント情報ウィンドウ",
  "This is the full information window that opens when someone clicks on the event.":
    "「これは、誰かがイベントをクリックしたときに開く完全な情報ウィンドウです。」",
  "Use Gradient": "「グラデーションを使う」",
  Vertical: "垂直",
  Horizontal: "水平",
  First: "最初",
  Second: "「セカンド」",
  diagonal: " 対角線",
  Radial: "ラジアル",
  "Select option": "オプションを選択",
  Solid: "固体",
  Dotted: "点在",
  Dashed: "ダッシュ",
  Double: "ダブル",
  "Border Radius": "ボーダー半径",
  Padding: "パディング",
  "Date Header": "日付ヘッダ",
  "Event Default Color": "イベントデフォルトカラー",
  "Days of Week": "曜日",
  "Days of Week Background": "曜日の経歴",
  Date: "日付",
  "Event Title": "「イベントタイトル」",
  "Highlight today": "今日のハイライト",
  "Highlight Color": "ハイライトカラー",
  Hide: "隠す",
  "Calendar Border Color": "カレンダー枠の色",
  "Calendar Border Width": "カレンダー枠の幅",
  "Calendar Border Style": "「カレンダー枠スタイル」",
  "Font Color": "フォントの��",
  "Event Background": "「イベントの背景」",
  "Card Date Color": "「カード日付の色」",
  "Title Font": "タイトルフォント",
  "Date Font": "日付フォント",
  "Description Font": "説明フォント",
  "Button Background": "「ボタンの背景」 ",
  "Button Text": "ボタンテキスト",
  "Border Color": "ボーダの色",
  "Border Width": "枠の幅",
  "Border Type": "枠の種類",
  Title: "タイトル",
  "Background Color": "「背景色」",
  Divider: "仕切り",
  "Event Details Font": "イベント詳細フォント",
  "Website Link Color": "Webサイトのリンクの色",
  "Developer Info": "開発者情報",
  "User Guide": "ユーザーガイド",
  "Support e-mail": "サポートメール",
  "Our Website": "私たちのウェブサイト",
  "App Review": "アプリレビュー",
  "Enjoying App? Leave us a review in the App Market.":
    "Appを楽しんでいますか？App Marketでレビューを残してください。",
  "Review Us": "私達を見直しなさい",
  "Connect With Us": "「私達とつながりなさい」",
  "What's your email?": "あなたのEメールは何ですか？",
  "Invalid email address!": "無効なメールアドレスです！",
  Comments: "コメント",
  "We'd love to hear from you. Send us a message.":
    "「私たちはあなたから話を聞きたいです。私たちにメッセージを送ってください。」",
  "Message must be at least 5 characters long":
    "メッセージは5文字以上でなければなりません",
  Send: "送信",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "「ユーザーにカレンダー表示の切り替えを許可する場合は、このオプションを有効にして表示したい表示を選択してください。」",
  Main: "メイン",
  Localize: "ローカライズ",
  Settings: "設定",
  Layouts: "レイアウト",
  Advanced: "高度な",
  Design: "設計",
  Support: "サポート",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "すべてのローカル設定は（自動的に）あなたの言語に基づいています。 あなたの言語がリストに載っていれば、このセクションをカスタマイズする必要はありません。",
  "Date Format": "日付形式",
  "Time Format": "時間形式",
  "Text Direction": "テキストの方向",
  "Left to Right": "左から右へ",
  "Right to Left": "右から左へ",
  "Week Starts On": "週の始まり",
  "Agenda Style": "アジェンダスタイル",
  Classic: "クラシック",
  Modern: "モダン",
  "Agenda Header": "アジェンダヘッダー",
  "Upcoming Events": "今後のイベント",
  "Agenda Event Limit": "アジェンダイベント制限",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "今すぐアップグレードして、さらに多くの機能を入手し、APPを完全に楽しみましょう！",
  "Upgrade Now": "今すぐアップグレード",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "終日開催するイベントをホストしていますか？これにより、カレンダーにイベントを表示できます。",
  "24 hours": "24時間",
  Sun: "日曜日",
  Mon: "月曜",
  Sat: "土曜日",
  Default: "デフォルト",
  "Select custom design style for your calendar.":
    "カレンダーのカスタムデザインスタイルを選択します",
  Style: "スタイル",
  "Styles and Colors": "スタイルと色",
  "Calendar Name": "カレンダー名",
  "Write your Calendar name here": "ここにカレンダー名を書いてください",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "これはユーザーには見えません。 ブームカレンダー同期機能を使用する場合は、名前を設定してカレンダーを区別します。",
  Venue: "会場",
  Search: "探す",
  "Add to": "追加",
  calendar: "カレンダー",
  "Copy event URL": "イ��ントURLをコピー",
  "Copied!": "コピーしました！",
  "Add & Share": "追加して共有",
  Map: "地図",
  "Calendar view": "カレンダービュー",
  Uncategorised: "「未分類」",
  More: "もっと",
  Less: "もっと少なく",
  Register: "登録",
  Card: "カード",

  Guests: "ゲスト",
  unlimited: "無制限",
  "Show more": "もっと見せる",
  "Enable Search": "検索を有効にする",
  "+ Add Event": "+イベントを追加",
  "Manage and Sync": "管理と同期",
  "Show event details as...": "イベントの詳細を次のように表示...",
  Tooltip: "ツールチップ",
  Popup: "情報ボックス",
  None: "なし",
  "Show Category": "カテゴリを表示",
  "Header Align": "ヘッダー整列",
  "Show Time": "ショータイム",
  "Hours in Weekly/Daily View": "週次/日次ビューの時間",
  "Share Events": "イベントを共有する",
  Shadow: "影",
  "Inner Padding": "内部パディング",
  Text: "テキスト",
  "Active Button Border": "アクティブボタンの境界線",
  "Light Mode": "ライトモード",
  "Event Text Color": "イベントテキストの色",
  Dates: "日付",
  Skeleton: "スケルトン",
  "Skeleton Color": "スケルトンカラー",
  Width: "幅",
  "Skeleton Style": "スケルトンスタイル",
  Color: "色",
  "Section Titles": "セクションのタイトル",
  "Section Content": "セクションコンテンツ",
  Header: "ヘッダ",
  Standard: "標準",
  Retro: "レトロ",
  Silver: "銀",
  Night: "夜",
  Dark: "闇",
  Aubergine: "茄子",
  "Map Header": "マップヘッダー",
  "Show Title in mobile": "モバイルでタイトルを表示",
  "Card View": "カードビュー",
  "Card background color": "カードの背景色",
  "Title font": "タイトルフォント",
  "Desciption font": "説明フォント",
  "Section font": "フォントセクション",
  "Section divider color": "セクションディバイダーカラー",
  "Add event": "イベントを追加",
  "Choose a category": "カテゴリを選択",
  "Venue name": "会場名",
  "Venue phone": "「会場電話」",
  "Venue email": "「会場メール」",
  "Venue website": "「会場のウェブサイト」",
  "Personal info": "個人情報",
  "First name": "ファーストネーム",
  "Last name": "苗字",
  "Email Address": "電子メールアドレス",
  "Additional Notes": "その他の注意事項",
  Back: "バック",
  Save: "保存する",
  "Your event has been submitted": "「あなたのイベントは送信されました」",
  "Event submittion has been failed": "「イベントの送信に失敗しました」",
  "First Name": "ファーストネーム",
  "Last Name": "苗字",
  "Phone Number": "電話番号",
  Address: "住所",
  "Your comments": "あなたのコメント",
  "How many guests?": "ゲストは何人ですか？",
  "Anything else we need to know?": "他に知っておくべきことはありますか？",
  "Guests:": "ゲスト：",
  Submit: "参加する",
  "Go to Calendar": "カレンダーに移動",
  "Registration completed successfully!": "登録が正常に完了しました。",
  "Please check your registered email address":
    "登録したメールアドレスを確認してください",
  "Add to Calendar": "カレンダーに追加",
  "Share this Event": "このイベントを共有する",
  "Sorry something went wrong": "何かがうまくいかなかった",
  "Back to registration": "登録に戻る",
  "Date & Location": "日付と場所",
  "Date & Time": "日付時刻",
  home: "家",
  "Header align": "ヘッダー整列",
  Footer: "フッター",
  "Categories Filter": "カテゴリフィルター",
  "Show only upcoming": "今後のみ表示",
  "Card(s) in a row": "連続したカード",
  "Space between cards": "カード間のスペース",
  "Shown events limit": "表示されるイベントの制限",
  "Style 1": "スタイル1",
  "Style 2": "スタイル2",
  "Style 3": "スタイル3",
  "Style 4": "スタイル4",
  "Buttons & Links": "ボタンとリンク",
  "Button corner radius": "ボタンの角の半径",
  "Buttons font": "ボタンフォント",
  "Buttons background": "ボタンの背景",
  "Get notified by Email": "メールで通知を受け取る",
  "Review events": "イベントを確認する",
  "Click on date": "日付をクリック",
  "Add Event button": "イベントボタンを追加します",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "カレンダーの同期により、イベントとセッションをブームカレンダーと統合できます。",
  connect: "接続する",
  "Synchronized Calendars": "同期されたカレンダー",
  "Import events": "イベントのインポート",
  Disconnect: "切断する",
  "Choose calendar": "カレンダーを選択",
  "Monitor your Wix events through the sync feature":
    "同期機能を介してWixイベントを監視します",
  "Connect all your Boom calendars available on your website":
    "あなたのウェブサイトで利用可能なすべてのブームカレンダーを接続します",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "ブームカレンダーからズーム会議をスケジュール、参加、管理します。",
  "Monitor your Event Brite events through the Event Brite sync feature":
    "EventBrite同期機能を介してEventBriteイベントを監視します",
  Email: "Eメール",
  "Add-ons": "アドオン",
  "Receive notification emails as soon as users add events to your calendar.":
    "カレンダーにイベントを追加するとすぐに通知メールを受信します。",
  "Enable + button on the calendar header":
    "カレンダーヘッダーの+ボタンを有効にします",
  "Accept or decline events added by customers before making them public.":
    "公開する前に、顧客によって追加されたイベントを受け入れるか拒否する。",
  "Switch Add Event": "スイッチイベントを追加します",
  "Enable your browser cookies to connect to your account.":
    "ブラウザのクッキーをアカウントに接続できるようにします。",
  "Learn more": "もっと詳しく知る",
  "Print Button": "印刷ボタン",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "ユーザーがBOOMイベントカレンダーを印刷することを許可します。",
  "Show Title on mobile": "携帯電話でタイトルを表示",
  "Show Skeleton on mobile": "携帯電話でスケルトンを表示",
  "Start 7-day Business trial": "7日間のビジネス試験を始めてください",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "販売チケット、登録、訪問者イベントアドオンなどのすべての無制限の機能をお楽しみください。",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "ご注意：試用期間の終わりには、既存の購読計画に戻ります。",
  "Not Now": "今はやめろ",
  "Start free trial": "無料トライアルを開始",
  "Congrats!": "おめでとうございます！",
  "Your 7-day Business trial has been successfully activated.":
    "あなたの7日間のビジネス試験は成功しました。",
  Done: "終わり",
  "Title font color": "タイトルフォントカラー",
  "Desciption font color": "説明フォントカラー",
  "Section font color": "セクションフォントカラー",
  "Card Header": "カードヘッダー",
  Category: "カテゴリー",
  "Display at the": "に表示",
  top: "上",
  bottom: "下",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "カレンダーの上部またはカレンダーの下部にあるカテゴリフィルタを表示します。設定は議題とカードの閲覧のみに適用されます",
  "Processing your events": "あなたのイベントを処理する",
  "Search for events": "イベントを検索します",
  "There are no events added": "イベントが追加されていません",
  "Location: To be determined": "場所：決定するために",
  "No events for selected date": "選択日のイベントはありません",
  Uncategorized: "未分類",
  "Edit event": "編集イベント",
  "Edit original event": "元のイベントを編集します",
  "Copy event": "イベントをコピーします",
  "Copy as new event": "新しいイベントとしてコピーします",
  "Delete event": "イベントを削除します",
  "Stop repeating on this date": "この日付で繰り返すのをやめてください",
  "Exclude this date": "この日付を除外してください",
  "Fill your personal information": "あなたの個人情報を記入してください",
  "Check Box": "チェックボックス",
  "Single Choice": "単一の選択",
  Option: "オプション",
  "Share Event": "イベントを共有します",
  "Oops! Something went wrong": "おっとっと！何かがうまくいかなかった",
  "We are sorry this event has already taken place":
    "申し訳ありませんが、このイベントがすでに行われています",
  "Back to calendar": "カレンダーに戻ります",
  "This field is required": "この項目は必須です",
  Phone: "電話",
  "Number field": "数字フィールド",
  "Please provide a valid email": "有効なメールを提供してください",
  "Select at least one option": "少なくとも1つのオプションを選択します",
  "Choose tickets to see total value":
    "チケットを選択して、合計値を確認してください",
  tickets: "切符売場",
  "Choose Tickets": "チケットを選択します",
  "Choose payment method": "支払い方法を選択します",
  Pay: "支払い",
  Total: "合計",
  Free: "無料",
  "Buy tickets": "チケットを買う",
  "Sold Out": "完売",
  "Tickets are available": "チケットが利用可能です",
  "Sales End": "セールスエンド",
  "Availible from": "から入手可能",
  "Go to Orders": "注文に移動します",
  "Go to Details": "詳細に移動します",
  "Group ticket": "グループチケット",
  Name: "名前",
  Price: "価格",
  "Order by": "注文",
  "Order ID": "注文ID",
  Applied: "適用",
  Fees: "料金",
  "Enter promo code": "プロモーションコードを入力",
  Apply: "申し込み",
  "Promo Code": "プロモーションコード",
  Cash: "現金",
  "You can find your e-tickets attached to your email or download them":
    "メールに添付されている電子メールを見つけるか、ダウンロードできます",
  here: "ここ",
  Time: "時間",
  "Invalid promo code": "無効なプロモーションコード",
  "Credit card": "クレジットカード",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "すぐに、メールアドレスへの登録が成功した確認メッセージを受け取ります。",
  "You can also check your order details below.":
    "以下の注文の詳細を確認することもできます。",
  at: "で",
  Buy: "買う",
  Donation: "寄付",
  "Enter price": "企業",
  Choose: "選ぶ",
  Chosen: "選ばれた",
  "Choose your plan": "あなたの計画を選択してください",
  week: "週",
  wk: "週",
  "Choose plan cycle": "プランサイクルを選択します",
  months: "数ヶ月",
  years: "年",
  weeks: "週",
  "Copy Event Url": "イベントURLをコピーします",
  "You can find your e-tickets attached to your email or print them":
    "電子メールに添付されているeチケットを見つけるか、印刷することができます",
  "Guest Info": "ゲスト情報",
  "Ticket Info": "チケット情報",
  "Ticket name": "チケット名",
  "Ticket price": "切符の値段",
  "Ticket ID": "チケットID",
  "If you have any questions contact to organizer":
    "質問がある場合は、オーガナイザーに連絡してください",
  "As soon as event ends": "イベントが終了するとすぐに",
  "1 day after event ends": "イベントが終了してから1日後",
  "7 days after event ends": "イベントが終了してから7日後",
  "14 days after event ends": "イベントが終了してから14日後",
  "30 days after event ends": "イベントが終了してから30日後",
  Menu: "メニュー",
  "No event for selected date": "選択された日付のイベントはありません",
  "All day event": "終日イベント",
  "Add location": "場所を追加します",
  "The field is required": "フィールドが必要です",
  "Please provide a valid url": "有効なURLを提供してください",
  Bold: "ボールド",
  Italic: "イタリック",
  Underline: "下線",
  Link: "リンク",
  "Bulleted list": "箇条書きリスト",
  "Numbered list": "番号付きリスト",
  Website: "Webサイト",
};
export default ja;
