let ko = {
  "Categories": "카테고리",
  "Share this event": "이 이벤트를 공유",
  "Language": "언어",
  "Show Time Zone": "시간대 표시",
  "Custom Local Settings": "맞춤 지역 설정",
  "Add and showcase events on your site using a beautiful calendar.": "아름다운 캘린더를 사용하여 사이트의 이벤트를 추가하고 보여줍니다 . ",
  "Week Days": "주중 일",
  "Manage Events": "이벤트 관리",
  "General": "일반",
  "Layout Picker": "레이아웃 선택 도구",
  "Month": "달",
  "Monthly": "월간 간행물",
  "Week": "주",
  "Weekly": "주간",
  "Day": "일",
  "Daily": "매일",
  "Agenda": "비망록",
  "Navigation Buttons": "탐색 버튼",
  "Week numbers": "주 번호",
  "Include Weekends": "주말 포함",
  "All-day": "하루 종일",
  "All Day": "하루 종일",
  "Label": "상표",
  "Fit to Height": "높이에 맞추기",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "앱 비율을 설정하려면이 옵션을 비활성화하고 편집기에서 캘린더의 크기를 조정하십시오.",
  "Default Layout": "기본 레이아웃",
  "Monthly view": "월간보기",
  "Weekly and Daily view": "주간 및 일일보기",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "한 번에 같은 주 수 ( 6)를 표시함으로써 방문자에게보다 일관된 경험을 제공 할 수 있습니다 .",
  "Fixed Weekly Layout": "고정 주간 레이아웃",
  "back": " 뒤로 ",
  "Row": "열",
  "Hours in Weekly View": "주간보기 시간",
  "Hours in Daily View": "일일보기 시간",
  "Start": "스타트",
  "End": "종료",
  "At This Hour": "이 시간에",
  "Button": "단추",
  "Buttons": "버튼",
  "Sunday": "일요일",
  "Monday": "월요일",
  "Tuesday": "화요일",
  "Wednesday": "수요일",
  "Thursday": " 목요일 ",
  "Friday": "금요일",
  "Saturday": "토요일",
  "Default Date": "기본 날짜",
  "year": " 년 ",
  "month": " 월 ",
  "days": " 일 ",
  "ago": " 이전 ",
  "ahead": " 앞으로 ",
  "Yesterday": "어제",
  "Today": "오늘",
  "Tomorrow": "내일",
  "Custom": "관습",
  "Set Daily Rows Limit": "일일 행 제한 설정",
  "Set Proportions": "비율 설정",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "방문자가 지역 Calnedars : Google, Yahoo, Outlook, ICalendar에 이벤트를 추가 할 수 있습니다.",
  "Container": "컨테이너",
  "Background": "배경",
  "Container Background": "컨테이너 배경",
  "Container Borders": "컨테이너 테두리",
  "Calendar": "달력",
  "Event Info Tooltip": "이벤트 정보 툴팁",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "사람들이 이벤트에 마우스를 가져 가면 툴팁에 모든 정보가 표시됩니다. ",
  "Event Info Window": "이벤트 정보 창",
  "This is the full information window that opens when someone clicks on the event.": "이것은 누군가가 이벤트를 클릭하면 열리는 전체 정보 창입니다. ",
  "Use Gradient": "그라디언트 사용",
  "Vertical": "수직선",
  "Horizontal": "수평 적",
  "First": "먼저",
  "Second": "둘째",
  "diagonal": " 대각선 ",
  "Radial": "방사형",
  "Select option": "선택 옵션",
  "Solid": "고체",
  "Dotted": "점이 찍힌",
  "Dashed": "Dashed",
  "Double": "더블",
  "Border Radius": "테두리 반지름",
  "Padding": "심",
  "Date Header": "날짜 헤더",
  "Event Default Color": "이벤트 기본 색상",
  "Days of Week": "요일",
  "Days of Week Background": "요일 배경",
  "Date": "데이트",
  "Event Title": "이벤트 제목",
  "Highlight today": "오늘 하이라이트",
  "Highlight Color": "하이라이트 색상",
  "Hide": "숨는 장소",
  "Calendar Border Color": "일정 테두리 색",
  "Calendar Border Width": "일정 테두리 너비",
  "Calendar Border Style": "일정 테두리 스타일",
  "Font Color": "글꼴 색상",
  "Event Background": "이벤트 배경",
  "Card Date Color": "카드 날짜 색상",
  "Title Font": "제목 글꼴",
  "Date Font": "날짜 글꼴",
  "Description Font": "설명 글꼴",
  "Button Background": "버튼 배경",
  "Button Text": "버튼 텍스트",
  "Border Color": "테두리 색상",
  "Border Width": "테두리 너비",
  "Border Type": "테두리 유형",
  "Title": "표제",
  "Description": "기술",
  "Background Color": "배경색",
  "Divider": "분할기",
  "Event Details Font": "이벤트 세부 정보 글꼴",
  "Website Link Color": "웹 사이트 링크 색상",
  "Developer Info": "개발자 정보",
  "User Guide": "사용자 설명서",
  "Support e-mail": "지원 이메일",
  "Our Website": "우리의 웹 사이트",
  "App Review": "앱 검토",
  "Enjoying App? Leave us a review in the App Market.": "앱 즐기기? App Market에서 리뷰를 남겨주세요 . ",
  "Review Us": "검토하기",
  "Connect With Us": "우리와 접촉",
  "What's your email?": "귀하의 이메일은 무엇입니까? ",
  "Invalid email address!": "잘못된 이메일 주소입니다! ",
  "Comments": "코멘트",
  "We'd love to hear from you. Send us a message.": "우리는 당신의 의견을 듣고 싶습니다. 우리에게 메시지를 보내십시오. ",
  "Message must be at least 5 characters long": "메시지 길이는 5 자 이상이어야합니다.",
  "Send": "보내다",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "사용자가 캘린더보기간에 전환 할 수있게하려면이 옵션을 활성화하고 표시 할보기를 선택하십시오. ",
  "Main": "본관",
  "Localize": "지역화",
  "Settings": "설정",
  "Layouts": "레이아웃",
  "Advanced": "많은",
  "Design": "디자인",
  "Support": "지원하다",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "모든 로컬 설정은 사용자의 언어에 따라 (자동으로) 설정됩니다. 언어가 목록에 있으면이 섹션을 사용자 정의 할 필요가 없습니다.",
  "Date Format": "날짜 형식",
  "Time Format": "시간 형식",
  "Text Direction": "텍스트 방향",
  "Left to Right": "왼쪽에서 오른쪽으로",
  "Right to Left": "오른쪽에서 왼쪽으로",
  "Week Starts On": "주 시작",
  "Agenda Style": "아젠다 스타일",
  "Classic": "권위 있는",
  "Modern": "현대",
  "Agenda Header": "아젠다 헤더",
  "Upcoming Events": "다가오는 이벤트",
  "Agenda Event Limit": "의제 이벤트 제한",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "지금 업그레이드하고 더 많은 기능을 사용하고 APP을 완전히 즐기십시오!",
  "Upgrade Now": "지금 업그레이드",
  "Hosting events that last all day? This lets you show them on your calendar.": "하루 종일 지속되는 행사를 주최합니까? 캘린더에 표시 할 수 있습니다.",
  "24 hours": "24 시간",
  "Sat": "토요일",
  "Sun": "일요일",
  "Mon": "월요일",
  "Default": "태만",
  "Select custom design style for your calendar.": "캘린더에 대한 사용자 정의 디자인 스타일을 선택하십시오.",
  "Style": "스타일",
  "Styles and Colors": "스타일과 색상",
  "Calendar Name": "캘린더 이름",
  "Write your Calendar name here": "여기에 캘린더 이름을 작성하십시오",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "사용자에게는 보이지 않습니다. 붐 캘린더 동기화 기능을 사용할 때 캘린더를 구별 할 수 있도록 이름을 설정하십시오.",
  "General Info": "일반 정보",
  "Venue": "장소",
  "Organizer": "조직자",
  "Search": "검색",
  "Add to": "다음에 추가",
  "calendar": "달력",
  "Copy event URL": "이벤트 URL 복사",
  "Copied!": "복사했습니다!",
  "Add & Share": "추가 및 공유",
  "Map": "지도",
  "Calendar view": "달력보기",
  "Add Event": "이벤트 추가",
  "Uncategorised": "분류되지 않음",
  "More": "더",
  "Less": "적게",
  "Register": "레지스터",
  "Card": "카드",

  "Guests": "손님",
  "unlimited": "제한 없는",
  "Show more": "자세히보기",
  "Enable Search": "검색 사용",
  "+ Add Event": "+ 이벤트 추가",
  "Manage and Sync": "관리 및 동기화",
  "Show event details as...": "일정 세부 정보 표시 ...",
  "Tooltip": "툴팁",
  "Popup": "정보 상자",
  "None": "없음",
  "Show Category": "카테고리 표시",
  "Header Align": "헤더 정렬",
  "Show Time": "쇼 시간",
  "Hours in Weekly/Daily View": "주간 / 일일 시간",
  "Share Events": "이벤트 공유",
  "Shadow": "그림자",
  "Inner Padding": "내부 패딩",
  "Text": "본문",
  "Active Button Border": "활성 버튼 테두리",
  "Light Mode": "라이트 모드",
  "Event Text Color": "이벤트 텍스트 색상",
  "Dates": "날짜",
  "Skeleton": "해골",
  "Skeleton Color": "스켈레톤 컬러",
  "Width": "폭",
  "Skeleton Style": "스켈레톤 스타일",
  "Color": "색깔",
  "Section Titles": "섹션 제목",
  "Section Content": "섹션 내용",
  "Header": "헤더",
  "Standard": "표준",
  "Retro": "레트로",
  "Silver": "은",
  "Night": "밤",
  "Dark": "어두운",
  "Aubergine": "가지",
  "Map Header": "지도 헤더",
  "Show Title in mobile": "모바일에서 제목 표시",
  "Card View": "카드보기",
  "Card background color": "카드 배경색",
  "Title font": "제목 글꼴",
  "Desciption font": "설명 글꼴",
  "Section font": "글꼴 섹션",
  "Section divider color": "섹션 구분선 색상",
  "Add event": "이벤트 추가",
  "All Day Event": "하루 종일 이벤트",
  "Location": "위치",
  "Choose a category": "카테고리 선택",
  "Venue name": "장소 이름",
  "Venue phone": "회장 전화",
  "Venue email": "장소 이메일",
  "Venue website": "장소 웹 사이트",
  "Organizer name": "주최자 이름",
  "Organizer phone": "주최자 전화",
  "Organizer email": "주최자 이메일",
  "Organizer website": "주최자 웹 사이트",
  "Personal info": "개인적인 정보",
  "First name": "이름",
  "Last name": "성",
  "Email Address": "이메일 주소",
  "Additional Notes": "추가 참고 사항",
  "Back": "뒤",
  "Save": "저장",
  "Next": "다음",
  "Your event has been submitted": "이벤트가 제출되었습니다",
  "Event submittion has been failed": "이벤트 제출 실패",
  "e.g. Birthday Party": "예 : 생일 파티",
  "First Name": "이름",
  "Last Name": "성",
  "Phone Number": "전화 번호",
  "Address": "주소",
  "Your comments": "귀하의 의견",
  "How many guests?": "손님은 몇 명입니까?",
  "Anything else we need to know?": "우리가 알아야 할 다른 것이 있습니까?",
  "Guests:": "손님 :",
  "Submit": "제출",
  "Go to Calendar": "캘린더로 이동",
  "Registration completed successfully!": "등록이 성공적으로 완료되었습니다!",
  "Please check your registered email address": "등록 된 이메일 주소를 확인하세요",
  "Add to Calendar": "캘린더에 추가",
  "Share this Event": "이 이벤트를 공유",
  "Sorry something went wrong": "죄송합니다. 문제가 발생했습니다.",
  "Back to registration": "등록으로 돌아 가기",
  "Date & Location": "날짜 및 위치",
  "Date & Time": "날짜 시간",
  "home": "집",
  "Header align": "헤더 정렬",
  "Footer": "보행인",
  "Categories Filter": "카테고리 필터",
  "Show only upcoming": "예정된 항목 만 표시",
  "Card(s) in a row": "연속 된 카드",
  "Space between cards": "카드 사이의 공간",
  "Shown events limit": "표시된 이벤트 제한",
  "Style 1": "스타일 1",
  "Style 2": "스타일 2",
  "Style 3": "스타일 3",
  "Style 4": "스타일 4",
  "Buttons & Links": "버튼 및 링크",
  "Button corner radius": "버튼 모서리 반경",
  "Buttons font": "버튼 글꼴",
  "Buttons background": "버튼 배경",
  "Get notified by Email": "이메일로 통보 받으십시오",
  "Review events": "이벤트 검토",
  "Click on date": "날짜를 클릭",
  "Add Event button": "이벤트 추가 버튼",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "캘린더 동기화를 통해 이벤트 및 세션을 Boom 캘린더와 통합 할 수 있습니다.",
  "connect": "잇다",
  "Synchronized Calendars": "동기화 된 캘린더",
  "Import events": "이벤트 가져 오기",
  "Disconnect": "연결 해제",
  "Choose calendar": "달력 선택",
  "Monitor your Wix events through the sync feature": "동기화 기능을 통해 Wix 이벤트 모니터링",
  "Connect all your Boom calendars available on your website": "웹 사이트에서 사용 가능한 모든 Boom 캘린더 연결",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Boom 캘린더를 통해 Zoom 회의를 예약, 참여 및 관리하세요.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Event Brite 동기화 기능을 통해 Event Brite 이벤트 모니터링",
  "Email": "이메일",
  "Add-ons": "부가 기능",
  "Receive notification emails as soon as users add events to your calendar.": "사용자가 이벤트를 캘린더에 추가하자마자 알림 전자 메일을받습니다.",
  "Enable + button on the calendar header": "캘린더 헤더의 + 버튼을 사용합니다",
  "Accept or decline events added by customers before making them public.": "고객이 추가 한 이벤트를 수락하거나 거절합니다.",
  "Switch Add Event": "스위치 추가 이벤트",
  "Enable your browser cookies to connect to your account.": "브라우저 쿠키를 사용하여 계정에 연결할 수 있습니다.",
  "Learn more": "더 알아보기",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.": "사용자가 모든 날짜 범위에서 붐 이벤트 캘린더를 인쇄하도록 허용하십시오.",
  "Show Title on mobile": "모바일에 제목을 보여줍니다",
  "Show Skeleton on mobile": "모바일에서 스켈레톤을 보여줍니다",
  "Start 7-day Business trial": "7 일간 비즈니스 재판을 시작하십시오",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "판매 티켓, 등록, 방문자 이벤트 애드온과 같은 모든 무제한 기능을 즐기십시오.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "참고 : 평가판 기간이 끝나면 기존 가입 계획으로 돌아갑니다.",
  "Not Now": "지금은 아닙니다",
  "Start free trial": "무료 평가판을 시작하십시오",
  "Congrats!": "축하 해요!",
  "Your 7-day Business trial has been successfully activated.": "7 일 비즈니스 재판이 성공적으로 활성화되었습니다.",
  "Done": "완료",
  "Title font color": "제목 글꼴 색상",
  "Desciption font color": "설명 글꼴 색상",
  "Section font color": "섹션 글꼴 색상",
  "Card Header": "카드 헤더",
  "Category": "범주",
  "Display at the": "그대로 표시",
  "top": "맨 위",
  "bottom": "맨 아래",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "카테고리 필터를 맨 위 또는 캘린더 하단에 표시합니다.설정은 의제 및 카드 뷰에만 적용됩니다",
  "Processing your events": "이벤트 처리",
  "Search for events": "이벤트 검색",
  "There are no events added": "추가 된 이벤트가 없습니다",
  "Location: To be determined": "위치 : 결정됩니다",
  "No events for selected date": "선택한 날짜에 대한 이벤트가 없습니다",
  "Uncategorized": "분류되지 않은",
  "Edit event": "이벤트 편집",
  "Edit original event": "원본 이벤트 편집",
  "Copy event": "사본 이벤트",
  "Copy as new event": "새 이벤트로 복사하십시오",
  "Delete event": "이벤트 삭제",
  "Stop repeating on this date": "이 날짜에 반복하지 마십시오",
  "Exclude this date": "이 날짜를 제외하십시오",
  "Location is going to be announced": "위치가 발표 될 예정입니다",
  "Fill your personal information": "개인 정보를 작성하십시오",
  "Check Box": "확인란",
  "Single Choice": "단일 선택",
  "Option": "옵션",
  "Share Event": "공유 이벤트",
  "Oops! Something went wrong": "죄송합니다!뭔가 잘못되었습니다",
  "We are sorry this event has already taken place": "이 이벤트가 이미 일어난 일에 죄송합니다",
  "Back to calendar": "달력으로 돌아갑니다",
  "This field is required": "이 필드가 필요합니다",
 "Phone" : "핸드폰",
 "Number field" : "번호 필드"
}
export default ko