let lv = {
  "Categories": "Kategorijas",
  "Share this event": "Kopīgojiet šo notikumu",
  "Language": "Valoda",
  "Show Time Zone": "Rādīt laika joslu",
  "Custom Local Settings": "Pielāgoti vietējie iestatījumi",
  "Add and showcase events on your site using a beautiful calendar.": "Pievienojiet un demonstrējiet notikumus savā vietnē, izmantojot skaistu kalendāru . ",
  "Week Days": "Nedēļas dienas",
  "Manage Events": "Pārvaldīt pasākumus",
  "General": "Vispārīgi",
  "Layout Picker": "Izkārtojuma atlasītājs",
  "Month": "Mēnesis",
  "Monthly": "Mēneša",
  "Week": "Nedēļa",
  "Weekly": "Iknedēļas",
  "Day": "Diena",
  "Daily": "Katru dienu",
  "Agenda": "Darba kārtība",
  "Navigation Buttons": "Navigācijas pogas",
  "Week numbers": "Nedēļas numuri",
  "Include Weekends": "Iekļaut nedēļas nogales",
  "All-day": "Visu dienu",
  "All Day": "Visu dienu",
  "Label": "Etiķete",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Lai iestatītu lietotņu proporcijas, manuāli jāatspējo šī opcija un jāmaina kalendāra lielums redaktorā. ",
  "Default Layout": "Noklusētais izkārtojums",
  "Monthly view": "Mēneša skats",
  "Weekly and Daily view": "Nedēļas un dienas skats",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Varat sniegt apmeklētājiem konsekventāku pieredzi, parādot vienādu nedēļu skaitu ( 6) vienlaikus.",
  "Fixed Weekly Layout": "Fiksēts nedēļas izkārtojums",
  "back": " atpakaļ ",
  "Row": "Rinda",
  "Hours in Weekly View": "Stundas nedēļas skatījumā",
  "Hours in Daily View": "Stundas ikdienas skatījumā",
  "Start": "Sākt",
  "End": "Beigas",
  "At This Hour": "Šajā stundā",
  "Add to": "Pievienot",
  "Button": "Poga",
  "Buttons": "Pogas",
  "Sunday": "Svētdiena",
  "Monday": "Pirmdiena",
  "Tuesday": "Otrdiena",
  "Wednesday": "Trešdiena",
  "Thursday": " Ceturtdiena ",
  "Friday": "Piektdiena",
  "Saturday": "Sestdiena",
  "Default Date": "Noklusējuma datums",
  "year": " gads ",
  "month": " mēnesis ",
  "days": " dienas ",
  "ago": " pirms ",
  "ahead": " priekšā ",
  "Yesterday": "Vakar",
  "Today": "Šodien",
  "Tomorrow": "Rīt",
  "Custom": "Pielāgots",
  "Set Daily Rows Limit": "Iestatīt ikdienas rindu limitu",
  "Set Proportions": "Iestatīt proporcijas",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Atļaut apmeklētājam pievienot notikumu vietējiem calnedars , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Konteiners",
  "Background": "Fons",
  "Container Background": "Konteinera fons",
  "Container Borders": "Konteineru robežas",
  "Calendar": "Kalendārs",
  "Event Info Tooltip": "Pasākuma informācijas rīka padoms",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Kad cilvēki virzās virs kursora, viņi rīka padomā redzēs visu informāciju par to. ",
  "Event Info Window": "Pasākuma informācijas logs",
  "This is the full information window that opens when someone clicks on the event.": "Šis ir pilns informācijas logs, kas tiek atvērts, kad kāds noklikšķina uz notikuma. ",
  "Use Gradient": "Izmantojiet gradientu",
  "Vertical": "Vertikāls",
  "Horizontal": "Horizontāls",
  "First": "Pirmais",
  "Second": "Otrais",
  "diagonal": " pa diagonāli ",
  "Radial": "Radiāls",
  "Select option": "Atlasīt opciju",
  "Solid": "Ciets",
  "Dotted": "Punktēts",
  "Dashed": "Dashed",
  "Double": "Double",
  "Border Radius": "Robežas rādiuss",
  "Padding": "Polsterējums",
  "Date Header": "Datuma galvene",
  "Event Default Color": "Notikuma noklusējuma krāsa",
  "Days of Week": "Nedēļas dienas",
  "Days of Week Background": "Nedēļas dienu fons",
  "Date": "Datums",
  "Event Title": "Pasākuma nosaukums",
  "Highlight today": "Izcelt šodien",
  "Highlight Color": "Izcelt krāsu",
  "Hide": "Slēpt",
  "Calendar Border Color": "Kalendāra apmales krāsa",
  "Calendar Border Width": "Kalendāra robežas platums",
  "Calendar Border Style": "Kalendāra apmales stils",
  "Font Color": "Fonta krāsa",
  "Event Background": "Pasākuma fons",
  "Card Date Color": "Kartes datuma krāsa",
  "Title Font": "Nosaukuma fonts",
  "Date Font": "Datuma fonts",
  "Description Font": "Apraksts fonts",
  "Button Background": "Pogas fons",
  "Button Text": "Pogas teksts",
  "Border Color": "Apmales krāsa",
  "Border Width": "Robežas platums",
  "Border Type": "Robežas tips",
  "Title": "Virsraksts",
  "Description": "Apraksts",
  "Background Color": "Fona krāsa",
  "Divider": "Dalītājs",
  "Event Details Font": "Pasākuma detaļu fonts",
  "Website Link Color": "Vietnes saites krāsa",
  "Developer Info": "Informācija par izstrādātāju",
  "User Guide": "Lietotāja rokasgrāmata",
  "Support e-mail": "Atbalsta e-pasts",
  "Our Website": "Mūsu vietne",
  "App Review": "Lietotnes pārskats",
  "Enjoying App? Leave us a review in the App Market.": "Patīk lietotne? Atstājiet mums pārskatu App Market. ",
  "Review Us": "Pārskatiet mūs",
  "Connect With Us": "Sazinieties ar mums",
  "What's your email?": "Kāds ir jūsu e-pasts? ",
  "Invalid email address!": "Nederīga e-pasta adrese! ",
  "Comments": "Komentāri",
  "We'd love to hear from you. Send us a message.": "Mēs labprāt dzirdētu no jums. Nosūtiet mums ziņojumu. ",
  "Message must be at least 5 characters long": "Ziņojumam jābūt vismaz 5 rakstzīmju garam",
  "Send": "Sūtīt",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Ja vēlaties ļaut lietotājam pārslēgties starp kalendāra skatiem, iespējojiet šo opciju un izvēlieties skatus, kurus vēlaties parādīt. ",
  "Main": "Galvenais",
  "Localize": "Lokalizēt",
  "Settings": "Iestatījumi",
  "Layouts": "Izkārtojumi",
  "Advanced": "Uzlabots",
  "Design": "Dizains",
  "Support": "Atbalsts",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Visi vietējie iestatījumi (automātiski) ir balstīti uz jūsu valodu. Ja jūsu valoda ir sarakstā, šī sadaļa nav jāpielāgo.",
  "Date Format": "Datuma formāts",
  "Time Format": "Laika formāts",
  "Text Direction": "Teksta virziens",
  "Left to Right": "No kreisās uz labo",
  "Right to Left": "Pa labi no kreisās",
  "Week Starts On": "Nedēļa sākas",
  "Agenda Style": "Darba kārtības stils",
  "Classic": "Klasika",
  "Modern": "Mūsdienu",
  "Agenda Header": "Darba kārtības galvene",
  "Upcoming Events": "Gaidāmie notikumi",
  "Agenda Event Limit": "Darba kārtības notikumu limits",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Jauniniet tagad un iegūstiet daudz vairāk funkciju un pilnībā izbaudiet savu lietotni!",
  "Upgrade Now": "Uzlabot tagad",
  "Hosting events that last all day? This lets you show them on your calendar.": "Notikumi, kas ilgst visu dienu? Tas ļauj jums tos parādīt kalendārā.",
  "24 hours": "24 stundas",
  "Sun": "Svēt",
  "Mon": "Pirm",
  "Sat": "Sest",
  "Default": "Noklusējums",
  "Select custom design style for your calendar.": "Atlasiet sava kalendāra pielāgoto noformējuma stilu.",
  "Style": "Stils",
  "Styles and Colors": "Stili un krāsas",
  "Calendar Name": "Kalendāra nosaukums",
  "Write your Calendar name here": "Šeit ierakstiet kalendāra vārdu",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Tas jūsu lietotājiem nav redzams. Iestatiet nosaukumus, lai atšķirtu kalendārus, kad izmantojat Boom Calendar Sync funkciju.",
  "General Info": "Vispārīga informācija",
  "Venue": "Norises vieta",
  "Organizer": "Organizators",
  "Search": "Meklēt",
  "calendar": "kalendārs",
  "Copy event URL": "Kopēt notikuma URL",
  "Copied!": "Nokopēts!",
  "Add & Share": "Pievienot un kopīgot",
  "Map": "Karte",
  "Calendar view": "Kalendāra skats",
  "Add Event": "Pievienot notikumu",
  "Uncategorised": "Uncategorized",
  "More": "Vairāk",
  "Less": "Mazāk",
  "Register": "Reģistrēties",
  "Card": "Karte",
  
  "Guests": "Viesi",
  "unlimited": "neierobežots",
  "Show more": "Parādīt vairāk",
  "Enable Search": "Iespējot meklēšanu",
  "+ Add Event": "+ Pievienot notikumu",
  "Manage and Sync": "Pārvaldīt un sinhronizēt",
  "Show event details as...": "Rādīt informāciju par notikumu kā ...",
  "Tooltip": "Rīka padoms",
  "Popup": "Informācijas lodziņš",
  "None": "Nav",
  "Show Category": "Rādīt kategoriju",
  "Header Align": "Galvenes izlīdzināšana",
  "Show Time": "Laiks izrādei",
  "Hours in Weekly/Daily View": "Stundas nedēļas / dienas skatā",
  "Share Events": "Kopīgojiet pasākumus",
  "Shadow": "Ēna",
  "Inner Padding": "Iekšējais polsterējums",
  "Text": "Teksts",
  "Active Button Border": "Aktīvās pogas apmale",
  "Light Mode": "Gaismas režīms",
  "Event Text Color": "Pasākuma teksta krāsa",
  "Dates": "Datumi",
  "Skeleton": "Skelets",
  "Skeleton Color": "Skeleta krāsa",
  "Width": "Platums",
  "Skeleton Style": "Skeleta stils",
  "Color": "Krāsa",
  "Section Titles": "Sadaļu nosaukumi",
  "Section Content": "Sadaļas saturs",
  "Header": "Galvene",
  "Standard": "Standarta",
  "Retro": "Retro",
  "Silver": "Sudrabs",
  "Night": "Nakts",
  "Dark": "Tumšs",
  "Aubergine": "Baklažāni",
  "Map Header": "Kartes galvene",
  "Show Title in mobile": "Rādīt virsrakstu mobilajā telefonā",
  "Card View": "Kartes skats",
  "Card background color": "Kartes fona krāsa",
  "Title font": "Nosaukuma fonts",
  "Desciption font": "Apraksta fonts",
  "Section font": "Fontu sadaļa",
  "Section divider color": "Sadaļu dalītāja krāsa",
  "Add event": "Pievienot notikumu",
  "All Day Event": "Visas dienas pasākums",
  "Location": "Atrašanās vieta",
  "Choose a category": "Izvēlieties kategoriju",
  "Venue name": "Norises vietas nosaukums",
  "Venue phone": "Vietas tālrunis",
  "Venue email": "Norises vietas e-pasts",
  "Venue website": "Vietas vietne",
  "Organizer name": "Organizer name",
  "Organizer phone": "Organizatora tālrunis",
  "Organizer email": "Organizer e-pasts",
  "Organizer website": "Organizatora vietne",
  "Personal info": "Personiskā informācija",
  "First name": "Vārds",
  "Last name": "Uzvārds",
  "Email Address": "Epasta adrese",
  "Additional Notes": "Papildu piezīmes",
  "Back": "Atpakaļ",
  "Save": "Saglabāt",
  "Next": "Nākamais",
  "Your event has been submitted": "Jūsu pasākums ir iesniegts",
  "Event submittion has been failed": "Notikuma iesniegšana neizdevās",
  "e.g. Birthday Party": "piem. Dzimšanas dienas ballīte",
  "First Name": "Vārds",
  "Last Name": "Uzvārds",
  "Phone Number": "Telefona numurs",
  "Address": "Adrese",
  "Your comments": "Jūsu komentāri",
  "How many guests?": "Cik viesu?",
  "Anything else we need to know?": "Vai vēl kaut kas mums jāzina?",
  "Guests:": "Viesi:",
  "Submit": "Iesniegt",
  "Go to Calendar": "Dodieties uz Kalendāru",
  "Registration completed successfully!": "Reģistrācija veiksmīgi pabeigta!",
  "Please check your registered email address": "Lūdzu, pārbaudiet savu reģistrēto e-pasta adresi",
  "Add to Calendar": "Pievienot kalendāram",
  "Share this Event": "Kopīgojiet šo notikumu",
  "Sorry something went wrong": "Sorry, er ging iets mis",
  "Back to registration": "Atpakaļ pie reģistrācijas",
  "Date & Location": "Datums un vieta",
  "Date & Time": "Datums Laiks",
  "home": "mājas",
  "Header align": "Galvenes izlīdzināšana",
  "Footer": "Kājene",
  "Categories Filter": "kategorijas Filtrēt",
  "Show only upcoming": "Rādīt tikai gaidāmos",
  "Card(s) in a row": "Karte (-s) pēc kārtas",
  "Space between cards": "Vieta starp kartēm",
  "Shown events limit": "Parādīts notikumu ierobežojums",
  "Style 1": "1. stils",
  "Style 2": "2. stils",
  "Style 3": "3. stils",
  "Style 4": "4. stils",
  "Buttons & Links": "Pogas un saites",
  "Button corner radius": "Pogas stūra rādiuss",
  "Buttons font": "Pogu fonts",
  "Buttons background": "Pogu fons",
  "Get notified by Email": "Saņemiet paziņojumu pa e-pastu",
  "Review events": "Pārskatiet notikumus",
  "Click on date": "Noklikšķiniet uz datuma",
  "Add Event button": "Pievienot notikumu pogu",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Sinhronizējot kalendāru, varat integrēt savus notikumus un sesijas savā Boom kalendārā.",
  "connect": "savienot",
  "Synchronized Calendars": "Sinhronizētie kalendāri",
  "Import events": "Importēt pasākumus",
  "Disconnect": "Atvienojiet",
  "Choose calendar": "Izvēlieties kalendāru",
  "Monitor your Wix events through the sync feature": "Pārraugiet savus Wix notikumus, izmantojot sinhronizācijas funkciju",
  "Connect all your Boom calendars available on your website": "Pievienojiet visus jūsu vietnē pieejamos Boom kalendārus",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Ieplānojiet, pievienojieties un pārvaldiet tālummaiņas sapulces tieši caur mūsu uzplaukuma kalendāru.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Pārraugiet savus Event Brite notikumus, izmantojot Event Brite sinhronizācijas funkciju",
  "Email": "E-pasts",
  "Add-ons": "Papildinājumi",
  "Receive notification emails as soon as users add events to your calendar.": "Saņemt paziņojumu e-pastus, tiklīdz lietotāji pievieno notikumus jūsu kalendārā.",
  "Enable + button on the calendar header": "Ieslēgt + pogu uz kalendāra galvenes",
  "Accept or decline events added by customers before making them public.": "Pirms publiskošanas pieņemt vai noraidīt klientu pievienotos notikumus.",
  "Switch Add Event": "Switch Pievienot notikumu",
  "Enable your browser cookies to connect to your account.": "Iespējojiet pārlūkprogrammas sīkfailus izveidot savienojumu ar jūsu kontu.",
  "Learn more": "Uzzināt vairāk",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.": "Atļaujiet saviem lietotājiem izdrukāt jūsu Boom notikuma kalendāru jebkurā datuma diapazonā.",
  "Show Title on mobile": "Parādīt nosaukumu mobilajā ierīcē",
  "Show Skeleton on mobile": "Rādīt skeletu mobilajā telefonā",
  "Start 7-day Business trial" : "Sāciet savu 7 dienu biznesa izmēģinājumu",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons." : "Izbaudiet visas neierobežotās funkcijas, piemēram, pārdot biļetes, reģistrāciju, apmeklētāju notikumu papildinājumu.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan." : "Lūdzu, ņemiet vērā: beigās izmēģinājuma perioda, jūs atgriezīsies jūsu esošajā abonēšanas plānā.",
  "Not Now" : "Ne tagad",
  "Start free trial" : "Sākt bezmaksas izmēģinājumu",
  "Congrats!" : "Apsveicu!",
  "Your 7-day Business trial has been successfully activated." : "Jūsu 7 dienu biznesa izmēģinājums ir veiksmīgi aktivizēts.",
  "Done" : "Darīts",
  "Title font color" : "Nosaukuma fonta krāsa",
  "Desciption font color" : "Apraksts Fonta krāsa",
  "Section font color" : "Sekcijas fonta krāsa",
  "Card Header" : "Kartes galvene",
  "Category" : "Kategorija",
  "Display at the" : "Displejs pie",
  "top" : "tops",
  "bottom" : "apakšējā daļa",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only" : "Vitrīna kategorijas filtru augšpusē vai apakšā kalendāra.Uzstādījumi attiecas tikai uz darba kārtību un kartēm",
 "Processing your events" : "Jūsu notikumu apstrāde",
 "Search for events" : "Meklēt notikumus",
 "There are no events added" : "Nav pievienoti notikumi",
 "Location: To be determined" : "Atrašanās vieta: jānosaka",
 "No events for selected date" : "Nav notikumu izvēlētajam datumam"
}
export default lv