let nl = {
  "Categories": "Categorieën",
  "Share this event": "Deel dit evenement",
  "Language": "Taal",
  "Show Time Zone": "Tijdzone Tonen",
  "Custom Local Settings": "Aangepaste Lokale Instellingen",
  "Add and showcase events on your site using a beautiful calendar.": "Voeg evenementen toe aan uw pagina met behulp van een mooie kalender . ",
  "Week Days": "Dagen van de Week",
  "Manage Events": "Beheer Evenementen",
  "General": "Algemeen",
  "Layout Picker": "Kies Layout",
  "Month": "Maand",
  "Monthly": "Per Maand",
  "Week": "Week",
  "Weekly": "Per Week",
  "Day": "Dag",
  "Daily": "Per Dag",
  "Agenda": "Agenda",
  "Navigation Buttons": "Navigatie Knoppen",
  "Week numbers": "Weeknummers",
  "Include Weekends": "Inclusief Weekend",
  "All-day": "De hele dag",
  "All Day": "De hele dag",
  "Label": "Benoemen",
  "Fit to Height": "Aanpassen aan Hoogte",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Als u app-verhoudingen wilt instellen, schakelt u deze optie uit en wijzigt u de grootte van Kalender in Editor. ",
  "Default Layout": "Standaard Opmaak",
  "Monthly view": "per Maand",
  "Weekly and Daily view": "Wekelijkse en Dagelijkse overzicht",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "U kunt bezoekers een meer consistente ervaring geven door hetzelfde aantal weken ( 6) tegelijkertijd weer te geven.",
  "Fixed Weekly Layout": "Vaste Weekindeling",
  "back": " terug ",
  "Row": "Rij",
  "Hours in Weekly View": "Uren per Week",
  "Hours in Daily View": "Uren per Dag",
  "Start": "Start",
  "End": "Slutt",
  "At This Hour": "Tijdstip",
  "Button": "Knop",
  "Buttons": "Toetsen",
  "Sunday": "Zondag",
  "Monday": "Maandag",
  "Tuesday": "Dinsdag",
  "Wednesday": "Woensdag",
  "Thursday": " Donderdag ",
  "Friday": "Vrijdag",
  "Saturday": "Zaterdag",
  "Default Date": "Standaard Datum",
  "year": " jaar ",
  "month": " maand ",
  "days": " dagen ",
  "ago": " geleden ",
  "ahead": " vooruit ",
  "Yesterday": "Gisteren",
  "Today": "Vandaag",
  "Tomorrow": "Morgen",
  "Custom": "Aangepast",
  "Set Daily Rows Limit": "Rijenlimiet Dagen Instellen",
  "Set Proportions": "Eigenschappen Instellen",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Toestaan dat bezoeker evenement aan lokale Agenda's toevoegt , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Kader",
  "Background": "Achtergrond",
  "Container Background": "Achtergrond Kader",
  "Container Borders": "Randen Kader",
  "Calendar": "Kalender",
  "Event Info Tooltip": "Event Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Wanneer mensen boven een evenement hangen, zien ze alle info erover in een tooltip. ",
  "Event Info Window": "Event Info Window",
  "This is the full information window that opens when someone clicks on the event.": "Dit is het volledige informatievenster dat opent, wanneer men op het evenement klikt. ",
  "Use Gradient": "Gebruik Gradient",
  "Vertical": "Verticaal",
  "Horizontal": "Horizontaal",
  "First": "Eerste",
  "Second": "Tweede",
  "diagonal": " Diagonaal ",
  "Radial": "Radiaal",
  "Select option": "Selecteer optie",
  "Solid": "Solide",
  "Dotted": "Gestippeld",
  "Dashed": "Gestreept",
  "Double": "Dubbel",
  "Border Radius": "Rand Radius",
  "Padding": "Vulling",
  "Date Header": "Datum Koptekst",
  "Event Default Color": "Standaardkleur Evenement",
  "Days of Week": "Dagen van de Week",
  "Days of Week Background": "Achtergrond Dagen van de Week",
  "Date": "Dato",
  "Event Title": "Event title",
  "Highlight today": "Markeer Vandaag",
  "Highlight Color": "Markeer Kleur",
  "Hide": "Verbergen",
  "Calendar Border Color": "Randkleur Kalender",
  "Calendar Border Width": "Randbreedte Kalender",
  "Calendar Border Style": "Randstijl Kalender",
  "Font Color": "Letterkleur",
  "Event Background": "Achtergrond Activiteit",
  "Card Date Color": "Kaart Datum kleur",
  "Title Font": "Titel Lettertype",
  "Date Font": "Datum Lettertype",
  "Description Font": "Omschrijving Lettertype",
  "Button Background": "Knop Achtergrond",
  "Button Text": "Knop Tekst",
  "Border Color": "Randkleur",
  "Border Width": "Grensbreedte",
  "Border Type": "Rand Type",
  "Title": "Titel",
  "Description": "Omschrijving",
  "Background Color": "Achtergrond Kleur",
  "Divider": "Verdeler",
  "Event Details Font": "Evenement Details Lettertype",
  "Website Link Color": "Website Link Kleur",
  "Developer Info": "Info ontwikkelaar",
  "User Guide": "Gebruikershandleiding",
  "Support e-mail": "Ondersteuning e-mail",
  "Our Website": "Onze website",
  "App Review": "App Beoordeling",
  "Enjoying App? Leave us a review in the App Market.": "Blij met de app? Schrijf een beoordeling in de App-markt. ",
  "Review Us": "Beoordeel ons",
  "Connect With Us": "Bericht sturen",
  "What's your email?": "Wat is uw e-mail? ",
  "Invalid email address!": "Ongeldig e-mailadres! ",
  "Comments": "Reacties",
  "We'd love to hear from you. Send us a message.": "Wij horen graag van u. Stuur ons een bericht. ",
  "Message must be at least 5 characters long": "Bericht moet minimaal 5 tekens lang zijn",
  "Send": "Verzenden",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Als u de gebruiker wilt laten schakelen tussen agendaweergaven, schakelt u deze optie in en kiest u de weergaven die u wilt zien. ",
  "Main": "Hoofd",
  "Localize": "Lokaliseren",
  "Settings": "Instellingen",
  "Layouts": "Opmaak",
  "Advanced": "Geavanceerd",
  "Design": "Ontwerp",
  "Support": "Hulp",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alle lokale instellingen zijn (automatisch) gebaseerd op uw taal. Als uw taal in de lijst staat, hoeft u dit gedeelte niet aan te passen.",
  "Date Format": "Datum",
  "Time Format": "Tijd",
  "Text Direction": "Tekstrichting",
  "Left to Right": "van Links naar Rechts",
  "Right to Left": "van Rechts naar Links",
  "Week Starts On": "Week Begint Op",
  "Agenda Style": "Agendastijl",
  "Classic": "Klassiek",
  "Modern": "Modern",
  "Agenda Header": "Koptekst Agenda",
  "Upcoming Events": "Aankomende Evenementen",
  "Agenda Event Limit": "Agenda Event Limit",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Upgrade nu en krijg veel meer functies en geniet volop van uw APP!",
  "Upgrade Now": "Nu upgraden",
  "Hosting events that last all day? This lets you show them on your calendar.": "Organiseert u evenementen die de hele dag duren? Hiermee kunt u ze in uw agenda weergeven.",
  "24 hours": "24 uur",
  "Sat": "Zat",
  "Sun": "Zon",
  "Mon": "Maan",
  "Default": "Standaard",
  "Select custom design style for your calendar.": "Selecteer een aangepaste ontwerpstijl voor uw kalender.",
  "Style": "Stijl",
  "Styles and Colors": "Stijlen en kleuren",
  "Calendar Name": "Naam van agenda",
  "Write your Calendar name here": "Schrijf hier uw agendanaam",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Dit is niet zichtbaar voor uw gebruikers. Stel namen in om uw agenda's te onderscheiden wanneer u de Boom Calendar Sync-functie gebruikt.",
  "General Info": "Generell info",
  "Venue": "Evenementenlocatie",
  "Organizer": "Organisator",
  "Search": "Zoeken",
  "Add to": "Voeg toe",
  "calendar": "kalender",
  "Copy event URL": "Event-URL kopiëren",
  "Copied!": "Gekopieerd!",
  "Add & Share": "Toevoegen en delen",
  "Map": "Kart",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  "Uncategorised": "Ukategorisert",
  "More": "Meer",
  "Less": "Minder",
  "Register": "Registreren",
  "Card": "Kaart",

  "Guests": "Gjestene",
  "unlimited": "ubegrenset",
  "Show more": "Vis mer",
  "Enable Search": "Zoeken inschakelen",
  "+ Add Event": "+ Evenement toevoegen",
  "Manage and Sync": "Beheer en synchroniseer",
  "Show event details as...": "Afspraakdetails weergeven als ...",
  "Tooltip": "Knopinfo",
  "Popup": "Informatie box",
  "None": "Geen",
  "Show Category": "Categorie weergeven",
  "Header Align": "Koptekst uitlijnen",
  "Show Time": "Show Time",
  "Hours in Weekly/Daily View": "Uren in wekelijkse / dagelijkse weergave",
  "Share Events": "Deel evenementen",
  "Shadow": "Schaduw",
  "Inner Padding": "Inner Padding",
  "Text": "Tekst",
  "Active Button Border": "Actieve knoprand",
  "Light Mode": "Lichte modus",
  "Event Text Color": "Tekstkleur gebeurtenis",
  "Dates": "Datums",
  "Skeleton": "Skelet",
  "Skeleton Color": "Skeleton kleur",
  "Width": "Breedte",
  "Skeleton Style": "Skeleton stijl",
  "Color": "Farge",
  "Section Titles": "Sectie titels",
  "Section Content": "Sectie-inhoud",
  "Header": "Koptekst",
  "Standard": "Standard",
  "Retro": "Retro",
  "Silver": "Sølv",
  "Night": "Natt",
  "Dark": "Mørk",
  "Aubergine": "Aubergine",
  "Map Header": "Karthode",
  "Show Title in mobile": "Titel weergeven op mobiel",
  "Card View": "Kaartweergave",
  "Card background color": "Achtergrondkleur van de kaart",
  "Title font": "Titel lettertype",
  "Desciption font": "Beschrijving lettertype",
  "Section font": "Lettertype sectie",
  "Section divider color": "Kleur sectiescherm",
  "Add event": "Legg til hendelse",
  "All Day Event": "Heldags hendelse",
  "Location": "Plassering",
  "Choose a category": "Velg en kategori",
  "Venue name": "Stedets navn",
  "Venue phone": "Lokaltelefon",
  "Venue email": "E-poststed",
  "Venue website": "Stedets nettsted",
  "Organizer name": "Arrangørens navn",
  "Organizer phone": "Organiser-telefon",
  "Organizer email": "Organiser-e-post",
  "Organizer website": "Arrangørens nettsted",
  "Personal info": "Personlig informasjon",
  "First name": "Fornavn",
  "Last name": "Etternavn",
  "Email Address": "Epostadresse",
  "Additional Notes": "Tilleggsmerknader",
  "Back": "Tilbake",
  "Save": "Lagre",
  "Next": "Neste",
  "Your event has been submitted": "Arrangementet ditt er sendt inn",
  "Event submittion has been failed": "Innlevering av hendelse mislyktes",
  "e.g. Birthday Party": "f.eks. Bursdagsfest",
  "First Name": "Voornaam",
  "Last Name": "Achternaam",
  "Phone Number": "Telefonnummer",
  "Address": "Adresse",
  "Your comments": "Dine kommentarer",
  "How many guests?": "Hvor mange gjester?",
  "Anything else we need to know?": "Is er nog iets dat we moeten weten?",
  "Guests:": "Gasten:",
  "Submit": "Verzenden",
  "Go to Calendar": "Ga naar Kalender",
  "Registration completed successfully!": "Registreringen fullført!",
  "Please check your registered email address": "Controleer uw geregistreerde e-mailadres",
  "Add to Calendar": "Toevoegen aan agenda",
  "Share this Event": "Deel dit evenement",
  "Sorry something went wrong": "죄송합니다. 문제가 발생했습니다.",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Datum en locatie",
  "Date & Time": "Datum Tijd",
  "home": "huis",
  "Header align": "Koptekst uitlijnen",
  "Footer": "Voettekst",
  "Categories Filter": "categorieën Filter",
  "Show only upcoming": "Toon alleen aanstaande",
  "Card(s) in a row": "Kaart (en) op een rij",
  "Space between cards": "Ruimte tussen kaarten",
  "Shown events limit": "Limiet voor weergegeven evenementen",
  "Style 1": "Stijl 1",
  "Style 2": "Stijl 2",
  "Style 3": "Stijl 3",
  "Style 4": "Stijl 4",
  "Buttons & Links": "Knoppen en koppelingen",
  "Button corner radius": "Hoekstraal van knop",
  "Buttons font": "Knoppen lettertype",
  "Buttons background": "Knoppen achtergrond",
  "Get notified by Email": "Ontvang een melding per e-mail",
  "Review events": "Bekijk evenementen",
  "Click on date": "Klik op datum",
  "Add Event button": "Gebeurtenis toevoegen knop",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Met agendasynchronisatie kunt u uw evenementen en sessies integreren met uw Boom-agenda.",
  "connect": "aansluiten",
  "Synchronized Calendars": "Gesynchroniseerde kalenders",
  "Import events": "Evenementen importeren",
  "Disconnect": "verbinding verbreken",
  "Choose calendar": "Kies een kalender",
  "Monitor your Wix events through the sync feature": "Houd uw Wix-evenementen bij via de synchronisatiefunctie",
  "Connect all your Boom calendars available on your website": "Verbind al uw Boom-agenda's die beschikbaar zijn op uw website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Plan, neem deel en beheer Zoom-vergaderingen rechtstreeks via onze Boom-agenda.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Volg uw Event Brite-evenementen via de Event Brite-synchronisatiefunctie",
  "Email": "E-mail",
  "Add-ons": "Add-ons",
  "Receive notification emails as soon as users add events to your calendar.": "Ontvang meldings-e-mails zodra gebruikers gebeurtenissen aan uw agenda toevoegen.",
  "Enable + button on the calendar header": "Enable + knop op de kalenderkop",
  "Accept or decline events added by customers before making them public.": "Accepteert of weigeren gebeurtenissen die door klanten zijn toegevoegd voordat u ze openbaar maakt.",
  "Switch Add Event": "Schakel evenement toe",
  "Enable your browser cookies to connect to your account.": "Schakel uw browsercookies in om verbinding te maken met uw account.",
  "Learn more": "Kom meer te weten",
  "Print Button": "Drukāšanas poga",
  "Permit your users to print your Boom Event Calendar in any date range.": "Sta uw gebruikers toe om uw Boom Event-kalender in elk datumbereik af te drukken.",
  "Show Title on mobile": "Toon titel op mobiel",
  "Show Skeleton on mobile": "Toon skelet op mobiel",
  "Start 7-day Business trial": "Start uw bedrijfsprove met 7 dagen",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Geniet van alle onbeperkte functies, zoals verkooptickets, registratie, add-ons van bezoekersgebeurtenis.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Let op: aan het einde van de proefperiode wordt u teruggestuurd naar uw bestaande abonnementsplan.",
  "Not Now": "Niet nu",
  "Start free trial": "Start gratis proefversie",
  "Congrats!": "Proficiat!",
  "Your 7-day Business trial has been successfully activated.": "Uw 7-daagse bedrijfsproef is succesvol geactiveerd.",
  "Done": "Klaar",
  "Title font color": "Titel lettertype kleur",
  "Desciption font color": "Beschrijving Lettertypekleur",
  "Section font color": "Sectie lettertype kleur",
  "Card Header": "Kaartkop",
  "Category": "Categorie",
  "Display at the": "Weergave op de",
  "top": "bovenkant",
  "bottom": "onderkant",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Toon de categoriefilter aan de bovenkant of onderaan de kalender.De instellingen zijn alleen van toepassing op Agenda and Card-views",
  "Processing your events": "Uw evenementen verwerken",
  "Search for events": "Zoek naar evenementen",
  "There are no events added": "Er zijn geen gebeurtenissen toegevoegd",
  "Location: To be determined": "Locatie: te bepalen",
  "No events for selected date": "Geen evenementen voor geselecteerde datum",
  "Uncategorized": "Niet gecategoriseerd",
  "Edit event": "Event bewerken",
  "Edit original event": "Origineel evenement bewerken",
  "Copy event": "Kopieerevenement",
  "Copy as new event": "Kopieer als nieuw evenement",
  "Delete event": "Verwijder evenement",
  "Stop repeating on this date": "Stop met herhalen op deze datum",
  "Exclude this date": "Sluit deze datum uit",
  "Location is going to be announced": "Locatie wordt aangekondigd",
  "Fill your personal information": "Vul uw persoonlijke informatie in",
  "Check Box": "Selectievakje",
  "Single Choice": "Enkele keuze",
  "Option": "Keuze",
  "Share Event": "Deelgebeurtenis",
  "Oops! Something went wrong": "Oeps!Er is iets fout gegaan",
  "We are sorry this event has already taken place": "Het spijt ons dat dit evenement al heeft plaatsgevonden",
  "Back to calendar": "Terug naar kalender",
  "This field is required": "dit veld is verplicht",
  "Phone": "Telefoon",
  "Number field": "Nummerveld",
  "Option": "Keuze",
  "Check Box": "Selectievakje",
  "Single Choice": "Enkele keuze",
 "Please provide a valid email" : "Geef een geldige e -mail op",
 "Select at least one option" : "Selecteer ten minste één optie",
 "Choose tickets to see total value" : "Kies tickets om de totale waarde te zien",
 "tickets" : "kaartjes",
 "Choose Tickets" : "Kies tickets",
 "Choose payment method" : "Kies betalingsmethode",
 "Pay" : "Betalen",
 "Total" : "Totaal",
 "Free" : "Vrij",
 "Buy tickets" : "Koop kaartjes",
 "Sold Out" : "Uitverkocht",
 "Tickets are available" : "Tickets zijn beschikbaar",
 "Sales End" : "Verkoopuiteinde"
}
export default nl