let no = {
  "Categories": "Kategorier",
  "Share this event": "Del dette arrangementet",
  "Language": "Språk",
  "Show Time Zone": "Vis tidssone",
  "Custom Local Settings": "Tilpassede lokale innstillinger",
  "Add and showcase events on your site using a beautiful calendar.": "Legg til og vis hendelser på nettstedet ditt ved hjelp av en vakker kalender . ",
  "Week Days": "Ukedager",
  "Manage Events": "Administrer hendelser",
  "General": "Generell",
  "Layout Picker": "Layout Picker",
  "Month": "Måned",
  "Monthly": "Månedlig",
  "Week": "Uke",
  "Weekly": "Ukentlig",
  "Day": "Dag",
  "Daily": "Daglig",
  "Agenda": "Dagsorden",
  "Navigation Buttons": "Navigasjonsknapper",
  "Week numbers": "Ukenummer",
  "Include Weekends": "Inkluder helger",
  "All-day": "Hele dagen",
  "All Day": "Hele dagen",
  "Label": "Merkelapp",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Slik angir du app-proporsjoner manuelt deaktiverer dette alternativet og endrer størrelse på kalender i Editor. ",
  "Default Layout": "Standardoppsett",
  "Monthly view": "Månedsvisning",
  "Weekly and Daily view": "Ukentlig og daglig visning",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Du kan gi besøkende en mer konsistent opplevelse ved å vise samme antall uker ( 6) om gangen.",
  "Fixed Weekly Layout": "Fast ukesoppsett",
  "back": " tilbake ",
  "Row": "Rad",
  "Hours in Weekly View": "Timer i ukesvisning",
  "Hours in Daily View": "Timer i daglig visning",
  "Start": "Start",
  "End": "Slutt",
  "At This Hour": "På denne timen",
  "Button": "Knapp",
  "Buttons": "Knapper",
  "Sunday": "Søndag",
  "Monday": "Mandag",
  "Tuesday": "Tirsdag",
  "Wednesday": "Onsdag",
  "Thursday": " Torsdag ",
  "Friday": "Fredag",
  "Saturday": "Lørdag",
  "Default Date": "Standard dato",
  "year": " år ",
  "month": " måned ",
  "days": " dager ",
  "ago": " siden ",
  "ahead": " fremover ",
  "Yesterday": "I går",
  "Today": "I dag",
  "Tomorrow": "I morgen",
  "Custom": "Tilpasset",
  "Set Daily Rows Limit": "Angi grense for daglige rader",
  "Set Proportions": "Angi proporsjoner",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Tillat besøkende å legge til hendelser i lokale kalendere , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Container",
  "Background": "Bakgrunn",
  "Container Background": "Beholder bakgrunn",
  "Container Borders": "Beholdergrenser",
  "Calendar": "Kalender",
  "Event Info Tooltip": "Verktøytips for hendelsesinfo",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Når folk svever over et arrangement, vil de se all informasjonen om det i en verktøytips. ",
  "Event Info Window": "Vinduet med hendelsesinfo",
  "This is the full information window that opens when someone clicks on the event.": "Dette er det fullstendige informasjonsvinduet som åpnes når noen klikker på hendelsen. ",
  "Use Gradient": "Bruk gradient",
  "Vertical": "Vertical",
  "Horizontal": "Horisontal",
  "First": "Først",
  "Second": "Sekund",
  "diagonal": " diagonal ",
  "Radial": "Radial",
  "Select option": "Velg alternativ",
  "Solid": "Fast",
  "Dotted": "Prikket",
  "Dashed": "Stiplet",
  "Double": "Dobbelt",
  "Border Radius": "Border Radius",
  "Padding": "Padding",
  "Date Header": "Datohode",
  "Event Default Color": "Standardfarge på arrangement",
  "Days of Week": "Dager i uken",
  "Days of Week Background": "Days of Week bakgrunn",
  "Date": "Dato",
  "Event Title": "Event title",
  "Highlight today": "Uthev i dag",
  "Highlight Color": "Uthev farge",
  "Hide": "Gjemme seg",
  "Calendar Border Color": "Kalenderramme farge",
  "Calendar Border Width": "Kalendergrensebredde",
  "Calendar Border Style": "Kalendergrensestil",
  "Font Color": "Skriftfarge",
  "Event Background": "Hendelsesbakgrunn",
  "Card Date Color": "Farge på kortdato",
  "Title Font": "Tittelfont",
  "Date Font": "Datoskrift",
  "Description Font": "Beskrivelse Font",
  "Button Background": "Knappbakgrunn",
  "Button Text": "Knapptekst",
  "Border Color": "Grensefarge",
  "Border Width": "Border Width",
  "Border Type": "Grensetype",
  "Title": "Tittel",
  "Description": "Beskrivelse",
  "Background Color": "Bakgrunnsfarge",
  "Divider": "Deler",
  "Event Details Font": "Fontdetaljer for hendelsesdetaljer",
  "Website Link Color": "Nettstedslinkfarge",
  "Developer Info": "Utviklerinfo",
  "User Guide": "Brukerhåndboken",
  "Support e-mail": "Støtte e-post",
  "Our Website": "Vår nettside",
  "App Review": "Appanmeldelse",
  "Enjoying App? Leave us a review in the App Market.": "Nyter appen? Gi oss en anmeldelse i appmarkedet. ",
  "Review Us": "Gjennomgå oss",
  "Connect With Us": "Koble til oss",
  "What's your email?": "Hva er e-postmeldingen din? ",
  "Invalid email address!": "Ugyldig e-postadresse! ",
  "Comments": "Kommentarer",
  "We'd love to hear from you. Send us a message.": "Vi vil gjerne høre fra deg. Send oss ​​en melding. ",
  "Message must be at least 5 characters long": "Meldingen må være minst 5 tegn lang",
  "Send": "Sende",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Hvis du vil la brukeren bytte mellom kalendervisninger, aktiverer du dette alternativet og velger visningene du vil vise. ",
  "Main": "Hoved",
  "Localize": "Lokal",
  "Settings": "innstillinger",
  "Layouts": "oppsett",
  "Advanced": "Avansert",
  "Design": "Design",
  "Support": "Brukerstøtte",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Alle lokale innstillinger er (automatisk) basert på språket ditt. Hvis språket ditt er på listen, er det ikke nødvendig å tilpasse denne delen.",
  "Date Format": "Datoformat",
  "Time Format": "Tidsformat",
  "Text Direction": "Tekstretning",
  "Left to Right": "Venstre til høyre",
  "Right to Left": "Høyre til venstre",
  "Week Starts On": "Uken starter",
  "Agenda Style": "Agenda Style",
  "Classic": "Classic",
  "Modern": "Moderne",
  "Agenda Header": "Agenda Header",
  "Upcoming Events": "Kommende arrangementer",
  "Agenda Event Limit": "Agenda begivenhetsgrense",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Oppgrader nå og få mange flere funksjoner og nyt appen din i sin helhet!",
  "Upgrade Now": "Oppgrader nå",
  "Hosting events that last all day? This lets you show them on your calendar.": "Hosting av arrangementer som varer hele dagen? Dette lar deg vise dem i kalenderen din.",
  "24 hours": "24 timer",
  "Sun": "Søn",
  "Mon": "Man",
  "Sat": "Lør",
  "Default": "Misligholde",
  "Select custom design style for your calendar.": "Velg tilpasset designstil for kalenderen.",
  "Style": "Stil",
  "Styles and Colors": "Stiler og farger",
  "Calendar Name": "Kalendernavn",
  "Write your Calendar name here": "Skriv kalendernavnet ditt her",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Dette er ikke synlig for brukerne dine. Angi navn for å differensiere kalenderne dine når du bruker Boom Calendar Sync-funksjonen.",
  "General Info": "Generell info",
  "Venue": "spillested",
  "Organizer": "Planlegger",
  "Search": "Søk",
  "Add to": "Legge til",
  "calendar": "kalender",
  "Copy event URL": "Kopier URL-adresse",
  "Copied!": "Kopiert!",
  "Add & Share": "Legg til og del",
  "Map": "Kart",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  "Uncategorised": "Ukategorisert",
  "More": "Mer",
  "Less": "Mindre",
  "Register": "Registrere",
  "Card": "Kaart",
  "There are no events": "Det er ingen hendelser",
  "Guests": "Gjestene",
  "unlimited": "ubegrenset",
  "Show more": "Vis mer",
  "Enable Search": "Aktiver søk",
  "+ Add Event": "+ Legg til hendelseAdministrer og synkroniser",
  "Manage and Sync": "Administrer og synkroniser",
  "Show event details as...": "Vis hendelsesdetaljer som ...",
  "Tooltip": "tooltip",
  "Popup": "Info-boksen",
  "None": "Ingen",
  "Show Category": "Vis kategori",
  "Header Align": "Topplinje Juster",
  "Show Time": "Vis tid",
  "Hours in Weekly/Daily View": "Timer i ukevis / daglig visning",
  "Share Events": "Del hendelser",
  "Shadow": "skygge",
  "Inner Padding": "Indre polstring",
  "Text": "Tekst",
  "Active Button Border": "Aktiv knappekant",
  "Light Mode": "Lysmodus",
  "Event Text Color": "Farge på hendelsestekst",
  "Dates": "datoer",
  "Skeleton": "Skjelett",
  "Skeleton Color": "Skjelettfarge",
  "Width": "Bredde",
  "Skeleton Style": "Skjelettstil",
  "Color": "Farge",
  "Section Titles": "Seksjonstitler",
  "Section Content": "Seksjonens innhold",
  "Header": "Overskrift",
  "Standard": "Standard",
  "Retro": "Retro",
  "Silver": "Sølv",
  "Night": "Natt",
  "Dark": "Mørk",
  "Aubergine": "Aubergine",
  "Map Header": "Karthode",
  "Show Title in mobile": "Vis tittel på mobil",
  "Card View": "Kaartweergave",
  "Card background color": "Achtergrondkleur van de kaart",
  "Title font": "Titel lettertype",
  "Desciption font": "Beschrijving lettertype",
  "Section font": "Lettertype sectie",
  "Section divider color": "Kleur sectiescherm",
  "Add event": "Legg til hendelse",
  "All Day Event": "Heldags hendelse",
  "Location": "Plassering",
  "Choose a category": "Velg en kategori",
  "Venue name": "Stedets navn",
  "Venue phone": "Lokaltelefon",
  "Venue email": "E-poststed",
  "Venue website": "Stedets nettsted",
  "Organizer name": "Arrangørens navn",
  "Organizer phone": "Organiser-telefon",
  "Organizer email": "Organiser-e-post",
  "Organizer website": "Arrangørens nettsted",
  "Personal info": "Personlig informasjon",
  "First name": "Fornavn",
  "Last name": "Etternavn",
  "Email Address": "Epostadresse",
  "Additional Notes": "Tilleggsmerknader",
  "Back": "Tilbake",
  "Save": "Lagre",
  "Next": "Neste",
  "Your event has been submitted": "Arrangementet ditt er sendt inn",
  "Event submittion has been failed": "Innlevering av hendelse mislyktes",
  "e.g. Birthday Party": "f.eks. Bursdagsfest",
  "First Name": "Voornaam",
  "Last Name": "Etternavn",
  "Phone Number": "Telefonnummer",
  "Address": "Adresse",
  "Your comments": "Dine kommentarer",
  "How many guests?": "Hvor mange gjester?",
  "Anything else we need to know?": "Is er nog iets dat we moeten weten?",
  "Guests:": "Gasten:",
  "Submit": "Verzenden",
  "Go to Calendar": "Gå til Kalender",
  "Registration completed successfully!": "Registreringen fullført!",
  "Please check your registered email address": "Controleer uw geregistreerde e-mailadres",
  "Add to Calendar": "Legg til i kalenderen",
  "Share this Event": "Del denne hendelsen",
  "Sorry something went wrong": "Beklager, noe gikk galt",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Dato og beliggenhet",
  "Date & Time": "Dato tid",
  "home": "hjem",
  "Header align": "Hodejustering",
  "Footer": "Bunntekst",
  "Categories Filter": "kategorier Filter",
  "Show only upcoming": "Vis bare kommende",
  "Card(s) in a row": "Kort (er) på rad",
  "Space between cards": "Plass mellom kort",
  "Shown events limit": "Viste begivenhetsgrenser",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Stil 4.",
  "Buttons & Links": "Knapper og lenker",
  "Button corner radius": "Knapp hjørneradius",
  "Buttons font": "Knapper font",
  "Buttons background": "Knapper bakgrunn",
  "Get notified by Email": "Bli varslet via e-post",
  "Review events": "Gjennomgå hendelser",
  "Click on date": "Klikk på dato",
  "Add Event button": "Legg til hendelsesknapp",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Kalendersynkronisering lar deg integrere hendelser og økter med Boom-kalenderen.",
  "connect": "koble",
  "Synchronized Calendars": "Synkroniserte kalendere",
  "Import events": "Importer hendelser",
  "Disconnect": "Koble fra",
  "Choose calendar": "Velg Kalender",
  "Monitor your Wix events through the sync feature": "Overvåke Wix-hendelsene dine gjennom synkroniseringsfunksjonen",
  "Connect all your Boom calendars available on your website": "Koble til alle dine Boom-kalendere som er tilgjengelige på nettstedet ditt",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Planlegg, bli med, og administrer zoommøter rett gjennom vår boomkalender.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Overvåk Event Brite-hendelsene dine gjennom Event Brite-synkroniseringsfunksjonen",
  "Email": "E-post",
  "Add-ons": "Tillegg",
  "Receive notification emails as soon as users add events to your calendar.": "Motta varslingsmeldinger så snart brukerne legger til hendelser i kalenderen din.",
  "Enable + button on the calendar header": "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.": "Godta eller avslå hendelser lagt til av kunder før de gjør dem offentlige.",
  "Switch Add Event": "Bytt Legg til arrangement",
  "Enable your browser cookies to connect to your account.": "Aktiver nettleserkakene dine for å koble til kontoen din.",
  "Learn more": "Lære mer",
  "Print Button": "Wydrukuj przycisk",
  "Permit your users to print your Boom Event Calendar in any date range.": "Tillat brukerne å skrive ut Boom Event-kalenderen i et hvilket som helst datoport.",
  "Show Title on mobile": "Vis tittel på mobil",
  "Show Skeleton on mobile": "Vis skjelett på mobilen",
  "Start 7-day Business trial" : "Start din 7-dagers forretningsprøve",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons." : "Nyt alle ubegrensede funksjoner, for eksempel selger billetter, registrering, tilleggsavsetninger.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan." : "Vennligst merk: Ved slutten av prøveperioden vil du bli returnert til din eksisterende abonnementsplan.",
  "Not Now" : "Ikke nå",
  "Start free trial" : "Start gratis prøveperiode",
  "Congrats!" : "Gratulerer!",
  "Your 7-day Business trial has been successfully activated." : "Din 7-dagers forretningsprøve har blitt aktivert.",
  "Done" : "Gjort",
  "Title font color" : "Tittel Font Color.",
  "Desciption font color" : "Beskrivelse Font Color.",
  "Section font color" : "Seksjonsfont Color.",
  "Card Header" : "Kort header.",
  "Category" : "Kategori",
  "Display at the" : "Vis på det",
  "top" : "topp",
  "bottom" : "bunn",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only" : "Vis at kategorifilteret øverst eller nederst på kalenderen.Innstillingene gjelder bare for agenda- og kortvisninger",
 "Processing your events" : "Behandler hendelsene dine"
}
export default no