let pl = {
  "Categories": "Kategorie",
  "Share this event": "Udostępnij to wydarzenie",
  "Language": "Język",
  "Show Time Zone": "Pokaż strefę czasową",
  "Custom Local Settings": "Niestandardowe ustawienia lokalne",
  "Add and showcase events on your site using a beautiful calendar.": "Dodaj i pokaż wydarzenia w swojej witrynie za pomocą pięknego kalendarza . ",
  "Week Days": "Dni tygodnia",
  "Manage Events": "Zarządzaj wydarzeniami",
  "General": "Generał",
  "Layout Picker": "Wybór układu",
  "Month": "Miesiąc",
  "Monthly": "Miesięczny",
  "Week": "Tydzień",
  "Weekly": "Co tydzień",
  "Day": "Dzień",
  "Daily": "Codziennie",
  "Agenda": "Program",
  "Navigation Buttons": "Przyciski nawigacyjne",
  "Week numbers": "Numery tygodniowe",
  "Include Weekends": "Dołącz weekendy",
  "All-day": "Cały dzień",
  "All Day": "Cały dzień",
  "Label": "Etykieta",
  "Fit to Height": "Dopasuj do wysokości",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Aby ustawić proporcje App manully wyłączyć tę opcję i rozmiaru kalendarz w edytorze. ",
  "Default Layout": "Domyślny układ",
  "Monthly view": "Widok miesięczny",
  "Weekly and Daily view": "Widok tygodniowy i dzienny",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Możesz zapewnić odwiedzającym bardziej spójne wrażenia, pokazując tę ​​samą liczbę tygodni ( 6) naraz",
  "Fixed Weekly Layout": "Naprawiono układ tygodniowy",
  "back": " powrót ",
  "Row": "Rząd",
  "Hours in Weekly View": "Godziny w widoku tygodniowym",
  "Hours in Daily View": "Godziny w widoku dziennym",
  "Start": "Początek",
  "End": "Koniec",
  "At This Hour": "O tej godzinie",
  "Button": "Przycisk",
  "Buttons": "Guziki",
  "Sunday": "Niedziela",
  "Monday": "Poniedziałek",
  "Tuesday": "Wtorek",
  "Wednesday": "Środa",
  "Thursday": " Czwartek ",
  "Friday": "Piątek",
  "Saturday": "Sobota",
  "Default Date": "Data domyślna",
  "year": " rok ",
  "month": " miesiąc ",
  "days": " dni ",
  "ago": " temu ",
  "ahead": " naprzód ",
  "Yesterday": "Wczoraj",
  "Today": "Dzisiaj",
  "Tomorrow": "Jutro",
  "Custom": "Zwyczaj",
  "Set Daily Rows Limit": "Ustaw limit dzienny wierszy",
  "Set Proportions": "Ustaw proporcje",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Pozwól odwiedzającym dodawać wydarzenia do lokalnych Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Pojemnik",
  "Background": "Tło",
  "Container Background": "Tło pojemnika",
  "Container Borders": "Granice kontenerów",
  "Calendar": "Kalendarz",
  "Event Info Tooltip": "Etykieta informacji o wydarzeniu",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Gdy ludzie najeżdżają na zdarzenie, zobaczą wszystkie informacje o nim w podpowiedzi. ",
  "Event Info Window": "Okno informacji o wydarzeniu",
  "This is the full information window that opens when someone clicks on the event.": "To jest pełne okno informacyjne, które otwiera się, gdy ktoś kliknie wydarzenie. ",
  "Use Gradient": "Użyj gradientu",
  "Vertical": "Pionowy",
  "Horizontal": "Poziomy",
  "First": "Pierwszy",
  "Second": "Druga",
  "diagonal": " przekątna ",
  "Radial": "Promieniowy",
  "Select option": "Wybierz opcję",
  "Solid": "Solidny",
  "Dotted": "Kropkowany",
  "Dashed": "Przerywane",
  "Double": "Podwójnie",
  "Border Radius": "Promień graniczny",
  "Padding": "Wyściółka",
  "Date Header": "Nagłówek daty",
  "Event Default Color": "Domyślny kolor zdarzenia",
  "Days of Week": "Dni tygodnia",
  "Days of Week Background": "Tło dni tygodnia",
  "Date": "Data",
  "Event Title": "Tytuł wydarzenia",
  "Highlight today": "Podświetl dzisiaj",
  "Highlight Color": "Podświetlony kolor",
  "Hide": "Ukryć",
  "Calendar Border Color": "Kolor obramowania kalendarza",
  "Calendar Border Width": "Szerokość obramowania kalendarza",
  "Calendar Border Style": "Styl obramowania kalendarza",
  "Font Color": "Kolor czcionki",
  "Event Background": "Tło wydarzenia",
  "Card Date Color": "Kolor daty karty",
  "Title Font": "Czcionka tytułu",
  "Date Font": "Czcionka daty",
  "Description Font": "Czcionka opisu",
  "Button Background": "Tło przycisku",
  "Button Text": "Przycisk tekstowy",
  "Border Color": "Kolor ramki",
  "Border Width": "Szerokość granicy",
  "Border Type": "Typ obramowania",
  "Title": "Tytuł",
  "Description": "Opis",
  "Background Color": "Kolor tła",
  "Divider": "Rozdzielacz",
  "Event Details Font": "Czcionka szczegółów wydarzenia",
  "Website Link Color": "Kolor linku do witryny",
  "Developer Info": "Informacje dla programistów",
  "User Guide": "Podręcznik użytkownika",
  "Support e-mail": "Wsparcie e-mail",
  "Our Website": "Nasza strona internetowa",
  "App Review": "Przegląd aplikacji",
  "Enjoying App? Leave us a review in the App Market.": "Korzystając z aplikacji? Zostaw nam recenzję na App Market. ",
  "Review Us": "Sprawdź nas",
  "Connect With Us": "Połącz się z nami",
  "What's your email?": "Jaki jest twój e-mail? ",
  "Invalid email address!": "Nieprawidłowy adres e-mail! ",
  "Comments": "Komentarze",
  "We'd love to hear from you. Send us a message.": "Chcielibyśmy usłyszeć od ciebie. Wyślij nam wiadomość. ",
  "Message must be at least 5 characters long": "Wiadomość musi mieć co najmniej 5 znaków",
  "Send": "Wysłać",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Jeśli chcesz zezwolić użytkownikowi na przełączanie się między widokami kalendarza, włącz tę opcję i wybierz widoki, które chcesz pokazać. ",
  "Main": "Główny",
  "Localize": "Zlokalizować",
  "Settings": "Ustawienia",
  "Layouts": "Układy",
  "Advanced": "Zaawansowane",
  "Design": "Projekt",
  "Support": "Wsparcie",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Wszystkie lokalne ustawienia są (automatycznie) oparte na twoim języku. Jeśli Twój język jest na liście, nie ma potrzeby dostosowywania tej sekcji.",
  "Date Format": "Format daty",
  "Time Format": "Format czasu",
  "Text Direction": "Kierunek tekstu",
  "Left to Right": "Z lewej na prawą",
  "Right to Left": "Od prawej do lewej",
  "Week Starts On": "Tydzień zaczyna się od",
  "Agenda Style": "Styl agendy",
  "Classic": "Klasyczny",
  "Modern": "Nowoczesny",
  "Agenda Header": "Nagłówek agendy",
  "Upcoming Events": "nadchodzące wydarzenia",
  "Agenda Event Limit": "Limit wydarzeń w programie",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Zaktualizuj teraz i uzyskaj o wiele więcej funkcji i ciesz się aplikacją w całości!",
  "Upgrade Now": "Ulepsz teraz",
  "Hosting events that last all day? This lets you show them on your calendar.": "Prowadzisz wydarzenia trwające cały dzień? To pozwala pokazać je w kalendarzu.",
  "24 hours": "24 godziny",
  "Sat": "Sob",
  "Sun": "Nie",
  "Mon": "Pon",
  "Default": "Domyślna",
  "Select custom design style for your calendar.": "Wybierz niestandardowy styl projektowania swojego kalendarza.",
  "Style": "Styl",
  "Styles and Colors": "Style i kolory",
  "Calendar Name": "Nazwa kalendarza",
  "Write your Calendar name here": "Wpisz tutaj swoją nazwę kalendarza",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Nie jest to widoczne dla użytkowników. Ustaw nazwy, aby rozróżnić kalendarze podczas korzystania z funkcji synchronizacji kalendarza Boom.",
  "General Info": "Ogólne informacje",
  "Venue": "Miejsce wydarzenia",
  "Organizer": "Organizator",
  "Search": "Szukaj",
  "Add to": "Dodać do",
  "calendar": "kalendarz",
  "Copy event URL": "Skopiuj adres URL wydarzenia",
  "Copied!": "Skopiowano!",
  "Add & Share": "Dodaj i udostępnij",
  "Map": "Mapa",
  "Calendar view": "Widok kalendarza",
  "Add Event": "Dodaj wydarzenie",
  "Uncategorised": "Bez kategorii",
  "More": "Więcej",
  "Less": "Mniej",
  "Register": "Zarejestrować",
  "Card": "Karta",

  "Guests": "Goście",
  "unlimited": "Nieograniczony",
  "Show more": "Pokaż więcej",
  "Enable Search": "Włącz wyszukiwanie",
  "+ Add Event": "+ Dodaj wydarzenie",
  "Manage and Sync": "Zarządzaj i synchronizuj",
  "Show event details as...": "Pokaż szczegóły wydarzenia jako ...",
  "Tooltip": "Etykietka",
  "Popup": "Skrzynka informacyjna",
  "None": "Żaden",
  "Show Category": "Pokaż kategorię",
  "Header Align": "Header Align",
  "Show Time": "Header Align",
  "Hours in Weekly/Daily View": "Godziny w widoku tygodniowym / dziennym",
  "Share Events": "Udostępniaj wydarzenia",
  "Shadow": "Cień",
  "Inner Padding": "Wewnętrzna wyściółka",
  "Text": "Tekst",
  "Active Button Border": "Ramka aktywnego przycisku",
  "Light Mode": "Tryb światła",
  "Event Text Color": "Kolor tekstu wydarzenia",
  "Dates": "Daktyle",
  "Skeleton": "Szkielet",
  "Skeleton Color": "Kolor szkieletu",
  "Width": "Szerokość",
  "Skeleton Style": "Styl szkieletu",
  "Color": "Kolor",
  "Section Titles": "Tytuły sekcji",
  "Section Content": "Treść sekcji",
  "Header": "nagłówek",
  "Standard": "Standard",
  "Retro": "Retro",
  "Silver": "Srebro",
  "Night": "Noc",
  "Dark": "Ciemny",
  "Aubergine": "Noc",
  "Map Header": "Nagłówek mapy",
  "Show Title in mobile": "Pokaż tytuł w telefonie komórkowym",
  "Card View": "Widok karty",
  "Card background color": "Kolor tła karty",
  "Title font": "Czcionka tytułu",
  "Desciption font": "Czcionka opisu",
  "Section font": "Sekcja czcionek",
  "Section divider color": "Kolor przegrody",
  "Add event": "Dodaj wydarzenie",
  "All Day Event": "Wydarzenie całodniowe",
  "Location": "Lokalizacja",
  "Choose a category": "Wybierz kategorię",
  "Venue name": "Nazwa miejsca",
  "Venue phone": "Telefon miejsca",
  "Venue email": "E-mail dotyczący miejsca",
  "Venue website": "Strona miejsca",
  "Organizer name": "Nazwa organizatora",
  "Organizer phone": "Telefon organizatora",
  "Organizer email": "E-mail organizatora",
  "Organizer website": "Witryna organizatora",
  "Personal info": "Dane osobiste",
  "First name": "Imię",
  "Last name": "Nazwisko",
  "Email Address": "Adres e-mail",
  "Additional Notes": "Dodatkowe uwagi",
  "Back": "Z powrotem",
  "Save": "Zapisać",
  "Next": "Kolejny",
  "Your event has been submitted": "Twoje wydarzenie zostało przesłane",
  "Event submittion has been failed": "Przesłanie wydarzenia nie powiodło się",
  "e.g. Birthday Party": "na przykład. Przyjęcie urodzinowe",
  "First Name": "Imię",
  "Last Name": "Nazwisko",
  "Phone Number": "Numer telefonu",
  "Address": "Adres",
  "Your comments": "Twoje komentarze",
  "How many guests?": "Ilu gości?",
  "Anything else we need to know?": "Coś jeszcze musimy wiedzieć?",
  "Guests:": "Goście:",
  "Submit": "Zatwierdź",
  "Go to Calendar": "",
  "Registration completed successfully!": "Rejestracja zakończona pomyślnie!",
  "Please check your registered email address": "Sprawdź swój zarejestrowany adres e-mail",
  "Add to Calendar": "Dodaj do kalendarza",
  "Share this Event": "Udostępnij to wydarzenie",
  "Sorry something went wrong": "Przepraszam, coś poszło nie tak",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Data i lokalizacja",
  "Date & Time": "Data i godzina",
  "home": "Dom",
  "Header align": "Wyrównaj nagłówek",
  "Footer": "Stopka",
  "Categories Filter": "kategorie Filtr",
  "Show only upcoming": "Pokaż tylko nadchodzące",
  "Card(s) in a row": "Karty z rzędu",
  "Space between cards": "Przestrzeń między kartami",
  "Shown events limit": "Limit wyświetlanych wydarzeń",
  "Style 1": "Styl 1",
  "Style 2": "Styl 2",
  "Style 3": "Styl 3",
  "Style 4": "Styl 4",
  "Buttons & Links": "Przyciski i linki",
  "Button corner radius": "Promień narożnika przycisku",
  "Buttons font": "Czcionka przycisków",
  "Buttons background": "Tło przycisków",
  "Get notified by Email": "Otrzymuj powiadomienia e-mailem",
  "Review events": "Przegląd wydarzeń",
  "Click on date": "Kliknij datę",
  "Add Event button": "Przycisk Dodaj wydarzenie",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Synchronizacja kalendarza umożliwia integrację wydarzeń i sesji z kalendarzem Boom.",
  "connect": "połączyć",
  "Synchronized Calendars": "Kalendarze zsynchronizowane",
  "Import events": "Importuj wydarzenia",
  "Disconnect": "Rozłączyć się",
  "Choose calendar": "Wybierz kalendarz",
  "Monitor your Wix events through the sync feature": "Monitoruj swoje wydarzenia Wix za pomocą funkcji synchronizacji",
  "Connect all your Boom calendars available on your website": "Połącz wszystkie swoje kalendarze Boom dostępne w Twojej witrynie",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Planuj, dołączaj i zarządzaj spotkaniami Zoom za pomocą naszego Kalendarza Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Monitoruj wydarzenia Event Brite za pomocą funkcji synchronizacji Event Brite",
  "Email": "E-mail",
  "Add-ons": "Dodatki",
  "Receive notification emails as soon as users add events to your calendar.": "Otrzymuj powiadomienia e-maile, gdy tylko użytkownicy dodają zdarzenia do kalendarza.",
  "Enable + button on the calendar header": "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.": "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Switch Dodaj zdarzenie",
  "Enable your browser cookies to connect to your account.": "Włącz pliki cookie przeglądarki do połączenia z kontem.",
  "Learn more": "Ucz się więcej",
  "Print Button": "Wydrukuj przycisk",
  "Permit your users to print your Boom Event Calendar in any date range.": "Zezwalaj użytkownikom na wydrukowanie kalendarza zdarzenia wysięgnika w dowolnym zakresie dat.",
  "Show Title on mobile": "Pokaż tytuł na telefon komórkowy",
  "Show Skeleton on mobile": "Pokaż szkielet na telefonie komórkowym",
  "Start 7-day Business trial": "Uruchom 7-dniową wersję próbną",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Ciesz się wszystkimi nieograniczonymi funkcjami, takimi jak sprzedawać bilety, rejestracja, dodatki zdarzeń użytkownika.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Uwaga: Pod koniec okresu próbnego zostaniesz zwrócony do istniejącego planu subskrypcji.",
  "Not Now": "Nie teraz",
  "Start free trial": "Rozpocznij darmowy okres próbny",
  "Congrats!": "Gratulacje!",
  "Your 7-day Business trial has been successfully activated.": "Twój 7-dniowy proces biznesowy został pomyślnie aktywowany.",
  "Done": "Zrobione",
  "Title font color": "Tytułowy kolor czcionki",
  "Desciption font color": "Opis kolor czcionki",
  "Section font color": "Kolor czcionki sekcji",
  "Card Header": "Nagłówek kart",
  "Category": "Kategoria",
  "Display at the": "Wyświetlacz w The.",
  "top": "szczyt",
  "bottom": "na dole",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Pokaż filtr kategorii na górze lub na dole kalendarza.Ustawienia dotyczy tylko widoków programów i kart",
  "Processing your events": "Przetwarzanie wydarzeń",
  "Search for events": "Szukaj wydarzeń.",
  "There are no events added": "Nie ma żadnych zdarzeń",
  "Location: To be determined": "Lokalizacja: Do ustalenia",
  "No events for selected date": "Brak zdarzeń dla wybranej daty",
  "Uncategorized": "Bez kategorii",
  "Edit event": "Edytuj wydarzenie",
  "Edit original event": "Edytuj oryginalne wydarzenie",
  "Copy event": "Wydarzenie kopiowania",
  "Copy as new event": "Kopiuj jako nowe wydarzenie",
  "Delete event": "Usuń zdarzenie",
  "Stop repeating on this date": "Przestań powtarzać w tym dniu",
  "Exclude this date": "Wyklucz tę datę",
  "Location is going to be announced": "Lokalizacja zostanie ogłoszona",
  "Fill your personal information": "Wypełnij swoje dane osobowe",
  "Check Box": "Pole wyboru",
  "Single Choice": "Pojedynczy wybór",
  "Option": "Opcja",
  "Share Event": "Udostępnij wydarzenie",
  "Oops! Something went wrong": "Ups!Coś poszło nie tak",
  "We are sorry this event has already taken place": "Przykro nam, że to wydarzenie już miało miejsce",
  "Back to calendar": "Powrót do kalendarza",
  "This field is required": "To pole jest wymagane",
  "Phone": "Telefon",
  "Number field": "Pole liczbowe",
  "Option": "Opcja",
  "Check Box": "Pole wyboru",
  "Single Choice": "Pojedynczy wybór",
 "Please provide a valid email" : "Proszę podać ważny e -mail",
 "Select at least one option" : "Wybierz co najmniej jedną opcję",
 "Choose tickets to see total value" : "Wybierz bilety, aby zobaczyć całkowitą wartość",
 "tickets" : "bilety",
 "Choose Tickets" : "Wybierz bilety",
 "Choose payment method" : "Wybierz metodę płatności",
 "Pay" : "Płacić",
 "Total" : "Całkowity",
 "Free" : "Bezpłatny",
 "Buy tickets" : "Kup bilety",
 "Sold Out" : "Wyprzedane",
 "Tickets are available" : "Bilety są dostępne",
 "Sales End" : "Koniec sprzedaży",
 "Buy tickets" : "Kup bilety",
 "Availible from" : "dostępne od",
 "Go to Orders" : "Idź do zamówień",
 "Go to Details" : "Przejdź do szczegółów",
 "Group ticket" : "Bilet grupowy",
 "Name" : "Nazwa",
 "Price" : "Cena £",
 "Order by" : "Zamów przez",
 "Order ID" : "Identyfikator zamówienia",
 "Group ticket" : "Bilet grupowy",
 "Name" : "Nazwa",
 "Price" : "Cena £",
 "Order by" : "Zamów przez",
 "Order ID" : "Identyfikator zamówienia",
 "Applied" : "Stosowany",
 "Fees" : "Opłaty",
 "Enter promo code" : "Wpisz kod promocyjny",
 "Apply" : "Stosować",
 "Promo Code" : "Kod promocyjny",
 "Cash" : "Gotówka",
 "You can find your e-tickets attached to your email or download them" : "Możesz znaleźć e-bilety dołączone do e-maila lub pobrać je",
 "here" : "tutaj",
 "Time" : "Czas",
 "Invalid promo code" : "Nieprawidłowy kod promocyjny",
 "Credit card" : "Karta kredytowa",
 "You will soon receive a confirmation message of successful registration to your email address." : "Wkrótce otrzymasz wiadomość potwierdzającą udaną rejestrację na swój adres e -mail.",
 "You can also check your order details below." : "Możesz także sprawdzić szczegóły zamówienia poniżej.",
 "at" : "w"
}
export default pl