let pt = {
  "Categories": "Categorias",
  "Share this event": "Compartilhar este evento",
  "Language": "Língua",
  "Show Time Zone": "Mostrar fuso horário",
  "Custom Local Settings": "Configurações locais personalizadas",
  "Add and showcase events on your site using a beautiful calendar.": "Adicione e exiba eventos em seu site usando um calendário bonito . ",
  "Week Days": "Dias úteis",
  "Manage Events": "Gerenciar Eventos",
  "General": "Geral",
  "Layout Picker": "Selecionador de Layout",
  "Month": "Mês",
  "Monthly": "Por mês",
  "Week": "Semana",
  "Weekly": "Semanal",
  "Day": "Dia",
  "Daily": "Diariamente",
  "Agenda": "Agenda",
  "Navigation Buttons": "Botões de Navegação",
  "Week numbers": "Números da semana",
  "Include Weekends": "Incluir fins de semana",
  "All-day": "Dia todo",
  "All Day": "Dia todo",
  "Label": "Rótulo",
  "Fit to Height": "Ajustar à altura",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Para definir proporções App manully desabilitar essa opção e redimensionar Calendário no Editor. ",
  "Default Layout": "Layout padrão",
  "Monthly view": "Visualização mensal",
  "Weekly and Daily view": "Vista semanal e diária",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Você pode oferecer aos visitantes uma experiência mais consistente, mostrando o mesmo número de semanas ( 6) de cada vez.",
  "Fixed Weekly Layout": "Layout Semanal Fixo",
  "back": "de volta ",
  "Row": "Linha",
  "Hours in Weekly View": "Horas na Vista Semanal",
  "Hours in Daily View": "Horas na visualização diária",
  "Start": "Começar",
  "End": "Fim",
  "At This Hour": "Nesta hora",
  "Button": "Botão",
  "Buttons": "Botões",
  "Sunday": "Domingo",
  "Monday": "Segunda-feira",
  "Tuesday": "Terça",
  "Wednesday": "Quarta-feira",
  "Thursday": " Quinta-feira ",
  "Friday": "Sexta-feira",
  "Saturday": "Sábado",
  "Default Date": "Data padrão",
  "year": " ano ",
  "month": " mês ",
  "days": " dias ",
  "ago": " ago ",
  "ahead": " à frente ",
  "Yesterday": "Ontem",
  "Today": "Hoje",
  "Tomorrow": "Amanhã",
  "Custom": "Personalizadas",
  "Set Daily Rows Limit": "Definir Limite de Linhas Diárias",
  "Set Proportions": "Definir Proporções",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Permitir que o visitante adicione o evento aos Calendários locais , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Recipiente",
  "Background": "Fundo",
  "Container Background": "Fundo do recipiente",
  "Container Borders": "Fronteiras do contêiner",
  "Calendar": "Calendário",
  "Event Info Tooltip": "Event Info Tooltip",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Quando as pessoas passam o mouse sobre um evento, elas verão todas as informações sobre ele em uma dica de ferramenta. ",
  "Event Info Window": "Janela de Informações do Evento",
  "This is the full information window that opens when someone clicks on the event.": "Esta é a janela de informações completa que se abre quando alguém clica no evento. ",
  "Use Gradient": "Use Gradient",
  "Vertical": "Vertical",
  "Horizontal": "Horizontal",
  "First": "Primeiro",
  "Second": "Segundo",
  "diagonal": " diagonal ",
  "Radial": "Radial",
  "Select option": "Selecionar opção",
  "Solid": "Sólido",
  "Dotted": "Pontilhado",
  "Dashed": "Tracejadas",
  "Double": "Em dobro",
  "Border Radius": "Raio da Borda",
  "Padding": "Preenchimento",
  "Date Header": "Data de cabeçalho",
  "Event Default Color": "Cor Padrão do Evento",
  "Days of Week": "Dias da semana",
  "Days of Week Background": "Dias de fundo da semana",
  "Date": "Encontro",
  "Event Title": "Título do evento",
  "Highlight today": "Destaque hoje",
  "Highlight Color": "Cor de destaque",
  "Hide": "Ocultar",
  "Calendar Border Color": "Calendar Border Color",
  "Calendar Border Width": "Largura do limite do calendário",
  "Calendar Border Style": "Estilo de borda do calendário",
  "Font Color": "Cor da fonte",
  "Event Background": "Antecedentes do Evento",
  "Card Date Color": "Cor da data do cartão",
  "Title Font": "Fonte do título",
  "Date Font": "Data da fonte",
  "Description Font": "Descrição da fonte",
  "Button Background": "Botão de fundo",
  "Button Text": "Botão de texto",
  "Border Color": "Cor da borda",
  "Border Width": "Largura da Fronteira",
  "Border Type": "Tipo de Borda",
  "Title": "Título",
  "Description": "Descrição",
  "Background Color": "Cor de fundo",
  "Divider": "Divisor",
  "Event Details Font": "Fonte de detalhes do evento",
  "Website Link Color": "Website Link Color",
  "Developer Info": "Informações do desenvolvedor",
  "User Guide": "Guia de usuario",
  "Support e-mail": "Suporte e-mail",
  "Our Website": "Nosso site",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.": "Desfrutando App? Deixe-nos um comentário no App Market. ",
  "Review Us": "Revise-nos",
  "Connect With Us": "Conecte-se conosco",
  "What's your email?": "Qual é o seu email? ",
  "Invalid email address!": "Endereço de email inválido! ",
  "Comments": "Comentários",
  "We'd love to hear from you. Send us a message.": "Gostaríamos muito de ouvir de você. Envie-nos uma mensagem. ",
  "Message must be at least 5 characters long": "A mensagem deve ter pelo menos 5 caracteres",
  "Send": "Mandar",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Se você quiser permitir que o usuário alterne entre exibições de calendário, ative esta opção e escolha as exibições que deseja exibir. ",
  "Main": "a Principal",
  "Localize": "Localizar",
  "Settings": "Definições",
  "Layouts": "Plano",
  "Advanced": "Avançado",
  "Design": "desenhar",
  "Support": "Apoio, suporte",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Todas as configurações locais são (automaticamente) baseadas no seu idioma. Se o seu idioma estiver na lista, não há necessidade de personalizar esta seção.",
  "Date Format": "Formato de data",
  "Time Format": "Formato de hora",
  "Text Direction": "Direção do texto",
  "Left to Right": "Esquerda para a direita",
  "Right to Left": "Direita para esquerda",
  "Week Starts On": "Semana começa em",
  "Agenda Style": "Agenda Style",
  "Classic": "Clássico",
  "Modern": "Moderno",
  "Agenda Header": "Cabeçalho da agenda",
  "Upcoming Events": "Próximos eventos",
  "Agenda Event Limit": "Limite de eventos da agenda",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Atualize agora e tenha muito mais recursos e aproveite seu aplicativo na íntegra!",
  "Upgrade Now": "Atualize agora",
  "Hosting events that last all day? This lets you show them on your calendar.": "Eventos de hospedagem que duram o dia todo? Isso permite que você os mostre no seu calendário.",
  "24 hours": "24 horas",
  "Sun": "Dom",
  "Mon": "Seg",
  "Sat": "Sáb",
  "Default": "Padrão",
  "Select custom design style for your calendar.": "Selecione o estilo de design personalizado para o seu calendário.",
  "Style": "Estilo",
  "Styles and Colors": "Estilos e cores",
  "Calendar Name": "Nome do calendário",
  "Write your Calendar name here": "Escreva aqui o nome do seu calendário",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Isso não é visível para seus usuários. Defina nomes para diferenciar seus calendários ao usar a função Boom Calendar Sync.",
  "General Info": "Informações gerais",
  "Venue": "Local",
  "Organizer": "Organizador",
  "Search": "Procurar",
  "Add to": "Adicionar à",
  "calendar": "calendário",
  "Copy event URL": "Copiar URL do evento",
  "Copied!": "Copiado!",
  "Add & Share": "Adicionar e compartilhar",
  "Map": "Mapa",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  "Uncategorised": "Sem categoria",
  "More": "Mais",
  "Less": "Menos",
  "Register": "Registro",
  "Card": "Cartão",

  "Guests": "Convidados",
  "unlimited": "ilimitado",
  "Show more": "Mostre mais",
  "Enable Search": "Ativar pesquisa",
  "+ Add Event": "+ Adicionar evento",
  "Manage and Sync": "Gerenciar e sincronizar",
  "Show event details as...": "Mostrar detalhes do evento como ...",
  "Tooltip": "Sugestão",
  "Popup": "Caixa de informação",
  "None": "Nenhum",
  "Show Category": "Mostrar categoria",
  "Header Align": "Alinhamento de cabeçalho",
  "Show Time": "Altura de começar",
  "Hours in Weekly/Daily View": "Horas na exibição semanal / diária",
  "Share Events": "Compartilhar Eventos",
  "Shadow": "Sombra",
  "Inner Padding": "Estofamento interno",
  "Text": "Texto",
  "Active Button Border": "Borda do botão ativo",
  "Light Mode": "Modo de luz",
  "Event Text Color": "Cor do texto do evento",
  "Dates": "datas",
  "Skeleton": "Esqueleto",
  "Skeleton Color": "Cor do esqueleto",
  "Width": "Largura",
  "Skeleton Style": "Estilo esqueleto",
  "Color": "Cor",
  "Section Titles": "Títulos da Seção",
  "Section Content": "Conteúdo da seção",
  "Header": "Cabeçalho",
  "Standard": "Padrão",
  "Retro": "Retro",
  "Silver": "Prata",
  "Night": "Noite",
  "Dark": "Sombrio",
  "Aubergine": "Beringela",
  "Map Header": "Cabeçalho do Mapa",
  "Show Title in mobile": "Mostrar título no celular",
  "Card View": "Visualização de cartão",
  "Card background color": "Cor de fundo do cartão",
  "Title font": "Fonte do título",
  "Desciption font": "Fonte de descrição",
  "Section font": "Seção de fonte",
  "Section divider color": "Cor do divisor de seção",
  "Add event": "Adicionar Evento",
  "All Day Event": "Evento de dia inteiro",
  "Location": "Localização",
  "Choose a category": "Escolha uma categoria",
  "Venue name": "Nome do local",
  "Venue phone": "Telefone local",
  "Venue email": "Email do local",
  "Venue website": "Site do local",
  "Organizer name": "Nome do organizador",
  "Organizer phone": "Telefone organizador",
  "Organizer email": "Email do organizador",
  "Organizer website": "Site do organizador",
  "Personal info": "Informação pessoal",
  "First name": "Primeiro nome",
  "Last name": "Último nome",
  "Email Address": "Endereço de e-mail",
  "Additional Notes": "Notas Adicionais",
  "Back": "Costas",
  "Save": "Salve ",
  "Next": "Próximo",
  "Your event has been submitted": "Seu evento foi enviado",
  "Event submittion has been failed": "O envio do evento falhou",
  "e.g. Birthday Party": "por exemplo. Festa de aniversário",
  "First Name": "Primeiro nome",
  "Last Name": "Último nome",
  "Phone Number": "Número de telefone",
  "Address": "Endereço",
  "Your comments": "Os teus comentários",
  "How many guests?": "Quantos convidados?",
  "Anything else we need to know?": "Mais alguma coisa que precisamos saber?",
  "Guests:": "Convidados:",
  "Submit": "Enviar",
  "Go to Calendar": "Vá para o calendário",
  "Registration completed successfully!": "Registro concluído com sucesso!",
  "Please check your registered email address": "Por favor, verifique o seu endereço de e-mail registrado",
  "Add to Calendar": "Adicionar ao calendário",
  "Share this Event": "Compartilhar este evento",
  "Sorry something went wrong": "Desculpe, algo deu errado",
  "Back to registration": "กลับไปที่การลงทะเบียน",
  "Date & Location": "Data e local",
  "Date & Time": "Data hora",
  "home": "casa",
  "Header align": "Cabeçalho alinhar",
  "Footer": "Rodapé",
  "Categories Filter": "filtro de categorias",
  "Show only upcoming": "Mostrar apenas os próximos",
  "Card(s) in a row": "Cartão (s) em uma linha",
  "Space between cards": "Espaço entre cartas",
  "Shown events limit": "Limite de eventos mostrados",
  "Style 1": "Estilo 1",
  "Style 2": "Estilo 2",
  "Style 3": "Estilo 3",
  "Style 4": "Estilo 4",
  "Buttons & Links": "Botões e links",
  "Button corner radius": "Raio do canto do botão",
  "Buttons font": "Fonte de botões",
  "Buttons background": "Fundo dos botões",
  "Get notified by Email": "Seja notificado por e-mail",
  "Review events": "Rever eventos",
  "Click on date": "Clique na data",
  "Add Event button": "Botão Adicionar Evento",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "A sincronização do calendário permite que você integre seus eventos e sessões com o seu calendário Boom.",
  "connect": "conectar",
  "Synchronized Calendars": "Calendários sincronizados",
  "Import events": "Importar eventos",
  "Disconnect": "desconectar",
  "Choose calendar": "Escolha o calendário",
  "Monitor your Wix events through the sync feature": "Monitore seus eventos Wix por meio do recurso de sincronização",
  "Connect all your Boom calendars available on your website": "Conecte todos os seus calendários Boom disponíveis em seu site",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Agende, participe e gerencie reuniões do Zoom direto por meio do nosso Calendário Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Monitore seus eventos do Event Brite por meio do recurso de sincronização do Event Brite",
  "Email": "O email",
  "Add-ons": "Add-ons",
  "Receive notification emails as soon as users add events to your calendar.": "Receba e-mails de notificação assim que os usuários adicionem eventos ao seu calendário.",
  "Enable + button on the calendar header": "Ativar + botão no cabeçalho do calendário",
  "Accept or decline events added by customers before making them public.": "Aceitar ou recusar eventos adicionados pelos clientes antes de torná-los públicos.",
  "Switch Add Event": "Switch adicionar evento",
  "Enable your browser cookies to connect to your account.": "Ative seus cookies do navegador para se conectarem à sua conta.",
  "Learn more": "Saber mais",
  "Print Button": "Botão de impressão",
  "Permit your users to print your Boom Event Calendar in any date range.": "Permita que seus usuários imprimem seu calendário de eventos de boom em qualquer intervalo de datas.",
  "Show Title on mobile": "Mostrar título no celular",
  "Show Skeleton on mobile": "Mostrar esqueleto no celular",
  "Start 7-day Business trial": "Comece seu teste de negócios de 7 dias",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Aproveite todos os recursos ilimitados, como ingressos de venda, inscrição, add-ons de eventos de visitantes.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Por favor, note: No final do período de teste, você será devolvido ao seu plano de assinatura existente.",
  "Not Now": "Agora não",
  "Start free trial": "Iniciar teste gratuito",
  "Congrats!": "Parabéns!",
  "Your 7-day Business trial has been successfully activated.": "Seu teste de negócios de 7 dias foi ativado com sucesso.",
  "Done": "Feita",
  "Title font color": "Cor da fonte do título.",
  "Desciption font color": "Descrição Cor da fonte",
  "Section font color": "Cor da fonte de seção",
  "Card Header": "Cabeçalho de cartão",
  "Category": "Categoria",
  "Display at the": "Exibir no",
  "top": "principal",
  "bottom": "fundo",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Showcase o filtro de categoria na parte superior ou na parte inferior do calendário.As configurações se aplica apenas à agenda e visualizações de cartão",
  "Processing your events": "Processando seus eventos",
  "Search for events": "Procure por eventos",
  "There are no events added": "Não há eventos adicionados",
  "Location: To be determined": "Localização: para ser determinado",
  "No events for selected date": "Nenhum evento para a data selecionada",
  "Uncategorized": "Sem categoria",
  "Edit event": "Evento de edição",
  "Edit original event": "Edite o evento original",
  "Copy event": "Evento de cópia",
  "Copy as new event": "Cópia como novo evento",
  "Delete event": "Excluir evento",
  "Stop repeating on this date": "Pare de repetir nesta data",
  "Exclude this date": "Exclua esta data",
  "Location is going to be announced": "A localização será anunciada",
  "Fill your personal information": "Preencha suas informações pessoais",
  "Check Box": "Caixa de seleção",
  "Single Choice": "Escolha única",
  "Option": "Opção",
  "Share Event": "Evento de compartilhamento",
  "Oops! Something went wrong": "Opa!Algo deu errado",
  "We are sorry this event has already taken place": "Lamentamos que este evento já tenha ocorrido",
  "Back to calendar": "De volta ao calendário",
  "This field is required": "Este campo é obrigatório",
  "Phone": "Telefone",
  "Number field": "Campo numérico",
  "Option": "Opção",
  "Check Box": "Caixa de seleção",
  "Single Choice": "Escolha única",
 "Please provide a valid email" : "Por favor forneça um email válido",
 "Select at least one option" : "Selecione pelo menos uma opção",
 "Choose tickets to see total value" : "Escolha ingressos para ver o valor total",
 "tickets" : "ingressos",
 "Choose Tickets" : "Escolha ingressos",
 "Choose payment method" : "escolha o método de pagamento",
 "Pay" : "Pagar",
 "Total" : "Total",
 "Free" : "Livre",
 "Buy tickets" : "Comprar bilhetes",
 "Sold Out" : "Vendido",
 "Tickets are available" : "Os ingressos estão disponíveis",
 "Sales End" : "Vendas terminam"
}
export default pt