let ru = {
  "Categories": "Категории",
  "Share this event": "Поделиться этим событием",
  "Language": "Язык",
  "Show Time Zone": "Показать часовой пояс",
  "Custom Local Settings": "Пользовательские локальные настройки",
  "Add and showcase events on your site using a beautiful calendar.": "Добавляйте и демонстрируйте события на своем сайте, используя красивый календарь.",
  "Week Days": "Будние дни",
  "Manage Events": "Управление событиями",
  "General": "Генеральный",
  "Layout Picker": "Выбор макета",
  "Month": "Месяц",
  "Monthly": "Ежемесячно",
  "Week": "Неделя",
  "Weekly": "Еженедельно",
  "Day": "День",
  "Daily": "Ежедневно",
  "Agenda": "Повестка дня",
  "Navigation Buttons": "Кнопки навигации",
  "Week numbers": "Номера недели",
  "Include Weekends": "Включить выходные",
  "All-day": "Весь день",
  "All Day": "Весь день",
  "Label": "Этикетка",
  "Fit to Height": "Подходит к высоте",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Чтобы установить пропорции приложения, вручную отключите эту опцию и измените размер календаря в редакторе.",
  "Default Layout": "Макет по умолчанию",
  "Monthly view": "Ежемесячный просмотр",
  "Weekly and Daily view": "Еженедельный и ежедневный просмотр",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "Вы можете дать посетителям более последовательный опыт, показывая одинаковое количество недель (6) за раз.",
  "Fixed Weekly Layout": "Фиксированный недельный макет",
  "back": "назад",
  "Row": "Строка",
  "Hours in Weekly View": "Часы в недельном обзоре",
  "Hours in Daily View": "Часы в ежедневном просмотре",
  "Start": "Начало",
  "End": "Конец",
  "At This Hour": "в этот час",
  "Button": "Кнопка",
  "Buttons": "Кнопки",
  "Sunday": "Воскресенье",
  "Monday": "Понедельник",
  "Tuesday": "Вторник",
  "Wednesday": "Среда",
  "Thursday": "Четверг",
  "Friday": "Пятница",
  "Saturday": "Суббота",
  "Default Date": "Дата по умолчанию",
  "year": "год",
  "month": "месяц",
  "days": "дней",
  "ago": "тому назад",
  "ahead": "впереди",
  "Yesterday": "Вчера",
  "Today": "Сегодня",
  "Tomorrow": "Завтра",
  "Custom": "Обычай",
  "Set Daily Rows Limit": "Установить дневной лимит строк",
  "Set Proportions": "Установите пропорции",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Разрешить посетителю добавлять события в локальные Calnedars: Google, Yahoo, Outlook, ICalendar.",
  "Container": "Контейнер",
  "Background": "Фон",
  "Container Background": "Фон Контейнерa",
  "Container Borders": "Контейнерные границы",
  "Calendar": "Календарь",
  "Event Info Tooltip": "Информация о событии",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "Когда люди наводят курсор на событие, они видят всю информацию о нем во всплывающей подсказке.",
  "Event Info Window": "Окно информации о событии",
  "This is the full information window that opens when someone clicks on the event.": "Это окно полной информации, которое открывается, когда кто-то нажимает на событие.",
  "Use Gradient": "Использовать градиент",
  "Vertical": "Вертикальный",
  "Horizontal": "Горизонтальный",
  "First": "Первый",
  "Second": "Второй",
  "diagonal": "Диагональ",
  "Radial": "Радиальный",
  "Select option": "Выберите опцию",
  "Solid": "Сплошной",
  "Dotted": "Пунктирный",
  "Dashed": "Пунктирная",
  "Double": "Двойной",
  "Border Radius": "Пограничный радиус",
  "Padding": "Ннабивка",
  "Date Header": "Заголовок даты",
  "Event Default Color": "Цвет события по умолчанию",
  "Days of Week": "Дни недели",
  "Days of Week Background": "Фон дней недель",
  "Date": "Свидание",
  "Event Title": "Название события",
  "Highlight today": "Выделите сегодня",
  "Highlight Color": "Цвет подсветки",
  "Hide": "Спрятать",
  "Calendar Border Color": "Цвет границы календаря",
  "Calendar Border Width": "Ширина границы календаря",
  "Calendar Border Style": "Стиль Границы Календаря",
  "Font Color": "Цвет шрифта",
  "Event Background": "Фон события",
  "Card Date Color": "Цвет даты карты",
  "Title Font": "Название шрифта",
  "Date Font": "Дата Шрифта",
  "Description Font": "Описание шрифта",
  "Button Background": "Фон кнопки",
  "Button Text": "Текст кнопки",
  "Border Color": "Цвет границы",
  "Border Width": "Ширина рамки",
  "Border Type": "Тип границы",
  "Title": "Заглавие",
  "Description": "Описание",
  "Background Color": "Фоновый цвет",
  "Divider": "Делитель",
  "Event Details Font": "Событие Подробнее Шрифт",
  "Website Link Color": "Цвет Ссылки на Сайт",
  "Developer Info": "Информация про разработчиков",
  "User Guide": "Гид Пользователя",
  "Support e-mail": "Поддержка по e-mail",
  "Our Website": "Наш Сайт",
  "App Review": "Обзор приложения",
  "Enjoying App? Leave us a review in the App Market.": "Наслаждаешься приложением? Оставьте нам отзыв в App Market.",
  "Review Us": "Обзор",
  "Connect With Us": "Связаться с нами",
  "What's your email?": "Какой у тебя адрес электронной почты?",
  "Invalid email address!": "Неверный адрес электронной почты!",
  "Comments": "Комментарии",
  "We'd love to hear from you. Send us a message.": "Мы хотели бы услышать от вас. Отправьте нам сообщение.",
  "Message must be at least 5 characters long": "Сообщение должно быть не менее 5 символов",
  "Send": "Отправить",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Если вы хотите, чтобы пользователь мог переключаться между представлениями календаря, включите эту опцию и выберите представления, которые вы хотите показать.",
  "Main": "Главный",
  "Localize": "Локализировать",
  "Settings": "Настройки",
  "Layouts": "Макеты",
  "Advanced": "Продвинутый",
  "Design": "Дизайн",
  "Support": "Служба поддержки",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Все локальные настройки (автоматически) основаны на вашем языке. Если ваш язык есть в списке, нет необходимости настраивать этот раздел.",
  "Date Format": "Формат даты",
  "Time Format": "Формат времени",
  "Text Direction": "Направление текста",
  "Left to Right": "Слева направо",
  "Right to Left": "Справа налево",
  "Week Starts On": "Неделя начинается",
  "Agenda Style": "Стиль Повестки дня",
  "Classic": "классический",
  "Modern": "Современный",
  "Agenda Header": "Повестка дня",
  "Upcoming Events": "Предстоящие События",
  "Agenda Event Limit": "Предел Событий Повестки дня",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Обновите сейчас и получите гораздо больше возможностей и наслаждайтесь вашим приложением в полном объеме!",
  "Upgrade Now": "Обнови сейчас",
  "Hosting events that last all day? This lets you show them on your calendar.": "Хостинг событий, которые длятся весь день? Это позволяет вам показывать их в своем календаре",
  "24 hours": "24 часа",
  "Sat": "Суб",
  "Sun": "Вос",
  "Mon": "Пон",
  "Default": "По умолчанию",
  "Select custom design style for your calendar.": "Выберите индивидуальный стиль дизайна для вашего календаря.",
  "Style": "Стиль",
  "Styles and Colors": "Стили и Цвета",
  "Calendar Name": "Название календаря",
  "Write your Calendar name here": "Напишите здесь название вашего календаря",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Это не видно вашим пользователям. Задайте имена, чтобы дифференцировать календари при использовании функции синхронизации календаря Boom.",
  "General Info": "Главная информация",
  "Venue": "Место встречи",
  "Organizer": "Организатор",
  "Search": "Поиск",
  "Add to": "Добавить в",
  "calendar": "календарь",
  "Copy event URL": "Скопировать URL события",
  "Copied!": "Скопировано!",
  "Add & Share": "Добавить и поделиться",
  "Map": "карта",
  "Calendar view": "Просмотр календаря",
  "Add Event": "Добавить событие",
  "Uncategorised": "Без категории",
  "More": "Больше",
  "Less": "Меньше",
  "Register": "регистр",
  "Card": "Карта",

  "Guests": "Гости",
  "unlimited": "неограниченный",
  "Show more": "Показать больше",
  "Enable Search": "Включить поиск",
  "+ Add Event": "+ Добавить событие",
  "Manage and Sync": "Управление и синхронизация",
  "Show event details as...": "Показать детали события как ...",
  "Tooltip": "подсказка",
  "Popup": "Информационное поле",
  "None": "Никто",
  "Show Category": "Показать категорию",
  "Header Align": "Выровнять заголовок",
  "Show Time": "Время для шоу",
  "Hours in Weekly/Daily View": "Часы в еженедельном / ежедневном просмотре",
  "Share Events": "Поделиться событиями",
  "Shadow": "Тень",
  "Inner Padding": "Внутренняя обивка",
  "Text": "Текст",
  "Active Button Border": "Граница активной кнопки",
  "Light Mode": "Легкий режим",
  "Event Text Color": "Цвет текста события",
  "Dates": "Даты",
  "Skeleton": "остов",
  "Skeleton Color": "Цвет скелета",
  "Width": "Ширина",
  "Skeleton Style": "Ширина",
  "Color": "Цвет",
  "Section Titles": "Заголовки разделов",
  "Section Content": "Содержание раздела",
  "Header": "заголовок",
  "Standard": "Стандарт",
  "Retro": "Ретро",
  "Silver": "Серебряный",
  "Night": "Ночь",
  "Dark": "Тьма",
  "Aubergine": "Баклажан",
  "Map Header": "Заголовок карты",
  "Show Title in mobile": "Показать заголовок на мобильном устройстве",
  "Card View": "Карточка",
  "Card background color": "Цвет фона карты",
  "Title font": "Шрифт заголовка",
  "Desciption font": "Шрифт описания",
  "Section font": "Раздел шрифтов",
  "Section divider color": "Цвет разделителя секции",
  "Add event": "Добавить мероприятие",
  "All Day Event": "Событие на весь день",
  "Location": "Место расположения",
  "Choose a category": "Выберите категорию",
  "Venue name": "Название объекта",
  "Venue phone": "Телефон места проведения",
  "Venue email": "Адрес места проведения",
  "Venue website": "Сайт объекта",
  "Organizer name": "Название организатора",
  "Organizer phone": "Телефон-органайзер",
  "Organizer email": "Электронная почта организатора",
  "Organizer website": "Сайт организатора",
  "Personal info": "Личная информация",
  "First name": "Имя",
  "Last name": "Фамилия",
  "Email Address": "Адрес электронной почты",
  "Additional Notes": "Дополнительные примечания",
  "Back": "Назад",
  "Save": "Сохранить",
  "Next": "Следующий",
  "Your event has been submitted": "Ваше мероприятие отправлено",
  "Event submittion has been failed": "Отправка события не удалась",
  "e.g. Birthday Party": "например. День рождения",
  "First Name": "Имя",
  "Last Name": "Фамилия",
  "Phone Number": "Телефонный номер",
  "Address": "Адрес",
  "Your comments": "Your comments",
  "How many guests?": "Сколько гостей?",
  "Anything else we need to know?": "Anything else we need to know?",
  "Guests:": "Гости:",
  "Submit": "Разместить",
  "Go to Calendar": "Перейти в календарь",
  "Registration completed successfully!": "Registration completed successfully!",
  "Please check your registered email address": "Пожалуйста, проверьте свой зарегистрированный а��рес электронной почты",
  "Add to Calendar": "Добавить в календарь",
  "Share this Event": "Поделиться этим событием",
  "Sorry something went wrong": "Извините, что-то пошло не так",
  "Back to registration": "Повернутися до реєстрації",
  "Date & Location": "Дата и местоположение",
  "Date & Time": "Дата и время",
  "home": "дома",
  "Header align": "Выровнять заголовок",
  "Footer": "Нижний колонтитул",
  "Categories Filter": "категории Фильтр",
  "Show only upcoming": "Показать только предстоящие",
  "Card(s) in a row": "Карточка (ы) подряд",
  "Space between cards": "Расстояние между карточками",
  "Shown events limit": "Лимит показанных событий",
  "Style 1": "Стиль 1",
  "Style 2": "Стиль 2",
  "Style 3": "Стиль 3",
  "Style 4": "Стиль 4",
  "Buttons & Links": "Кнопки и ссылки",
  "Button corner radius": "Радиус угла кнопки",
  "Buttons font": "Шрифт кнопок",
  "Buttons background": "Кнопки фон",
  "Get notified by Email": "Получить уведомление по электронной почте",
  "Review events": "Обзор событий",
  "Click on date": "Нажмите на дату",
  "Add Event button": "Добавить кнопку события",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Синхронизация календаря позволяет вам интегрировать ваши события и сеансы с вашим календарем Boom.",
  "connect": "соединять",
  "Synchronized Calendars": "Синхронизированные календари",
  "Import events": "Импортировать события",
  "Disconnect": "Отключить",
  "Choose calendar": "Выбрать календарь",
  "Monitor your Wix events through the sync feature": "Следите за своими событиями Wix с помощью функции синхронизации",
  "Connect all your Boom calendars available on your website": "Подключите все свои календари Boom, доступные на вашем сайте",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Планируйте, присоединяйтесь и управляйте собраниями Zoom прямо в нашем календаре Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Следите за событиями Event Brite с помощью функции синхронизации Event Brite",
  "Email": "Электронное письмо",
  "Add-ons": "Дополнения",
  "Receive notification emails as soon as users add events to your calendar.": "Получите уведомления писем, как только пользователи добавляют события в свой календарь.",
  "Enable + button on the calendar header": "Включить + кнопку на заголовке календаря",
  "Accept or decline events added by customers before making them public.": "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Переключатель Добавить событие",
  "Enable your browser cookies to connect to your account.": "Включите файлы файлов Browser для подключения к вашей учетной записи.",
  "Learn more": "Учить больше",
  "Print Button": "Tryckknapp",
  "Permit your users to print your Boom Event Calendar in any date range.": "Разрешите своим пользователям распечатать календарь событий Boom в любой диапазон даты.",
  "Show Title on mobile": "Показать название на мобильном",
  "Show Skeleton on mobile": "Показать скелет на мобильном",
  "Start 7-day Business trial": "Начните свой 7-дневный бизнес-проб",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Наслаждайтесь всеми неограниченными функциями, такими как билеты на продажу, регистрация, дополнение событий для посетителей.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Обратите внимание: в конце пробного периода вы будете возвращены в ваш существующий план подписки.",
  "Not Now": "Не сейчас",
  "Start free trial": "Начать бесплатную пробную версию",
  "Congrats!": "Поздравляю!",
  "Your 7-day Business trial has been successfully activated.": "Ваше 7-дневное деловое испытание было успешно активировано.",
  "Done": "Готово",
  "Title font color": "Заголовок шрифта цвета",
  "Desciption font color": "Описание Цвет шрифта",
  "Section font color": "Раздел шрифта цвета",
  "Card Header": "Заголовок карты",
  "Category": "Категория",
  "Display at the": "Отображать на то",
  "top": "Топ",
  "bottom": "Нижний",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Продемонстрируйте фильтр категории сверху или в нижней части календаря.Настройки применяются только к представлениям повестки дня и открытки",
  "Processing your events": "Обработка ваших событий",
  "Search for events": "Поиск событий",
  "There are no events added": "Нет добавленных событий",
  "Location: To be determined": "Расположение: быть определенным",
  "No events for selected date": "Нет событий для выбранной даты",
  "Uncategorized": "Без рубрики",
  "Edit event": "Редактировать событие",
  "Edit original event": "Редактировать оригинальное событие",
  "Copy event": "Копировать событие",
  "Copy as new event": "Копировать как новое событие",
  "Delete event": "Удалить событие",
  "Stop repeating on this date": "Перестань повторять в эту дату",
  "Exclude this date": "Исключить эту дату",
  "Location is going to be announced": "Место будет объявлено",
  "Fill your personal information": "Заполните свою личную информацию",
  "Check Box": "Флажок",
  "Single Choice": "Один выбор",
  "Option": "Вариант",
  "Share Event": "Поделиться событием",
  "Oops! Something went wrong": "Уп!Что-то пошло не так",
  "We are sorry this event has already taken place": "Мы сожалеем, что это событие уже состоялось",
  "Back to calendar": "Вернуться в календарь",
  "This field is required": "Это поле обязательно к заполнению",
  "Phone": "Телефон",
  "Number field": "Поле числа",
  "Option": "Вариант",
  "Check Box": "Флажок",
  "Single Choice": "Один выбор"
}
export default ru