let tr = {

   /* add event pop-up start*/
  "e.g. Birthday Party": "Örneğin. Doğum günü partisi",
  "Organizer": "Organizatör",
  "Location is going to be announced": "Konum duyurulacak",
  "Add Event": "Etkinlik ekle",
  "All Day Event": "Tüm gün aktivitesi",
  "Location": "Yer",   
  "General Info": "Genel Bilgi",
  "Description": "Açıklama",
  "Next": "Sonraki",
   "Make your contribution by adding your event to the calendar" : "Etkinliğinizi takvime ekleyerek katkınızı yapın",
 "Event name" : "Etkinlik ismi",
 "Start time" : "Başlangıç ​​saati",
 "End time" : "Bitiş zamanı",
 "Physical location" : "Fiziksel konum",
 "Online" : "İnternet üzerinden",
 "To be announced" : "Açıklanacak",
 "Add Image" : "Resim eklemek",
 "Event color" : "Olay rengi",
 "Choose categories" : "Kategorileri Seçin",
 "There are no categories to select" : "Seçilecek kategori yok",
 "Location name" : "Yer ismi",
 "Location email" : "Konum e -posta",
 "Location phone" : "Konum Telefon",
 "Location website" : "Yer · Web sitesi",
 "Organizer name" : "Organizatör adı",
 "Organizer phone" : "Organizatör telefon",
 "Organizer email" : "Organizatör e -postası",
 "Organizer website" : "Organizatör web sitesi",
 "Add meeting link" : "Toplantı Bağlantısı Ekle",
 "Choose category" : "Kategori Seçin",
 "Cancel" : "İptal",
 "Publish" : "Yayınla",
  /* add event pop-up end*/


  "Categories": "Kategoriler",
  "Share this event": "Bu etkinliği paylaş",
  "Language": "Dil",
  "Show Time Zone": "Saat Dilimini Göster",
  "Custom Local Settings": "Özel Yerel Ayarlar",
  "Add and showcase events on your site using a beautiful calendar.": "Güzel bir takvim kullanarak sitenize etkinlik ekleyin ve sergileyin . ",
  "Week Days": "Hafta içi",
  "Manage Events": "Etkinlikleri Yönet",
  "General": "Genel",
  "Layout Picker": "Düzen Seçici",
  "Month": "Ay",
  "Monthly": "Aylık",
  "Week": "Hafta",
  "Weekly": "Haftalık",
  "Day": "Gün",
  "Daily": "Günlük",
  "Agenda": "Gündem",
  "Navigation Buttons": "Yön tuşları",
  "Week numbers": "Hafta numaraları",
  "Include Weekends": "Hafta Sonlarını Dahil Et",
  "All-day": "Tüm gün",
  "All Day": "Tüm gün",
  "Label": "Etiket",
  "Fit to Height": "Yüksekliğe Sığdır",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "Uygulama oranlarını ayarlamak için bu seçeneği manüel olarak devre dışı bırakın ve Takvimi Editör'de Yeniden Boyutlandırın. ",
  "Default Layout": "Varsayılan Düzen",
  "Monthly view": "Aylık görünüm",
  "Weekly and Daily view": "Haftalık ve Günlük görünüm",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": " Bir kerede aynı haftaları ( 6) göstererek ziyaretçilere daha tutarlı bir deneyim sunabilirsiniz .",
  "Fixed Weekly Layout": "Sabit Haftalık Düzen",
  "back": " geri ",
  "Row": "Kürek çekmek",
  "Hours in Weekly View": "Haftalık Görünümde Saatler",
  "Hours in Daily View": "Günlük Görünümde Saatler",
  "Start": "Başlat",
  "End": "Son",
  "At This Hour": "Bu saatte",
  "Button": "Buton",
  "Buttons": "Düğmeler",
  "Sunday": "Pazar",
  "Monday": "Pazartesi",
  "Tuesday": "Salı",
  "Wednesday": "Çarşamba",
  "Thursday": " Perşembe ",
  "Friday": "Cuma",
  "Saturday": "Cumartesi",
  "Default Date": "Varsayılan Tarih",
  "year": " yıl ",
  "month": " ay ",
  "mo": " ay ",
  "days": " günler ",
  "ago": " önce ",
  "ahead": " ileri ",
  "Yesterday": "Dün",
  "Today": "Bugün",
  "Tomorrow": "Yarın",
  "Custom": "Görenek",
  "Set Daily Rows Limit": "Günlük Satır Sınırını Ayarla",
  "Set Proportions": "Oranları Ayarla",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "Ziyaretçilerin yerel Calnedar'lara etkinlik eklemesine izin ver , Google, Yahoo, Outlook, ICalendar . ",
  "Container": "Konteyner",
  "Background": "Arka fon",
  "Container Background": "Konteyner Arka Planı",
  "Container Borders": "Konteyner Sınırları",
  "Calendar": "Takvim",
  "Event Info Tooltip": "Etkinlik Bilgisi İpucu",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "İnsanlar bir etkinliğin üzerine geldiğinde, onunla ilgili tüm bilgileri bir araç ipucunda görürler. ",
  "Event Info Window": "Etkinlik Bilgi Penceresi",
  "This is the full information window that opens when someone clicks on the event.": "Bu, bir kişi etkinliği tıklattığında açılan tüm bilgi penceresidir. ",
  "Use Gradient": "Gradyanı Kullan",
  "Vertical": "Dikey",
  "Horizontal": "Yatay",
  "First": "İlk",
  "Second": "İkinci",
  "diagonal": " diyagonal ",
  "Radial": "Radyal",
  "Select option": "Seçeneği seç",
  "Solid": "Katı",
  "Dotted": "Noktalı",
  "Dashed": "Kesik",
  "Double": "Çift",
  "Border Radius": "Sınır Yarıçapı",
  "Padding": "Dolgu malzemesi",
  "Date Header": "Tarih Başlığı",
  "Event Default Color": "Etkinlik Varsayılan Rengi",
  "Days of Week": "Haftanın günleri",
  "Days of Week Background": "Haftanın Günleri Arkaplan",
  "Date": "Tarih",
  "Event Title": "Olay başlığı",
  "Highlight today": "Bugün vurgula",
  "Highlight Color": "Vurgu Rengi",
  "Hide": "Saklamak",
  "Calendar Border Color": "Takvim Kenarlığı Rengi",
  "Calendar Border Width": "Takvim Sınır Genişliği",
  "Calendar Border Style": "Takvim Sınır Stili",
  "Font Color": "Yazı rengi",
  "Event Background": "Etkinlik Arka Planı",
  "Card Date Color": "Kart Tarihi Rengi",
  "Title Font": "Başlık Yazı Tipi",
  "Date Font": "Tarih Yazı Tipi",
  "Description Font": "Açıklama Yazı Tipi",
  "Button Background": "Düğme Arka Planı",
  "Button Text": "Düğme Metni",
  "Border Color": "Sınır rengi",
  "Border Width": "Sınır Genişliği",
  "Border Type": "Sınır Türü",
  "Title": "Başlık",
  "Background Color": "Arka plan rengi",
  "Divider": "Bölücü",
  "Event Details Font": "Etkinlik Ayrıntıları Yazı Tipi",
  "Website Link Color": "Web Sitesi Bağlantı Rengi",
  "Developer Info": "Geliştirici Bilgisi",
  "User Guide": "Kullanici rehberi",
  "Support e-mail": "Destek e-postası",
  "Our Website": "Web Sitemiz",
  "App Review": "Uygulama İncelemesi",
  "Enjoying App? Leave us a review in the App Market.": "App Eğleniyor? Bize App Market hakkında bir inceleme bırakın . ",
  "Review Us": "Bizi İnceleyin",
  "Connect With Us": "Bizimle iletişime geçin",
  "What's your email?": "E-posta adresin nedir? ",
  "Invalid email address!": "Geçersiz e-posta adresi! ",
  "Comments": "Yorumlar",
  "We'd love to hear from you. Send us a message.": "Sizden haber almak isteriz.Bize bir mesaj gönderin.",
  "Message must be at least 5 characters long": "Mesaj en az 5 karakter uzunluğunda olmalı",
  "Send": "Gönder",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "Kullanıcının takvim görünümleri arasında geçiş yapmasına izin vermek istiyorsanız, bu seçeneği etkinleştirin ve göstermek istediğiniz görünümleri seçin. ",
  "Main": "Ana",
  "Localize": "Yerelleştirmek",
  "Settings": "Ayarlar",
  "Layouts": "Düzenleri",
  "Advanced": "Ileri",
  "Design": "Dizayn",
  "Support": "Destek",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "Tüm yerel ayarlar dilinize göre (otomatik olarak) yapılır. Diliniz listede ise, bu bölümü özelleştirmenize gerek yoktur.",
  "Date Format": "Tarih formatı",
  "Time Format": "Zaman formatı",
  "Text Direction": "Metin yönü",
  "Left to Right": "Soldan sağa",
  "Right to Left": "Sağdan sola",
  "Week Starts On": "Hafta Başlıyor",
  "Agenda Style": "Gündem Stili",
  "Classic": "Klasik",
  "Modern": "Modern",
  "Agenda Header": "Gündem Başlığı",
  "Upcoming Events": "Yaklaşan Etkinlikler",
  "Agenda Event Limit": "Gündem Etkinlik Sınırı",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "Şimdi yükseltin ve daha fazla özellik edinin ve uygulamanızın keyfini tam olarak çıkarın!",
  "Upgrade Now": "Şimdi Yükselt",
  "Hosting events that last all day? This lets you show them on your calendar.": "Bütün gün süren etkinlikleri barındırmak mı? Bu, takviminizde onlara göstermenizi sağlar.",
  "24 hours": "24 saat",
  "Sun": "Pazar",
  "Mon": "Pazartesi",
  "Sat": "Cumartesi",
  "Default": "Varsayılan",
  "Select custom design style for your calendar.": "Takviminiz için özel tasarım stilini seçin.",
  "Style": "Stil",
  "Styles and Colors": "Stiller ve Renkler",
  "Calendar Name": "Takvim Adı",
  "Write your Calendar name here": "Takvim adınızı buraya yazın",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "Bu, kullanıcılarınız tarafından görülemez. Boom Calendar Sync işlevini kullanırken takvimlerinizi ayırt etmek için adları ayarlayın.",
  "Venue": "mekan",
  "Search": "Arama",
  "Add to": "A ekle",
  "calendar": "takvim",
  "Copy event URL": "Olay URL'sini kopyala",
  "Copied!": "Kopyalandı!",
  "Add & Share": "Ekle ve Paylaş",
  "Map": "Harita",
  "Calendar view": "Takvim görünümü",
  "Uncategorised": "Kategorize edilmemiş",
  "More": "Daha",
  "Less": "Az",
  "Register": "Kayıt ol",
  "Card": "Kart",

  "Guests": "Misafirler",
  "unlimited": "sınırsız",
  "Show more": "Daha fazla göster",
  "Enable Search": "Aramayı Etkinleştir",
  "+ Add Event": "+ Etkinlik Ekle",
  "Manage and Sync": "Yönet ve Senkronize Et",
  "Show event details as...": "Etkinlik ayrıntılarını şu şekilde göster ...",
  "Tooltip": "İpucu",
  "Popup": "Bilgi kutusu",
  "None": "Yok",
  "Show Category": "Kategoriyi Göster",
  "Header Align": "Üstbilgi Hizalama",
  "Show Time": "Gösteri zamanı",
  "Hours in Weekly/Daily View": "Haftalık / Günlük Görünümdeki Saatler",
  "Share Events": "Etkinlikleri Paylaşma",
  "Shadow": "Gölge",
  "Inner Padding": "İç Dolgu",
  "Text": "Metin",
  "Active Button Border": "Etkin Düğme Kenarlığı",
  "Light Mode": "Işık Modu",
  "Event Text Color": "Etkinlik Metni Rengi",
  "Dates": "Tarih",
  "Skeleton": "iskelet",
  "Skeleton Color": "İskelet Rengi",
  "Width": "Genişlik",
  "Skeleton Style": "İskelet Tarzı",
  "Color": "Renk",
  "Section Titles": "Bölüm Başlıkları",
  "Section Content": "Bölüm İçeriği",
  "Header": "Başlık",
  "Standard": "Standart",
  "Retro": "Retro",
  "Silver": "Gümüş",
  "Night": "Gece",
  "Dark": "Karanlık",
  "Aubergine": "Patlıcan",
  "Map Header": "Harita Başlığı",
  "Show Title in mobile": "Başlığı mobilde göster",
  "Card View": "Kart Görünümü",
  "Card background color": "Kart arka plan rengi",
  "Title font": "Başlık yazı tipi",
  "Desciption font": "Açıklama yazı tipi",
  "Section font": "Yazı tipi bölümü",
  "Section divider color": "Bölüm ayırıcı rengi",
  "Add event": "Etkinlik ekle",
  "Choose a category": "Bir kategori seçin",
  "Venue name": "Mekan İsmi",
  "Venue phone": "Mekân telefonu",
  "Venue email": "Yer e-postası",
  "Venue website": "Mekan web sitesi",
  "Personal info": "Kişisel bilgi",
  "First name": "İsim",
  "Last name": "Soyadı",
  "Email Address": "E",
  "Additional Notes": "Ek Notlar",
  "Back": "Geri",
  "Save": "Kayıt etmek",
  "Your event has been submitted": "Etkinliğiniz gönderildi",
  "Event submittion has been failed": "Etkinlik gönderimi başarısız oldu",
  "First Name": "İsim",
  "Last Name": "Soyadı",
  "Phone Number": "Telefon numarası",
  "Address": "Adres",
  "Your comments": "Yorumların, yorumlarınız",
  "How many guests?": "Kaç misafir?",
  "Anything else we need to know?": "Bilmemiz gereken başka bir şey var mı?",
  "Guests:": "Misafirler:",
  "Submit": "Sunmak",
  "Go to Calendar": "Takvime git",
  "Registration completed successfully!": "Kayıt başarıyla tamamlandı!",
  "Please check your registered email address": "Lütfen kayıtlı e-posta adresinizi kontrol edin",
  "Add to Calendar": "Takvime ekle",
  "Share this Event": "Bu Etkinliği Paylaş",
  "Sorry something went wrong": "Üzgünüm bir şeyler ters gitti",
  "Back to registration": "กลับไปที่การลงทะเบียน",
  "Date & Location": "Tarih ve Yer",
  "Date & Time": "Tarih ve Saat",
  "home": "ev",
  "Header align": "Üstbilgi hizalaması",
  "Footer": "Alt bilgi",
  "Categories Filter": "kategoriler Filtre",
  "Show only upcoming": "Yalnızca yaklaşanları göster",
  "Card(s) in a row": "Arka arkaya kart (lar)",
  "Space between cards": "Kartlar arasındaki boşluk",
  "Shown events limit": "Gösterilen etkinlik sınırı",
  "Style 1": "Tarzı 1",
  "Style 2": "Tarzı 2",
  "Style 3": "Tarzı 3",
  "Style 4": "Tarzı 4",
  "Buttons & Links": "Düğmeler ve Bağlantılar",
  "Button corner radius": "Düğme köşe yarıçapı",
  "Buttons font": "Düğmeler yazı tipi",
  "Buttons background": "Düğmeler arka plan",
  "Get notified by Email": "E-posta ile haberdar olun",
  "Review events": "Olayları inceleyin",
  "Click on date": "Tarihi tıklayın",
  "Add Event button": "Etkinlik Ekle düğmesi",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "Takvim senkronizasyonu, etkinliklerinizi ve oturumlarınızı Boom Takviminizle bütünleştirmenize olanak tanır.",
  "connect": "bağlanmak",
  "Synchronized Calendars": "Senkronize Takvimler",
  "Import events": "Olayları içe aktar",
  "Disconnect": "Bağlantıyı kes",
  "Choose calendar": "Takvim seçin",
  "Monitor your Wix events through the sync feature": "Wix olaylarınızı senkronizasyon özelliği ile izleyin",
  "Connect all your Boom calendars available on your website": "Connect all your Boom calendars available on your website",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "Doğrudan Boom Takvimimiz aracılığıyla Yakınlaştırma toplantılarını planlayın, katılın ve yönetin.",
  "Monitor your Event Brite events through the Event Brite sync feature": "Event Brite senkronizasyon özelliği aracılığıyla Event Brite olaylarınızı izleyin",
  "Email": "E-posta",
  "Add-ons": "Eklentiler",
  "Receive notification emails as soon as users add events to your calendar.": "Kullanıcılar takviminize etkinlikler ekler almaz bildirim e-postaları alın.",
  "Enable + button on the calendar header": "Takvim başlığında + düğme etkinleştirin",
  "Accept or decline events added by customers before making them public.": "Onları halka açıklamadan önce müşterilerin eklenen olayları kabul edin veya reddetme.",
  "Switch Add Event": "Anahtarlama Etkinliği Anahtar",
  "Enable your browser cookies to connect to your account.": "Enable your browser cookies to connect to your account.",
  "Learn more": "Daha fazla bilgi edin",
  "Print Button": "Yazdır düğmesi",
  "Permit your users to print your Boom Event Calendar in any date range.": "Kullanıcılarınızın BOOM Olay Takviminizi herhangi bir tarih aralığında yazdırmalarına izin verin.",
  "Show Title on mobile": "Mobilde başlık göster",
  "Show Skeleton on mobile": "Mobilde iskeleti göster",
  "Start 7-day Business trial": "7 günlük iş denemenizi başlatın",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "Biletler, kayıt, ziyaretçi olayı eklentileri gibi tüm sınırsız özelliklerin tadını çıkarın.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "Lütfen dikkat: Deneme süresinin sonunda, mevcut abonelik planınıza iade edilecektir.",
  "Not Now": "Şimdi değil",
  "Start free trial": "Deneme sürümüne başla",
  "Congrats!": "Tebrikler!",
  "Your 7-day Business trial has been successfully activated.": "7 günlük iş denemeniz başarıyla etkinleştirildi.",
  "Done": "Tamamlandı",
  "Title font color": "Başlık yazı tipi rengi",
  "Desciption font color": "Açıklama yazı tipi rengi",
  "Section font color": "Bölüm yazı tipi rengi",
  "Card Header": "Kart başlığı",
  "Category": "Kategori",
  "Display at the": "Görüntülemek",
  "top": "Tepe",
  "bottom": "alt",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "Kategori filtresini üstten veya takvimin altına sergileyin.Ayarlar sadece gündem ve kart görünümler için geçerlidir.",
  "Processing your events": "Olaylarınızı işleme",
  "Search for events": "Etkinlikleri ara",
  "There are no events added": "Eklenen hiçbir etkinlik yok",
  "Location: To be determined": "Yer: Belirlenmek",
  "No events for selected date": "Seçilen tarih için etkinlik yok",
  "Uncategorized": "Kategorize edilmemiş",
  "Edit event": "Düzenleme Etkinliği",
  "Edit original event": "Orijinal Etkinliği Düzenle",
  "Copy event": "Kopyala Etkinliği",
  "Copy as new event": "Yeni olay olarak kopyala",
  "Delete event": "Etkinliği Sil",
  "Stop repeating on this date": "Bu tarihte tekrarlamayı bırak",
  "Exclude this date": "Bu tarihi hariç tut",
  "Fill your personal information": "Kişisel Bilgilerinizi Doldurun",
  "Check Box": "Onay kutusu",
  "Single Choice": "Tek seçim",
  "Option": "Seçenek",
  "Share Event": "Paylaşım Etkinliği",
  "Oops! Something went wrong": "Oops!Bir şeyler yanlış gitti",
  "We are sorry this event has already taken place": "Bu olay zaten gerçekleşti üzgünüz",
  "Back to calendar": "Takvime geri dön",
  "This field is required": "Bu alan gereklidir",
  "Phone": "Telefon",
  "Number field": "Sayı alanı",
 "Please provide a valid email" : "Lütfen geçerli bir e -posta sağlayın",
 "Select at least one option" : "En az bir seçenek seçin",
 "Choose tickets to see total value" : "Toplam değeri görmek için biletleri seçin",
 "tickets" : "biletler",
 "Choose Tickets" : "Biletler Seçin",
 "Choose payment method" : "ödeme yöntemini seçin",
 "Pay" : "Ödemek",
 "Total" : "Toplam",
 "Free" : "Özgür",
 "Buy tickets" : "Bilet satın al",
 "Sold Out" : "Hepsi satıldı",
 "Tickets are available" : "Biletler mevcut",
 "Sales End" : "Satış sonu",
 "Availible from" : "Kullanılabilir",
 "Go to Orders" : "Siparişlere Git",
 "Go to Details" : "Ayrıntılara git",
 "Group ticket" : "Grup bileti",
 "Name" : "İsim",
 "Price" : "Fiyat",
 "Order by" : "Tarafından sipariş",
 "Order ID" : "Sipariş Kimliği",
 "Applied" : "Uygulamalı",
 "Fees" : "Ücret",
 "Enter promo code" : "Promosyon kodunu girin",
 "Apply" : "Uygulamak",
 "Promo Code" : "Promosyon kodu",
 "Cash" : "Nakit",
 "You can find your e-tickets attached to your email or download them" : "E-posta ile e-postanıza bağlı bulabilir veya indirebilirsiniz",
 "here" : "burada",
 "Time" : "Zaman",
 "Invalid promo code" : "Geçersiz reklam kodu",
 "Credit card" : "Kredi kartı",
 "You will soon receive a confirmation message of successful registration to your email address." : "Yakında e -posta adresinize başarılı bir kayıt onay mesajı alacaksınız.",
 "You can also check your order details below." : "Sipariş bilgilerinizi aşağıda da kontrol edebilirsiniz.",
 "at" : "-den",
 "Buy" : "Satın almak",
 "Donation" : "Bağış",
 "Enter price" : "Girişim",
 "Choose" : "Seçmek",
 "Chosen" : "Seçilmiş",
 "Choose your plan" : "Planınızı Seçin",
  "week": "hafta",
  "wk": "hafta",
 "Choose plan cycle" : "Plan döngüsünü seçin",
 "months" : "aylar",
 "years" : "yıllar",
 "weeks" : "haftalar",
 "Copy Event Url" : "Olay URL'sini Kopyala",
 "You can find your e-tickets attached to your email or print them" : "E-biletlerinizi e-postanıza bağlı bulabilir veya yazdırabilirsiniz",
 "Guest Info" : "Konuk Bilgisi",
 "Ticket Info" : "Bilet bilgileri",
 "Ticket name" : "Bilet adı",
 "Ticket price" : "Bilet fiyatı",
 "Ticket ID" : "Bilet kimliği",
 "If you have any questions contact to organizer" : "Herhangi bir sorunuz varsa organizatörle iletişime geçin",
 "As soon as event ends" : "Olay biter bitmez",
 "1 day after event ends" : "Olay bittikten 1 gün sonra",
 "7 days after event ends" : "Olay bittikten 7 gün sonra",
 "14 days after event ends" : "Olay bittikten 14 gün sonra",
 "30 days after event ends" : "Olay bittikten 30 gün sonra",
 "Menu" : "Menü",
 "No event for selected date" : "Seçilen tarih için olay yok",
 "All day event" : "Tüm gün aktivitesi",
 "Add location" : "Konum ekle",
 "The field is required" : "Alan zorunludur",
 "Please provide a valid url" : "Lütfen geçerli bir URL sağlayın",
 "Bold" : "Gözü pek",
 "Italic" : "İtalik",
 "Underline" : "Altını çizmek",
 "Link" : "Bağlantı",
 "Bulleted list" : "Maddeli liste",
 "Numbered list" : "Numaralı liste",
 "Website" : "İnternet sitesi"
}
export default tr