let vi = {
   "Language":"Ngôn ngữ",
   "Show Time Zone":"Hiển thị múi giờ",
   "Custom Local Settings":"Cài đặt cục bộ tùy chỉnh",
   "Add and showcase events on your site using a beautiful calendar.":"Thêm và giới thiệu các sự kiện trên trang web của bạn bằng cách sử dụng lịch đẹp.",
   "Week Days":"Ngày trong tuần",
   "Manage Events":"Quản lý sự kiện",
   "General":"Tổng quan",
   "Layout Picker":"Bộ chọn bố cục",
   "Month":"Tháng",
   "Monthly":"Hàng tháng",
   "Week":"Tuần",
   "Weekly":"Hàng tuần",
   "Day":"Ngày",
   "Daily":"hằng ngày",
   "Agenda":"Chương trình nghị sự",
   "Navigation Buttons":"Nút điều hướng",
   "Week numbers":"Số tuần",
   "Include Weekends":"Bao gồm các ngày cuối tuần",
   "All-day":"Cả ngày",
   "All Day":"Cả ngày",
   "Label":"Nhãn mác",
   "Fit to Height":"Vừa với chiều cao",
   "To set App proportions manully disable this option and resize Calendar in Editor.":"Để đặt Tỷ lệ ứng dụng theo cách thủ công, hãy tắt tùy chọn này và thay đổi kích thước Lịch trong Trình chỉnh sửa theo cách thủ công.",
   "Default Layout":"Bố cục mặc định",
   "Monthly view":"Xem hàng tháng",
   "Weekly and Daily view":"Chế độ xem hàng tuần và hàng ngày",
   "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":"Bạn có thể mang đến cho khách truy cập trải nghiệm nhất quán hơn bằng cách hiển thị cùng một số tuần (6) tại một thời điểm.",
   "Fixed Weekly Layout":"Bố cục hàng tuần cố định",
   "back":"trở lại",
   "Row":"Chèo thuyền",
   "Hours in Weekly View":"Giờ trong Chế độ xem hàng tuần",
   "Hours in Daily View":"Giờ trong Chế độ xem hàng ngày",
   "Start":"Khởi đầu",
   "End":"Chấm dứt",
   "At This Hour":"Vào giờ này",
   "Add to":"Thêm vào",
   "Button":"Cái nút",
   "Buttons":"nút",
   "Sunday":"chủ nhật",
   "Monday":"thứ hai",
   "Tuesday":"thứ ba",
   "Wednesday":"Thứ Tư",
   "Thursday":"Thứ năm",
   "Friday":"Thứ sáu",
   "Saturday":"thứ bảy",
   "Default Date":"Ngày mặc định",
   "year":"năm",
   "month":"tháng",
   "days":"ngày",
   "ago":"trước kia",
   "ahead":"phía trước",
   "Yesterday":"Hôm qua",
   "Today":"Hôm nay",
   "Tomorrow":"Ngày mai",
   "Custom":"Tập quán",
   "Set Daily Rows Limit":"Đặt giới hạn hàng ngày",
   "Set Proportions":"Đặt tỷ lệ",
   "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":"Cho phép khách truy cập thêm sự kiện vào Lịch cục bộ: Google, Yahoo, Outlook, ICalendar.",
   "Container":"Thùng đựng hàng",
   "Background":"Lý lịch",
   "Container Background":"Nền vùng chứa",
   "Container Borders":"Biên giới vùng chứa",
   "Calendar":"Lịch",
   "Event Info Tooltip":"Chú giải công cụ / cửa sổ bật lên thông tin sự kiện",
   "When people hover over an event they’ll see all the info about it in a tooltip.":"Khi mọi người di chuột qua một sự kiện, họ sẽ thấy tất cả thông tin về sự kiện đó trong chú giải công cụ.",
   "Event Info Window":"Cửa sổ thông tin sự kiện",
   "This is the full information window that opens when someone clicks on the event.":"Đây là cửa sổ thông tin đầy đủ sẽ mở ra khi ai đó nhấp vào sự kiện.",
   "Use Gradient":"Sử dụng Gradient",
   "Vertical":"Thẳng đứng",
   "Horizontal":"Nằm ngang",
   "First":"Ngày thứ nhất",
   "Second":"Thứ hai",
   "diagonal":"đường chéo",
   "Radial":"Xuyên tâm",
   "Select option":"Chọn tùy chọn",
   "Solid":"Cứng",
   "Dotted":"Say mê",
   "Dashed":"Tiêu tan",
   "Double":"Gấp đôi",
   "Border Radius":"Bán kính đường viền",
   "Padding":"Đệm lót",
   "Date Header":"Tiêu đề ngày",
   "Event Default Color":"Màu mặc định của sự kiện",
   "Days of Week":"Ngày trong tuần",
   "Days of Week Background":"Nền các ngày trong tuần",
   "Date":"Ngày",
   "Event Title":"Tiêu đề sự kiện",
   "Highlight today":"Đánh dấu ngày hôm nay",
   "Highlight Color":"Màu nổi bật",
   "Hide":"Giấu",
   "Calendar Border Color":"Màu viền lịch",
   "Calendar Border Width":"Chiều rộng đường viền lịch",
   "Calendar Border Style":"Lịch kiểu viền",
   "Section Titles":"Tiêu đề phần",
   "Section Content":"Nội dung phần",
   "Event Background":"Nền sự kiện",
   "Card Date Color":"Màu ngày thẻ",
   "Title Font":"Phông chữ tiêu đề",
   "Date Font":"Phông chữ ngày tháng",
   "Description Font":"Phông chữ mô tả",
   "Button Background":"Nền nút",
   "Button Text":"Nút văn bản",
   "Border Color":"Màu viền",
   "Border Width":"Chiều rộng biên giới",
   "Border Type":"Loại đường viền",
   "Title":"Chức vụ",
   "Description":"Sự miêu tả",
   "Background Color":"Màu nền",
   "Divider":"Dải phân cách",
   "Event Details Font":"Phông chữ chi tiết sự kiện",
   "Website Link Color":"Màu sắc liên kết",
   "Developer Info":"Thông tin nhà phát triển",
   "User Guide":"Hướng dẫn & Trò chuyện",
   "Support e-mail":"Hỗ trợ e-mail",
   "Our Website":"Website của chúng tôi",
   "App Review":"Đánh giá ứng dụng",
   "Enjoying App? Leave us a review in the App Market.":"Bạn thích ứng dụng? Để lại cho chúng tôi một đánh giá trong Thị trường ứng dụng.",
   "Review Us":"Đánh giá chúng tôi",
   "Connect With Us":"Kết nối với chúng tôi",
   "What's your email?":"Email của bạn là gì?",
   "Invalid email address!":"Địa chỉ email không hợp lệ!",
   "Comments":"Bình luận",
   "We'd love to hear from you. Send us a message.":"Chúng tôi rất muốn nghe từ bạn. Gửi tin nhắn cho chúng tôi.",
   "Message must be at least 5 characters long":"Tin nhắn phải dài ít nhất 5 ký tự",
   "Send":"Gửi",
   "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":"Nếu bạn muốn cho phép người dùng chuyển đổi giữa các chế độ xem lịch, hãy bật tùy chọn này và chọn các chế độ xem bạn muốn hiển thị.",
   "Main":"Chủ yếu",
   "Localize":"Bản địa hóa",
   "Settings":"Cài đặt",
   "Layouts":"Bố cục",
   "Advanced":"Trình độ cao",
   "Design":"Thiết kế",
   "Support":"Hỗ trợ",
   "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":"Tất cả các cài đặt cục bộ đều (tự động) dựa trên ngôn ngữ của bạn. Nếu ngôn ngữ của bạn có trong danh sách, không cần phải tùy chỉnh phần này.",
   "Date Format":"Định dạng ngày tháng",
   "Time Format":"Định dạng thời gian",
   "Text Direction":"Văn bản chỉ đạo",
   "Left to Right":"Trái sang phải",
   "Right to Left":"Phải sang trái",
   "Week Starts On":"Tuần bắt đầu vào",
   "Agenda Style":"Phong cách chương trình nghị sự",
   "Classic":"Kinh điển",
   "Modern":"Hiện đại",
   "Agenda Header":"Tiêu đề chương trình làm việc",
   "Upcoming Events":"sự kiện sắp tới",
   "Agenda Event Limit":"Giới hạn sự kiện trong chương trình làm việc",
   "Upgrade now and get a lot more features and enjoy your APP in full!":"Nâng cấp ngay bây giờ và nhận được nhiều tính năng hơn và tận hưởng APP của bạn một cách trọn vẹn!",
   "Upgrade Now":"Nâng cấp ngay bây giờ",
   "Hosting events that last all day? This lets you show them on your calendar.":"Tổ chức các sự kiện kéo dài cả ngày? Điều này cho phép bạn hiển thị chúng trên lịch của mình.",
   "24 hours":"24 tiếng",
   "Sun":"mặt trời",
   "Mon":"Thứ hai",
   "Sat":"Đã ngồi",
   "Default":"Vỡ nợ",
   "Style":"Phong cách",
   "Calendar Name":"Tên lịch",
   "Write your Calendar name here":"Viết tên Lịch của bạn ở đây",
   "Enable Search":"Bật tìm kiếm",
   "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":"Điều này không hiển thị cho người dùng của bạn. Đặt tên để phân biệt các lịch của bạn khi sử dụng chức năng Boom Calendar Sync.",
   "+ Add Event":"+ Thêm sự kiện",
   "Manage and Sync":"Quản lý và đồng bộ hóa",
   "Show event details as...":"Hiển thị chi tiết sự kiện dưới dạng ...",
   "Tooltip":"Chú giải công cụ",
   "Popup":"Cửa sổ bật lên",
   "None":"Không có",
   "Show Category":"Hiển thị danh mục",
   "Header Align":"Căn chỉnh tiêu đề",
   "Show Time":"Hiển thị thời gian",
   "Hours in Weekly/Daily View":"Giờ trong Chế độ xem hàng tuần / hàng ngày",
   "Share Events":"Chia sẻ sự kiện",
   "Shadow":"Bong tôi",
   "Inner Padding":"Đệm bên trong",
   "Text":"Chữ",
   "Active Button Border":"Đường viền nút hoạt động",
   "Light Mode":"Chế độ sáng",
   "Event Text Color":"Màu văn bản sự kiện",
   "Dates":"ngày",
   "Skeleton":"Bộ xương",
   "Skeleton Color":"Màu da",
   "Width":"Chiều rộng",
   "Skeleton Style":"Phong cách Skeleton",
   "Color":"Màu sắc",
   "Header":"Tiêu đề",
   "Map":"Bản đồ",
   "Standard":"Tiêu chuẩn",
   "Retro":"Cổ điển",
   "Silver":"Màu bạc",
   "Night":"Đêm",
   "Dark":"Tối tăm",
   "Aubergine":"Aubergine",
   "Map Header":"Tiêu đề bản đồ",
   "Show Title in mobile":"Hiển thị Tiêu đề trong điện thoại di động",
   "Card":"Thẻ",
   "Card View":"Xem thẻ",
   "Card background color":"Màu nền thẻ",
   "Title font":"Phông chữ tiêu đề",
   "Desciption font":"Phông chữ mô tả",
   "Section font":"Phần phông chữ",
   "Section divider color":"Màu của dải phân cách",
   "Font Color":"Màu phông chữ",
   "General Info":"Thông tin chung",
   "Venue":"Địa điểm",
   "Organizer":"Người tổ chức",
   "Search":"Tìm kiếm",
   "calendar":"lịch",
   "Share this event":"Chia sẻ sự kiện này",
   "Copy event URL":"Sao chép URL sự kiện",
   "Copied!":"Đã sao chép!",
   "Add & Share":"Thêm & Chia sẻ",
   "Calendar view":"Chế độ xem lịch",
   "Add Event":"Thêm sự kiện",
   "Uncategorised":"Chưa được phân loại",
   "Categories":"Thể loại",
   "More":"Hơn",
   "Less":"Ít hơn",
   "Register":"Đăng ký",
   "Guests":"Khách",
   "unlimited":"vô hạn",
   "Show more":"Cho xem nhiều hơn",
   "Add event":"Thêm sự kiện",
   "All Day Event":"Sự kiện cả ngày",
   "Location":"Địa điểm",
   "Choose a category":"Chọn một danh mục",
   "Venue name":"Tên địa điểm",
   "Venue phone":"Điện thoại địa điểm",
   "Venue email":"Địa chỉ email",
   "Venue website":"Trang web địa điểm",
   "Organizer name":"Tên người tổ chức",
   "Organizer phone":"Điện thoại của người tổ chức",
   "Organizer email":"Email của người tổ chức",
   "Organizer website":"Trang web của nhà tổ chức",
   "Personal info":"Thông tin cá nhân",
   "First name":"Họ",
   "Last name":"Họ",
   "Email Address":"Địa chỉ email",
   "Additional Notes":"Ghi chú bổ sung",
   "Back":"Trở lại",
   "Save":"Cứu",
   "Next":"Kế tiếp",
   "Your event has been submitted":"Sự kiện của bạn đã được gửi",
   "Event submittion has been failed":"Gửi sự kiện không thành công",
   "e.g. Birthday Party":"ví dụ. Tiệc sinh nhật",
   "First Name":"Họ",
   "Last Name":"Họ",
   "Phone Number":"Số điện thoại",
   "Address":"Địa chỉ nhà",
   "Your comments":"Bình luận của bạn",
   "How many guests?":"Có bao nhiêu vị khách?",
   "Anything else we need to know?":"Còn điều gì khác chúng ta cần biết không?",
   "Guests: ":"Khách:",
   "Submit":"Nộp",
   "Go to Calendar":"Đi tới Lịch",
   "Registration completed successfully!":"Đăng ký đã hoàn tất thành công!",
   "Please check your registered email address":"Vui lòng kiểm tra địa chỉ email đã đăng ký của bạn",
   "Add to Calendar":"Thêm vào Lịch",
   "Share this Event":"Chia sẻ sự kiện này",
   "Sorry something went wrong":"Xin lỗi, có lỗi xảy ra",
   "Back to registration":"Quay lại đăng ký",
   "Date & Location":"Ngày & Vị trí",
   "Date & Time":"Ngày giờ",
   "home":"Trang Chủ",
   "Header align":"Căn chỉnh tiêu đề",
   "Footer":"Chân trang",
   "Categories Filter":"Bộ lọc danh mục",
   "Show only upcoming":"Chỉ hiển thị sắp tới",
   "Card(s) in a row":"(Các) thẻ liên tiếp",
   "Space between cards":"Khoảng cách giữa các thẻ",
   "Shown events limit":"Giới hạn sự kiện được hiển thị",
   "Style 1":"Phong cách 1",
   "Style 2":"Phong cách 2",
   "Style 3":"Phong cách 3",
   "Style 4":"Phong cách 4",
   "Buttons & Links":"Các nút và liên kết",
   "Button corner radius":"Bán kính góc nút",
   "Buttons font":"Phông chữ các nút",
   "Buttons background":"Các nút nền",
   "Get notified by Email":"Nhận thông báo qua Email",
   "Review events":"Xem lại các sự kiện",
   "Click on date":"Bấm vào ngày",
   "Add Event button":"Thêm nút Sự kiện",
   "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":"Đồng bộ hóa lịch cho phép bạn tích hợp các sự kiện và phiên của mình với Lịch bùng nổ.",
   "connect":"liên kết",
   "Synchronized Calendars":"Lịch được đồng bộ hóa",
   "Import events":"Nhập sự kiện",
   "Disconnect":"Ngắt kết nối",
   "Choose calendar":"Chọn lịch",
   "Monitor your Wix events through the sync feature":"Giám sát các sự kiện Wix của bạn thông qua tính năng đồng bộ hóa",
   "Connect all your Boom calendars available on your website":"Kết nối tất cả các lịch Boom có ​​sẵn trên trang web của bạn",
   "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":"Lên lịch, tham gia và quản lý các cuộc họp Zoom ngay thông qua Lịch Boom của chúng tôi.",
   "Monitor your Event Brite events through the Event Brite sync feature":"Theo dõi các sự kiện Event Brite của bạn thông qua tính năng đồng bộ hóa Event Brite",
   "Email":"E-mail",
   "Add-ons":"Tiện ích bổ sung",
   "Switch Add Event":"Chuyển đổi Thêm sự kiện",
   "Enable your browser cookies to connect to your account.":"Bật cookie của trình duyệt để kết nối với tài khoản của bạn.",
   "Learn more":"Tìm hiểu thêm",
   "Print Button":"Nút in",
   "Permit your users to print your Boom Event Calendar in any date range.":"Cho phép người dùng in Lịch sự kiện bùng nổ của bạn trong bất kỳ phạm vi ngày nào.",
   "Show Title on mobile":"Hiển thị Tiêu đề trên điện thoại di động",
   "Show Skeleton on mobile":"Hiển thị Skeleton trên thiết bị di động",
   "Start 7-day Business trial":"Bắt đầu dùng thử 7 ngày dành cho Doanh nghiệp",
   "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":"Tận hưởng tất cả các tính năng Unlimiited, chẳng hạn như Bán vé, Đăng ký, Tiện ích sự kiện của khách truy cập.",
   "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":"Xin lưu ý: Khi kết thúc giai đoạn dùng thử, bạn sẽ được quay lại gói đăng ký hiện có của mình.",
   "Not Now":"Không phải bây giờ",
   "Start free trial":"Dùng thử miễn phí",
   "Congrats!":"Chúc mừng!",
   "Your 7-day Business trial has been successfully activated.":"Bản dùng thử 7 ngày dành cho Doanh nghiệp của bạn đã được kích hoạt thành công.",
   "Done":"Làm xong",
   "Title font color":"Màu phông chữ tiêu đề",
   "Desciption font color":"Màu phông chữ mô tả",
   "Section font color":"Màu phông chữ phần",
   "Card Header":"Tiêu đề thẻ",
   "Category":"Loại",
   "Display at the":"Hiển thị tại",
   "top":"đứng đầu",
   "bottom":"đáy",
   "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":"Hiển thị bộ lọc danh mục ở đầu hoặc cuối lịch. Cài đặt chỉ áp dụng cho các chế độ xem Chương trình làm việc và Thẻ",
   "Processing your events":"Xử lý các sự kiện của bạn",
   "Search for events":"Tìm kiếm sự kiện",
   "There are no events added":"Không có sự kiện nào được thêm vào",
   "Location: To be determined":"Vị trí: Được xác định"
}

export default vi