let zh = {
  "Categories": "分类目录",
  "Share this event": "分享这个活动",
  "Language": "语言",
  "Show Time Zone": "显示时区",
  "Custom Local Settings": "自定义本地设置",
  "Add and showcase events on your site using a beautiful calendar.": "使用漂亮的日历在您的网站上添加和展示活动。",
  "Week Days": "周日",
  "Manage Events": "管理活动",
  "General": "一般",
  "Layout Picker": "布局选择器",
  "Month": "月",
  "Monthly": "每月",
  "Week": "周",
  "Weekly": "每周",
  "Day": "天",
  "Daily": "日常",
  "Agenda": "议程",
  "Navigation Buttons": "导航按钮",
  "Week numbers": "周数",
  "Include Weekends": "包括周末",
  "All-day": "一整天",
  "All Day": "一整天",
  "Label": "标签",
  "Fit to Height": "适合身高",
  "To set App proportions manully disable this option and resize Calendar in Editor.": "要设置应用程序比例，请手动禁用此选项并在编辑器中调整日历大小。",
  "Default Layout": "默认布局",
  "Monthly view": "每月观点",
  "Weekly and Daily view": "每周和每日观点",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.": "通过一次显示相同的周数（6），您可以为访问者提供更一致的体验。",
  "Fixed Weekly Layout": "固定每周布局",
  "back": " 回",
  "Row": "行",
  "Hours in Weekly View": "每周视图中的小时数",
  "Hours in Daily View": "每日观看时间",
  "Start": "开始",
  "End": "结束",
  "At This Hour": "在这个时刻",
  "Button": "按钮",
  "Buttons": "纽扣",
  "Sunday": "星期日",
  "Monday": "星期一",
  "Tuesday": "星期二",
  "Wednesday": "星期三",
  "Thursday": " 星期四",
  "Friday": "星期五",
  "Saturday": "星期六",
  "Default Date": "默认日期",
  "year": " 年",
  "month": " 月",
  "days": " 天",
  "ago": " 以前",
  "ahead": " 领先",
  "Yesterday": "昨天",
  "Today": "今天",
  "Tomorrow": "明天",
  "Custom": "自定义",
  "Set Daily Rows Limit": "设置每日行限制",
  "Set Proportions": "设置比例",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.": "允许访问者向当地的Calnedars 添加活动,Google，Yahoo，Outlook，ICalendar 。",
  "Container": "容器",
  "Background": "背景",
  "Container Background": "容器背景",
  "Container Borders": "集装箱边界",
  "Calendar": "日历",
  "Event Info Tooltip": "活动信息工具提示",
  "When people hover over an event they’ll see all the info about it in a tooltip.": "当人们在事件上盘旋时，他们会在工具提示中看到有关它的所有信息。",
  "Event Info Window": "活动信息窗口",
  "This is the full information window that opens when someone clicks on the event.": "这是当有人点击事件时打开的完整信息窗口。",
  "Use Gradient": "使用渐变",
  "Vertical": "垂直",
  "Horizontal": "水平",
  "First": "第一",
  "Second": "第二",
  "diagonal": " 对角线",
  "Radial": "子午线",
  "Select option": "选择选项",
  "Solid": "固体",
  "Dotted": "虚线",
  "Dashed": "虚线",
  "Double": "双",
  "Border Radius": "边界半径",
  "Padding": "填充",
  "Date Header": "日期标题",
  "Event Default Color": "事件默认颜色",
  "Days of Week": "星期几",
  "Days of Week Background": "周日背景",
  "Date": "日期",
  "Event Title": "活动标题",
  "Highlight today": "今日亮点",
  "Highlight Color": "突出显示颜色",
  "Hide": "隐藏",
  "Calendar Border Color": "日历边框颜色",
  "Calendar Border Width": "日历边框宽度",
  "Calendar Border Style": "日历边框样式",
  "Font Color": "字体颜色",
  "Event Background": "活动背景",
  "Card Date Color": "卡片日期颜色",
  "Title Font": "标题字体",
  "Date Font": "日期字体",
  "Description Font": "描述字体",
  "Button Background": "按钮背景",
  "Button Text": "按钮文字",
  "Border Color": "边框颜色",
  "Border Width": "边界宽度",
  "Border Type": "边境类型",
  "Title": "标题",
  "Description": "描述",
  "Background Color": "背景颜色",
  "Divider": "除法",
  "Event Details Font": "活动详情字体",
  "Website Link Color": "网站链接颜色",
  "Developer Info": "开发者信息",
  "User Guide": "用户指南",
  "Support e-mail": "支持电子邮件",
  "Our Website": "我们的网站",
  "App Review": "App Review",
  "Enjoying App? Leave us a review in the App Market.": "享受App？在App Market 留下评论。",
  "Review Us": "回顾我们",
  "Connect With Us": "联系我们",
  "What's your email?": "你的电子邮件是什么？",
  "Invalid email address!": "电子邮件地址无效！",
  "Comments": "评论",
  "We'd love to hear from you. Send us a message.": "我们很乐意听取您的意见。给我们留言。",
  "Message must be at least 5 characters long": "邮件长度必须至少为5个字符",
  "Send": "发送",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.": "如果您想允许用户在日历视图之间切换，请启用此选项并选择您要显示的视图。",
  "Main": "主要",
  "Localize": "本土化",
  "Settings": "设置",
  "Layouts": "布局",
  "Advanced": "高级",
  "Design": "设计",
  "Support": "支持",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.": "所有本地设置都是（自动）基于您的语言。 如果您的语言在列表中，则无需自定义此部分。",
  "Date Format": "日期格式",
  "Time Format": "时间格式",
  "Text Direction": "文字方向",
  "Left to Right": "左到右",
  "Right to Left": "右到左",
  "Week Starts On": "周开始",
  "Agenda Style": "议程风格",
  "Classic": "经典",
  "Modern": "现代",
  "Agenda Header": "议程标题",
  "Upcoming Events": "接下来的活动",
  "Agenda Event Limit": "议程活动限制",
  "Upgrade now and get a lot more features and enjoy your APP in full!": "立即升级，获得更多功能，全面享受您的APP！",
  "Upgrade Now": "现在升级",
  "Hosting events that last all day? This lets you show them on your calendar.": "主持持续一整天的活动？这可以让你在日历上显示它们。",
  "24 hours": "24小时",
  "Sun": "星期日",
  "Mon": "星期一",
  "Sat": "星期六",
  "Default": "默认",
  "Select custom design style for your calendar.": "为您的日历选择自定义设计风格。",
  "Style": "样式",
  "Styles and Colors": "款式和顏色",
  "Calendar Name": "日曆名稱",
  "Write your Calendar name here": "在這裡寫下您的日曆名��",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.": "這對您的用戶不可見。 使用動臂日曆同步功能時，請設置名稱以區分您的日曆。",
  "General Info": "基本信息",
  "Venue": "会场",
  "Organizer": "组织者",
  "Search": "搜索",
  "Add to": "添加",
  "calendar": "日历",
  "Copy event URL": "复制事件URL",
  "Copied!": "复制！",
  "Add & Share": "添加并分享",
  "Map": "地图",
  "Calendar view": "日历视图",
  "Add Event": "新增活动",
  "Uncategorised": "未分类",
  "More": "更多",
  "Less": "减",
  "Register": "寄存器",
  "Card": "卡",

  "Guests": "来宾",
  "unlimited": "无限",
  "Show more": "展示更多",
  "Enable Search": "启用搜寻",
  "+ Add Event": "+添加事件",
  "Manage and Sync": "管理和同步",
  "Show event details as...": "将活动详细信息显示为...",
  "Tooltip": "工具提示",
  "Popup": "信息框",
  "None": "没有",
  "Show Category": "显示类别",
  "Header Align": "标题对齐",
  "Show Time": "开演时间",
  "Hours in Weekly/Daily View": "每周/每日视图中的小时数",
  "Share Events": "分享活动",
  "Shadow": "阴影",
  "Inner Padding": "阴影",
  "Text": "文本",
  "Active Button Border": "活动按钮边框",
  "Light Mode": "灯光模式",
  "Event Text Color": "活动文字颜色",
  "Dates": "日期",
  "Skeleton": "骨架",
  "Skeleton Color": "骨架色",
  "Width": "宽度",
  "Skeleton Style": "骨架样式",
  "Color": "颜色",
  "Section Titles": "章节标题",
  "Section Content": "栏目内容",
  "Header": "标头",
  "Standard": "标准",
  "Retro": "复古风",
  "Silver": "银",
  "Night": "晚",
  "Dark": "黑暗",
  "Aubergine": "茄子",
  "Map Header": "地图标题",
  "Show Title in mobile": "在手机上显示标题",
  "Card View": "卡视图",
  "Card background color": "卡背景色",
  "Title font": "标题字体",
  "Desciption font": "说明字体",
  "Section font": "字体部分",
  "Section divider color": "分区颜色",
  "Add event": "添加事件",
  "All Day Event": "全天的活动",
  "Location": "位置",
  "Choose a category": "选择类别",
  "Venue name": "地点名称",
  "Venue phone": "场馆电话",
  "Venue email": "地点电子邮件",
  "Venue website": "场地网站",
  "Organizer name": "组织者名称",
  "Organizer phone": "主办单位电话",
  "Organizer email": "组织者电子邮件",
  "Organizer website": "主办单位网站",
  "Personal info": "个人信息",
  "First name": "名字",
  "Last name": "姓",
  "Email Address": "电子邮件地址",
  "Additional Notes": "补充说明",
  "Back": "背部",
  "Save": "救",
  "Next": "下一个",
  "Your event has been submitted": "您的活动已提交",
  "Event submittion has been failed": "事件提交失败",
  "e.g. Birthday Party": "例如。 生日聚会",
  "First Name": "名字",
  "Last Name": "姓",
  "Phone Number": "电话号码",
  "Address": "地址",
  "Your comments": "你的评论",
  "How many guests?": "有多少位客人？",
  "Anything else we need to know?": "我们还有什么需要知道的吗？",
  "Guests:": "嘉宾：",
  "Submit": "提交",
  "Go to Calendar": "转到日历",
  "Registration completed successfully!": "注册成功完成！",
  "Please check your registered email address": "请检查您的注册电子邮件地址",
  "Add to Calendar": "添加到日历",
  "Share this Event": "分享此活动",
  "Sorry something went wrong": "抱歉，出了一些问题",
  "Back to registration": "返回注册",
  "Date & Location": "日期和地点",
  "Date & Time": "约会时间",
  "home": "家",
  "Header align": "标头对齐",
  "Footer": "页脚",
  "Categories Filter": "类别筛选",
  "Show only upcoming": "仅显示即将举行的",
  "Card(s) in a row": "连续的卡片",
  "Space between cards": "卡之间的空间",
  "Shown events limit": "显示事件限制",
  "Style 1": "风格1",
  "Style 2": "风格2",
  "Style 3": "风格3",
  "Style 4": "风格4",
  "Buttons & Links": "按钮和链接",
  "Button corner radius": "按钮角半径",
  "Buttons font": "按钮字体",
  "Buttons background": "按钮背景",
  "Get notified by Email": "通过电子邮件通知",
  "Review events": "审查事件",
  "Click on date": "点击日期",
  "Add Event button": "添加事件按钮",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.": "日历同步允许您将事件和会话与Boom日历集成在一起。",
  "connect": "连接",
  "Synchronized Calendars": "同步日历",
  "Import events": "导入事件",
  "Disconnect": "断开",
  "Choose calendar": "选择日历",
  "Monitor your Wix events through the sync feature": "通过同步功能监视您的Wix事件",
  "Connect all your Boom calendars available on your website": "连接您网站上所有可用的Boom日历",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.": "计划，加入和管理通过我们的繁荣日历进行缩放会议。",
  "Monitor your Event Brite events through the Event Brite sync feature": "通过事件Brite同步功能监视您的事件Brite事件",
  "Email": "电子邮件",
  "Add-ons": "附加组件",
  "Receive notification emails as soon as users add events to your calendar.": "一旦用户将事件添加到日历，就会收到通知电子邮件。",
  "Enable + button on the calendar header": "在Calendar标题上启用+按钮",
  "Accept or decline events added by customers before making them public.": "在让他们公开之前接受或拒绝客户添加的事件。",
  "Switch Add Event": "切换添加事件",
  "Enable your browser cookies to connect to your account.": "启用您的浏览器cookie以连接到您的帐户。",
  "Learn more": "学到更多",
  "Print Button": "打印按钮",
  "Permit your users to print your Boom Event Calendar in any date range.": "允许您的用户在任何日期范围内打印您的Boom事件日历。",
  "Show Title on mobile": "在移动时显示标题",
  "Show Skeleton on mobile": "在移动设备上显示骨架",
  "Start 7-day Business trial": "启动7天的商业审判",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.": "享受所有无限功能，如卖票，注册，访客活动加载项。",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.": "请注意：在试用期结束时，您将返回现有的订阅计划。",
  "Not Now": "现在不要",
  "Start free trial": "开启免费体验",
  "Congrats!": "恭喜！",
  "Your 7-day Business trial has been successfully activated.": "您的7天商务审判已成功激活。",
  "Done": "完毕",
  "Title font color": "标题字体颜色",
  "Desciption font color": "描述字体颜色",
  "Section font color": "部分字体颜色",
  "Card Header": "卡片标题",
  "Category": "类别",
  "Display at the": "在展示",
  "top": "最佳",
  "bottom": "底部",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only": "在日历的顶部或底部展示类别过滤器。这些设置仅适用于议程和卡片视图",
  "Processing your events": "处理您的活动",
  "Search for events": "搜索事件",
  "There are no events added": "没有添加活动",
  "Location: To be determined": "位置：要确定",
  "No events for selected date": "没有选定日期的活动",
  "Uncategorized": "未分类",
  "Edit event": "编辑事件",
  "Edit original event": "编辑原始事件",
  "Copy event": "复制事件",
  "Copy as new event": "复制为新活动",
  "Delete event": "删除事件",
  "Stop repeating on this date": "停止在这个日期重复",
  "Exclude this date": "排除此日期",
  "Location is going to be announced": "地点将宣布",
  "Fill your personal information": "填写您的个人信息",
  "Check Box": "复选框",
  "Single Choice": "单一选择",
  "Option": "选项",
  "Share Event": "分享活动",
  "Oops! Something went wrong": "哎呀！出问题了",
  "We are sorry this event has already taken place": "我们很抱歉这项活动已经举行",
  "Back to calendar": "返回日历",
  "This field is required": "这是必填栏",
  "Phone": "电话",
  "Number field": "数字字段",
  "Option": "选项",
  "Check Box": "复选框",
  "Single Choice": "单一选择",
 "Please provide a valid email" : "请提供有效的电子邮件",
 "Select at least one option" : "选择至少一个选项"
}
export default zh-cn